#!/usr/bin/env bash
# Builds hello-panel-python.odmod: CPython 3.12 plus the standard library plus
# main.py, as one wasm module.
#
# Needs wasi-sdk 20 and a prebuilt libpython; tools/sdk_toolchains.sh installs
# both into .toolchains/.
#
# THE VERSION MATCH IS LOAD-BEARING. libpython is built against wasi-sdk 20's
# libc, and linking it with a newer wasi-sdk produces a module that loads, runs,
# and then faults with "out of bounds memory access" somewhere inside CPython's
# startup. It is not a warning, it is silent corruption -- so this script pins
# the SDK rather than searching PATH for whichever clang is around.
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../../../.." && pwd)"
sdk="$root/sdk"
pydir="$sdk/python"
TC="$root/.toolchains"

CC="${WASI_SDK_20_CC:-$TC/wasi-sdk-20/bin/clang}"
PYROOT="${GBX_LIBPYTHON:-$TC/libpython}"

[ -x "$CC" ] || {
    echo "wasi-sdk 20 not found at $CC" >&2
    echo "Install it with: tools/sdk_toolchains.sh install" >&2
    exit 1
}
[ -f "$PYROOT/lib/wasm32-wasi/libpython3.12.a" ] || {
    echo "libpython not found under $PYROOT" >&2
    echo "Install it with: tools/sdk_toolchains.sh install" >&2
    exit 1
}

# --- the standard library, frozen -------------------------------------------
# A mod has no filesystem, so CPython cannot read its stdlib from disk and will
# not start without `encodings`. gen_frozen.py turns the shipped .pyc files into
# a C table that PyImport_FrozenModules points at. See that script.
if [ ! -f "$here/frozen_stdlib.h" ] || \
   [ "$PYROOT/lib/python312.zip" -nt "$here/frozen_stdlib.h" ]; then
    python3 "$pydir/tools/gen_frozen.py" \
        "$PYROOT/lib/python312.zip" "$here/frozen_stdlib.h"
fi

# --- main.py -> script.h -----------------------------------------------------
python3 - "$here/main.py" "$here/script.h" <<'PY'
import sys, pathlib
src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
data = src.read_bytes()
# NUL-terminated: Py_CompileString takes a C string, like QuickJS and unlike Lua.
blob = data + b"\x00"
rows = [", ".join(f"0x{b:02x}" for b in blob[i:i+16]) for i in range(0, len(blob), 16)]
dst.write_text(
    "/* Generated by build.sh from %s. Do not edit. */\n"
    "#ifndef GBX_SCRIPT_H\n#define GBX_SCRIPT_H\n\n"
    "static const unsigned char gbx_script[] = {\n    %s\n};\n"
    "static const unsigned int gbx_script_len = %d;\n"
    "static const char gbx_script_name[] = \"%s\";\n\n"
    "#endif\n" % (src.name, ",\n    ".join(rows), len(data), src.name)
)
print(f"  embedded {src.name} ({len(data)} bytes)")
PY

# --- link --------------------------------------------------------------------
# -mexec-model=reactor: the host calls mod_load, not _start. Without it the
# module exports _start and CPython never initialises.
"$CC" -O2 -mexec-model=reactor \
      -I "$sdk" -I "$here" \
      -I "$PYROOT/include/python3.12" \
      -o "$here/mod.wasm" \
      "$pydir/gearbox_py.c" \
      "$PYROOT/lib/wasm32-wasi/libpython3.12.a" \
      -lwasi-emulated-mman -lwasi-emulated-signal \
      -lwasi-emulated-getpid -lwasi-emulated-process-clocks

python3 "$root/tools/wasm_imports.py" "$here/mod.wasm"
"$root/tools/pack_odmod.sh" "$here" "$here/hello-panel-python.odmod"

ls -l "$here/mod.wasm" "$here/hello-panel-python.odmod" \
    | awk '{printf "  %-12s %9d bytes\n", $NF, $5}'

cat <<'NOTE'

  NOTE: this mod needs a host built with -DOD_MODS_FAST_INTERP=OFF.
        CPython trips WAMR's fast-interpreter INT16_MAX operand-stack limit
        and will not load otherwise. See sdk/python/README.md.
NOTE
