// Generated by tools/gen_server_raylib_stubs.py -- do not edit by hand.
//
// The half of raylib the dedicated server does not do: drawing, textures,
// shaders, windows, input, audio. Each entry point is present so the game's
// source links, and does nothing when called.
//
// The hand-written half -- images, files, text, colour, time, everything the
// simulation reads its own data through -- is in ServerRaylib.cpp, and the two
// files together are the whole of raylib as far as the server is concerned. No
// GL, no GLFW and no audio device is linked into the server binary at all.
//
// Regenerate after a raylib upgrade:  python3 tools/gen_server_raylib_stubs.py

#include "raylib.h"

void AttachAudioMixedProcessor(AudioCallback processor) { }
void AttachAudioStreamProcessor(AudioStream stream, AudioCallback processor) { }
void BeginBlendMode(int mode) { }
void BeginDrawing(void) { }
void BeginMode2D(Camera2D camera) { }
void BeginMode3D(Camera3D camera) { }
void BeginScissorMode(int x, int y, int width, int height) { }
void BeginShaderMode(Shader shader) { }
void BeginTextureMode(RenderTexture2D target) { }
void BeginVrStereoMode(VrStereoConfig config) { }
bool ChangeDirectory(const char *dir) { return false; }
bool CheckCollisionBoxSphere(BoundingBox box, Vector3 center, float radius) { return false; }
bool CheckCollisionBoxes(BoundingBox box1, BoundingBox box2) { return false; }
bool CheckCollisionCircleLine(Vector2 center, float radius, Vector2 p1, Vector2 p2) { return false; }
bool CheckCollisionCircleRec(Vector2 center, float radius, Rectangle rec) { return false; }
bool CheckCollisionCircles(Vector2 center1, float radius1, Vector2 center2, float radius2) { return false; }
bool CheckCollisionLines(Vector2 startPos1, Vector2 endPos1, Vector2 startPos2, Vector2 endPos2, Vector2 *collisionPoint) { return false; }
bool CheckCollisionPointLine(Vector2 point, Vector2 p1, Vector2 p2, int threshold) { return false; }
bool CheckCollisionPointPoly(Vector2 point, const Vector2 *points, int pointCount) { return false; }
bool CheckCollisionPointTriangle(Vector2 point, Vector2 p1, Vector2 p2, Vector2 p3) { return false; }
bool CheckCollisionSpheres(Vector3 center1, float radius1, Vector3 center2, float radius2) { return false; }
void ClearBackground(Color color) { }
void ClearWindowState(unsigned int flags) { }
void CloseAudioDevice(void) { }
void CloseWindow(void) { }
const char * CodepointToUTF8(int codepoint, int *utf8Size) { return nullptr; }
Color ColorAlphaBlend(Color dst, Color src, Color tint) { return Color{}; }
Color ColorBrightness(Color color, float factor) { return Color{}; }
Color ColorContrast(Color color, float contrast) { return Color{}; }
Color ColorFromHSV(float hue, float saturation, float value) { return Color{}; }
Color ColorFromNormalized(Vector4 normalized) { return Color{}; }
bool ColorIsEqual(Color col1, Color col2) { return false; }
Color ColorLerp(Color color1, Color color2, float factor) { return Color{}; }
Vector4 ColorNormalize(Color color) { return Vector4{}; }
Color ColorTint(Color color, Color tint) { return Color{}; }
Vector3 ColorToHSV(Color color) { return Vector3{}; }
unsigned char * CompressData(const unsigned char *data, int dataSize, int *compDataSize) { return nullptr; }
unsigned int ComputeCRC32(unsigned char *data, int dataSize) { return 0; }
unsigned int * ComputeMD5(unsigned char *data, int dataSize) { return nullptr; }
unsigned int * ComputeSHA1(unsigned char *data, int dataSize) { return nullptr; }
unsigned char * DecodeDataBase64(const unsigned char *data, int *outputSize) { return nullptr; }
unsigned char * DecompressData(const unsigned char *compData, int compDataSize, int *dataSize) { return nullptr; }
void DetachAudioMixedProcessor(AudioCallback processor) { }
void DetachAudioStreamProcessor(AudioStream stream, AudioCallback processor) { }
void DisableCursor(void) { }
void DisableEventWaiting(void) { }
void DrawBillboard(Camera camera, Texture2D texture, Vector3 position, float scale, Color tint) { }
void DrawBillboardPro(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector3 up, Vector2 size, Vector2 origin, float rotation, Color tint) { }
void DrawBillboardRec(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector2 size, Color tint) { }
void DrawBoundingBox(BoundingBox box, Color color) { }
void DrawCapsule(Vector3 startPos, Vector3 endPos, float radius, int slices, int rings, Color color) { }
void DrawCapsuleWires(Vector3 startPos, Vector3 endPos, float radius, int slices, int rings, Color color) { }
void DrawCircle(int centerX, int centerY, float radius, Color color) { }
void DrawCircle3D(Vector3 center, float radius, Vector3 rotationAxis, float rotationAngle, Color color) { }
void DrawCircleGradient(int centerX, int centerY, float radius, Color inner, Color outer) { }
void DrawCircleLines(int centerX, int centerY, float radius, Color color) { }
void DrawCircleLinesV(Vector2 center, float radius, Color color) { }
void DrawCircleSector(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color) { }
void DrawCircleSectorLines(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color) { }
void DrawCircleV(Vector2 center, float radius, Color color) { }
void DrawCube(Vector3 position, float width, float height, float length, Color color) { }
void DrawCubeV(Vector3 position, Vector3 size, Color color) { }
void DrawCubeWires(Vector3 position, float width, float height, float length, Color color) { }
void DrawCubeWiresV(Vector3 position, Vector3 size, Color color) { }
void DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color) { }
void DrawCylinderEx(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color) { }
void DrawCylinderWires(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color) { }
void DrawCylinderWiresEx(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color) { }
void DrawEllipse(int centerX, int centerY, float radiusH, float radiusV, Color color) { }
void DrawEllipseLines(int centerX, int centerY, float radiusH, float radiusV, Color color) { }
void DrawFPS(int posX, int posY) { }
void DrawGrid(int slices, float spacing) { }
void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color) { }
void DrawLine3D(Vector3 startPos, Vector3 endPos, Color color) { }
void DrawLineBezier(Vector2 startPos, Vector2 endPos, float thick, Color color) { }
void DrawLineEx(Vector2 startPos, Vector2 endPos, float thick, Color color) { }
void DrawLineStrip(const Vector2 *points, int pointCount, Color color) { }
void DrawLineV(Vector2 startPos, Vector2 endPos, Color color) { }
void DrawMesh(Mesh mesh, Material material, Matrix transform) { }
void DrawMeshInstanced(Mesh mesh, Material material, const Matrix *transforms, int instances) { }
void DrawModel(Model model, Vector3 position, float scale, Color tint) { }
void DrawModelEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint) { }
void DrawModelPoints(Model model, Vector3 position, float scale, Color tint) { }
void DrawModelPointsEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint) { }
void DrawModelWires(Model model, Vector3 position, float scale, Color tint) { }
void DrawModelWiresEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint) { }
void DrawPixel(int posX, int posY, Color color) { }
void DrawPixelV(Vector2 position, Color color) { }
void DrawPlane(Vector3 centerPos, Vector2 size, Color color) { }
void DrawPoint3D(Vector3 position, Color color) { }
void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color) { }
void DrawPolyLines(Vector2 center, int sides, float radius, float rotation, Color color) { }
void DrawPolyLinesEx(Vector2 center, int sides, float radius, float rotation, float lineThick, Color color) { }
void DrawRay(Ray ray, Color color) { }
void DrawRectangle(int posX, int posY, int width, int height, Color color) { }
void DrawRectangleGradientEx(Rectangle rec, Color topLeft, Color bottomLeft, Color topRight, Color bottomRight) { }
void DrawRectangleGradientH(int posX, int posY, int width, int height, Color left, Color right) { }
void DrawRectangleGradientV(int posX, int posY, int width, int height, Color top, Color bottom) { }
void DrawRectangleLines(int posX, int posY, int width, int height, Color color) { }
void DrawRectangleLinesEx(Rectangle rec, float lineThick, Color color) { }
void DrawRectanglePro(Rectangle rec, Vector2 origin, float rotation, Color color) { }
void DrawRectangleRec(Rectangle rec, Color color) { }
void DrawRectangleRounded(Rectangle rec, float roundness, int segments, Color color) { }
void DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, Color color) { }
void DrawRectangleRoundedLinesEx(Rectangle rec, float roundness, int segments, float lineThick, Color color) { }
void DrawRectangleV(Vector2 position, Vector2 size, Color color) { }
void DrawRing(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color) { }
void DrawRingLines(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color) { }
void DrawSphere(Vector3 centerPos, float radius, Color color) { }
void DrawSphereEx(Vector3 centerPos, float radius, int rings, int slices, Color color) { }
void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color) { }
void DrawSplineBasis(const Vector2 *points, int pointCount, float thick, Color color) { }
void DrawSplineBezierCubic(const Vector2 *points, int pointCount, float thick, Color color) { }
void DrawSplineBezierQuadratic(const Vector2 *points, int pointCount, float thick, Color color) { }
void DrawSplineCatmullRom(const Vector2 *points, int pointCount, float thick, Color color) { }
void DrawSplineLinear(const Vector2 *points, int pointCount, float thick, Color color) { }
void DrawSplineSegmentBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color) { }
void DrawSplineSegmentBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float thick, Color color) { }
void DrawSplineSegmentBezierQuadratic(Vector2 p1, Vector2 c2, Vector2 p3, float thick, Color color) { }
void DrawSplineSegmentCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color) { }
void DrawSplineSegmentLinear(Vector2 p1, Vector2 p2, float thick, Color color) { }
void DrawText(const char *text, int posX, int posY, int fontSize, Color color) { }
void DrawTextCodepoint(Font font, int codepoint, Vector2 position, float fontSize, Color tint) { }
void DrawTextCodepoints(Font font, const int *codepoints, int codepointCount, Vector2 position, float fontSize, float spacing, Color tint) { }
void DrawTextEx(Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint) { }
void DrawTextPro(Font font, const char *text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, Color tint) { }
void DrawTexture(Texture2D texture, int posX, int posY, Color tint) { }
void DrawTextureEx(Texture2D texture, Vector2 position, float rotation, float scale, Color tint) { }
void DrawTextureNPatch(Texture2D texture, NPatchInfo nPatchInfo, Rectangle dest, Vector2 origin, float rotation, Color tint) { }
void DrawTexturePro(Texture2D texture, Rectangle source, Rectangle dest, Vector2 origin, float rotation, Color tint) { }
void DrawTextureRec(Texture2D texture, Rectangle source, Vector2 position, Color tint) { }
void DrawTextureV(Texture2D texture, Vector2 position, Color tint) { }
void DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color) { }
void DrawTriangle3D(Vector3 v1, Vector3 v2, Vector3 v3, Color color) { }
void DrawTriangleFan(const Vector2 *points, int pointCount, Color color) { }
void DrawTriangleLines(Vector2 v1, Vector2 v2, Vector2 v3, Color color) { }
void DrawTriangleStrip(const Vector2 *points, int pointCount, Color color) { }
void DrawTriangleStrip3D(const Vector3 *points, int pointCount, Color color) { }
void EnableCursor(void) { }
void EnableEventWaiting(void) { }
char * EncodeDataBase64(const unsigned char *data, int dataSize, int *outputSize) { return nullptr; }
void EndBlendMode(void) { }
void EndDrawing(void) { }
void EndMode2D(void) { }
void EndMode3D(void) { }
void EndScissorMode(void) { }
void EndShaderMode(void) { }
void EndTextureMode(void) { }
void EndVrStereoMode(void) { }
bool ExportAutomationEventList(AutomationEventList list, const char *fileName) { return false; }
bool ExportDataAsCode(const unsigned char *data, int dataSize, const char *fileName) { return false; }
bool ExportFontAsCode(Font font, const char *fileName) { return false; }
bool ExportImageAsCode(Image image, const char *fileName) { return false; }
unsigned char * ExportImageToMemory(Image image, const char *fileType, int *fileSize) { return nullptr; }
bool ExportMesh(Mesh mesh, const char *fileName) { return false; }
bool ExportMeshAsCode(Mesh mesh, const char *fileName) { return false; }
bool ExportWave(Wave wave, const char *fileName) { return false; }
bool ExportWaveAsCode(Wave wave, const char *fileName) { return false; }
Image GenImageCellular(int width, int height, int tileSize) { return Image{}; }
Image GenImageChecked(int width, int height, int checksX, int checksY, Color col1, Color col2) { return Image{}; }
Image GenImageFontAtlas(const GlyphInfo *glyphs, Rectangle **glyphRecs, int glyphCount, int fontSize, int padding, int packMethod) { return Image{}; }
Image GenImageGradientLinear(int width, int height, int direction, Color start, Color end) { return Image{}; }
Image GenImageGradientRadial(int width, int height, float density, Color inner, Color outer) { return Image{}; }
Image GenImageGradientSquare(int width, int height, float density, Color inner, Color outer) { return Image{}; }
Image GenImagePerlinNoise(int width, int height, int offsetX, int offsetY, float scale) { return Image{}; }
Image GenImageText(int width, int height, const char *text) { return Image{}; }
Image GenImageWhiteNoise(int width, int height, float factor) { return Image{}; }
Mesh GenMeshCone(float radius, float height, int slices) { return Mesh{}; }
Mesh GenMeshCube(float width, float height, float length) { return Mesh{}; }
Mesh GenMeshCubicmap(Image cubicmap, Vector3 cubeSize) { return Mesh{}; }
Mesh GenMeshCylinder(float radius, float height, int slices) { return Mesh{}; }
Mesh GenMeshHeightmap(Image heightmap, Vector3 size) { return Mesh{}; }
Mesh GenMeshHemiSphere(float radius, int rings, int slices) { return Mesh{}; }
Mesh GenMeshKnot(float radius, float size, int radSeg, int sides) { return Mesh{}; }
Mesh GenMeshPlane(float width, float length, int resX, int resZ) { return Mesh{}; }
Mesh GenMeshPoly(int sides, float radius) { return Mesh{}; }
Mesh GenMeshSphere(float radius, int rings, int slices) { return Mesh{}; }
void GenMeshTangents(Mesh *mesh) { }
Mesh GenMeshTorus(float radius, float size, int radSeg, int sides) { return Mesh{}; }
void GenTextureMipmaps(Texture2D *texture) { }
Matrix GetCameraMatrix(Camera camera) { return Matrix{}; }
Matrix GetCameraMatrix2D(Camera2D camera) { return Matrix{}; }
int GetCharPressed(void) { return 0; }
Image GetClipboardImage(void) { return Image{}; }
const char * GetClipboardText(void) { return nullptr; }
int GetCodepoint(const char *text, int *codepointSize) { return 0; }
int GetCodepointCount(const char *text) { return 0; }
int GetCodepointNext(const char *text, int *codepointSize) { return 0; }
int GetCodepointPrevious(const char *text, int *codepointSize) { return 0; }
Rectangle GetCollisionRec(Rectangle rec1, Rectangle rec2) { return Rectangle{}; }
int GetCurrentMonitor(void) { return 0; }
const char * GetDirectoryPath(const char *filePath) { return nullptr; }
const char * GetFileExtension(const char *fileName) { return nullptr; }
int GetFileLength(const char *fileName) { return 0; }
long GetFileModTime(const char *fileName) { return 0; }
const char * GetFileName(const char *filePath) { return nullptr; }
const char * GetFileNameWithoutExt(const char *filePath) { return nullptr; }
Font GetFontDefault(void) { return Font{}; }
int GetGamepadAxisCount(int gamepad) { return 0; }
float GetGamepadAxisMovement(int gamepad, int axis) { return 0; }
int GetGamepadButtonPressed(void) { return 0; }
const char * GetGamepadName(int gamepad) { return nullptr; }
int GetGestureDetected(void) { return 0; }
float GetGestureDragAngle(void) { return 0; }
Vector2 GetGestureDragVector(void) { return Vector2{}; }
float GetGestureHoldDuration(void) { return 0; }
float GetGesturePinchAngle(void) { return 0; }
Vector2 GetGesturePinchVector(void) { return Vector2{}; }
Rectangle GetGlyphAtlasRec(Font font, int codepoint) { return Rectangle{}; }
int GetGlyphIndex(Font font, int codepoint) { return 0; }
GlyphInfo GetGlyphInfo(Font font, int codepoint) { return GlyphInfo{}; }
Rectangle GetImageAlphaBorder(Image image, float threshold) { return Rectangle{}; }
int GetKeyPressed(void) { return 0; }
float GetMasterVolume(void) { return 0; }
BoundingBox GetMeshBoundingBox(Mesh mesh) { return BoundingBox{}; }
BoundingBox GetModelBoundingBox(Model model) { return BoundingBox{}; }
int GetMonitorCount(void) { return 0; }
int GetMonitorHeight(int monitor) { return 0; }
const char * GetMonitorName(int monitor) { return nullptr; }
int GetMonitorPhysicalHeight(int monitor) { return 0; }
int GetMonitorPhysicalWidth(int monitor) { return 0; }
Vector2 GetMonitorPosition(int monitor) { return Vector2{}; }
int GetMonitorRefreshRate(int monitor) { return 0; }
int GetMonitorWidth(int monitor) { return 0; }
Vector2 GetMouseDelta(void) { return Vector2{}; }
Vector2 GetMousePosition(void) { return Vector2{}; }
float GetMouseWheelMove(void) { return 0; }
Vector2 GetMouseWheelMoveV(void) { return Vector2{}; }
int GetMouseX(void) { return 0; }
int GetMouseY(void) { return 0; }
float GetMusicTimeLength(Music music) { return 0; }
float GetMusicTimePlayed(Music music) { return 0; }
Color GetPixelColor(void *srcPtr, int format) { return Color{}; }
int GetPixelDataSize(int width, int height, int format) { return 0; }
const char * GetPrevDirectoryPath(const char *dirPath) { return nullptr; }
RayCollision GetRayCollisionBox(Ray ray, BoundingBox box) { return RayCollision{}; }
RayCollision GetRayCollisionMesh(Ray ray, Mesh mesh, Matrix transform) { return RayCollision{}; }
RayCollision GetRayCollisionQuad(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 p4) { return RayCollision{}; }
RayCollision GetRayCollisionSphere(Ray ray, Vector3 center, float radius) { return RayCollision{}; }
RayCollision GetRayCollisionTriangle(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3) { return RayCollision{}; }
Vector2 GetScreenToWorld2D(Vector2 position, Camera2D camera) { return Vector2{}; }
Ray GetScreenToWorldRay(Vector2 position, Camera camera) { return Ray{}; }
Ray GetScreenToWorldRayEx(Vector2 position, Camera camera, int width, int height) { return Ray{}; }
int GetShaderLocation(Shader shader, const char *uniformName) { return 0; }
int GetShaderLocationAttrib(Shader shader, const char *attribName) { return 0; }
Texture2D GetShapesTexture(void) { return Texture2D{}; }
Rectangle GetShapesTextureRectangle(void) { return Rectangle{}; }
Vector2 GetSplinePointBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t) { return Vector2{}; }
Vector2 GetSplinePointBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float t) { return Vector2{}; }
Vector2 GetSplinePointBezierQuad(Vector2 p1, Vector2 c2, Vector2 p3, float t) { return Vector2{}; }
Vector2 GetSplinePointCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t) { return Vector2{}; }
Vector2 GetSplinePointLinear(Vector2 startPos, Vector2 endPos, float t) { return Vector2{}; }
int GetTouchPointCount(void) { return 0; }
int GetTouchPointId(int index) { return 0; }
Vector2 GetTouchPosition(int index) { return Vector2{}; }
int GetTouchX(void) { return 0; }
int GetTouchY(void) { return 0; }
void * GetWindowHandle(void) { return nullptr; }
Vector2 GetWindowPosition(void) { return Vector2{}; }
Vector2 GetWindowScaleDPI(void) { return Vector2{}; }
const char * GetWorkingDirectory(void) { return nullptr; }
Vector2 GetWorldToScreen(Vector3 position, Camera camera) { return Vector2{}; }
Vector2 GetWorldToScreen2D(Vector2 position, Camera2D camera) { return Vector2{}; }
Vector2 GetWorldToScreenEx(Vector3 position, Camera camera, int width, int height) { return Vector2{}; }
void HideCursor(void) { }
void ImageAlphaClear(Image *image, Color color, float threshold) { }
void ImageAlphaCrop(Image *image, float threshold) { }
void ImageAlphaMask(Image *image, Image alphaMask) { }
void ImageAlphaPremultiply(Image *image) { }
void ImageBlurGaussian(Image *image, int blurSize) { }
void ImageClearBackground(Image *dst, Color color) { }
void ImageColorBrightness(Image *image, int brightness) { }
void ImageColorContrast(Image *image, float contrast) { }
void ImageColorGrayscale(Image *image) { }
void ImageColorInvert(Image *image) { }
void ImageColorReplace(Image *image, Color color, Color replace) { }
void ImageColorTint(Image *image, Color color) { }
void ImageCrop(Image *image, Rectangle crop) { }
void ImageDither(Image *image, int rBpp, int gBpp, int bBpp, int aBpp) { }
void ImageDraw(Image *dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint) { }
void ImageDrawCircle(Image *dst, int centerX, int centerY, int radius, Color color) { }
void ImageDrawCircleLines(Image *dst, int centerX, int centerY, int radius, Color color) { }
void ImageDrawCircleLinesV(Image *dst, Vector2 center, int radius, Color color) { }
void ImageDrawCircleV(Image *dst, Vector2 center, int radius, Color color) { }
void ImageDrawLine(Image *dst, int startPosX, int startPosY, int endPosX, int endPosY, Color color) { }
void ImageDrawLineEx(Image *dst, Vector2 start, Vector2 end, int thick, Color color) { }
void ImageDrawLineV(Image *dst, Vector2 start, Vector2 end, Color color) { }
void ImageDrawPixelV(Image *dst, Vector2 position, Color color) { }
void ImageDrawRectangleLines(Image *dst, Rectangle rec, int thick, Color color) { }
void ImageDrawRectangleRec(Image *dst, Rectangle rec, Color color) { }
void ImageDrawRectangleV(Image *dst, Vector2 position, Vector2 size, Color color) { }
void ImageDrawText(Image *dst, const char *text, int posX, int posY, int fontSize, Color color) { }
void ImageDrawTextEx(Image *dst, Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint) { }
void ImageDrawTriangle(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color) { }
void ImageDrawTriangleEx(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color c1, Color c2, Color c3) { }
void ImageDrawTriangleFan(Image *dst, Vector2 *points, int pointCount, Color color) { }
void ImageDrawTriangleLines(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color) { }
void ImageDrawTriangleStrip(Image *dst, Vector2 *points, int pointCount, Color color) { }
void ImageFlipHorizontal(Image *image) { }
void ImageFlipVertical(Image *image) { }
Image ImageFromChannel(Image image, int selectedChannel) { return Image{}; }
Image ImageFromImage(Image image, Rectangle rec) { return Image{}; }
void ImageKernelConvolution(Image *image, const float *kernel, int kernelSize) { }
void ImageMipmaps(Image *image) { }
void ImageResizeCanvas(Image *image, int newWidth, int newHeight, int offsetX, int offsetY, Color fill) { }
void ImageRotate(Image *image, int degrees) { }
void ImageRotateCCW(Image *image) { }
void ImageRotateCW(Image *image) { }
Image ImageText(const char *text, int fontSize, Color color) { return Image{}; }
Image ImageTextEx(Font font, const char *text, float fontSize, float spacing, Color tint) { return Image{}; }
void ImageToPOT(Image *image, Color fill) { }
void InitAudioDevice(void) { }
void InitWindow(int width, int height, const char *title) { }
bool IsAudioDeviceReady(void) { return false; }
bool IsAudioStreamPlaying(AudioStream stream) { return false; }
bool IsAudioStreamProcessed(AudioStream stream) { return false; }
bool IsAudioStreamValid(AudioStream stream) { return false; }
bool IsCursorHidden(void) { return false; }
bool IsCursorOnScreen(void) { return false; }
bool IsFileDropped(void) { return false; }
bool IsFileExtension(const char *fileName, const char *ext) { return false; }
bool IsFileNameValid(const char *fileName) { return false; }
bool IsFontValid(Font font) { return false; }
bool IsGamepadAvailable(int gamepad) { return false; }
bool IsGamepadButtonDown(int gamepad, int button) { return false; }
bool IsGamepadButtonPressed(int gamepad, int button) { return false; }
bool IsGamepadButtonReleased(int gamepad, int button) { return false; }
bool IsGamepadButtonUp(int gamepad, int button) { return false; }
bool IsGestureDetected(unsigned int gesture) { return false; }
bool IsImageValid(Image image) { return false; }
bool IsKeyDown(int key) { return false; }
bool IsKeyPressed(int key) { return false; }
bool IsKeyPressedRepeat(int key) { return false; }
bool IsKeyReleased(int key) { return false; }
bool IsKeyUp(int key) { return false; }
bool IsMaterialValid(Material material) { return false; }
bool IsModelAnimationValid(Model model, ModelAnimation anim) { return false; }
bool IsModelValid(Model model) { return false; }
bool IsMouseButtonDown(int button) { return false; }
bool IsMouseButtonPressed(int button) { return false; }
bool IsMouseButtonReleased(int button) { return false; }
bool IsMouseButtonUp(int button) { return false; }
bool IsMusicStreamPlaying(Music music) { return false; }
bool IsMusicValid(Music music) { return false; }
bool IsRenderTextureValid(RenderTexture2D target) { return false; }
bool IsShaderValid(Shader shader) { return false; }
bool IsSoundPlaying(Sound sound) { return false; }
bool IsSoundValid(Sound sound) { return false; }
bool IsTextureValid(Texture2D texture) { return false; }
bool IsWaveValid(Wave wave) { return false; }
bool IsWindowHidden(void) { return false; }
bool IsWindowMaximized(void) { return false; }
bool IsWindowState(unsigned int flag) { return false; }
AudioStream LoadAudioStream(unsigned int sampleRate, unsigned int sampleSize, unsigned int channels) { return AudioStream{}; }
AutomationEventList LoadAutomationEventList(const char *fileName) { return AutomationEventList{}; }
int * LoadCodepoints(const char *text, int *count) { return nullptr; }
FilePathList LoadDirectoryFilesEx(const char *basePath, const char *filter, bool scanSubdirs) { return FilePathList{}; }
FilePathList LoadDroppedFiles(void) { return FilePathList{}; }
Font LoadFont(const char *fileName) { return Font{}; }
GlyphInfo * LoadFontData(const unsigned char *fileData, int dataSize, int fontSize, int *codepoints, int codepointCount, int type) { return nullptr; }
Font LoadFontEx(const char *fileName, int fontSize, int *codepoints, int codepointCount) { return Font{}; }
Font LoadFontFromImage(Image image, Color key, int firstChar) { return Font{}; }
Font LoadFontFromMemory(const char *fileType, const unsigned char *fileData, int dataSize, int fontSize, int *codepoints, int codepointCount) { return Font{}; }
Image LoadImageAnim(const char *fileName, int *frames) { return Image{}; }
Image LoadImageAnimFromMemory(const char *fileType, const unsigned char *fileData, int dataSize, int *frames) { return Image{}; }
Image LoadImageFromScreen(void) { return Image{}; }
Image LoadImageFromTexture(Texture2D texture) { return Image{}; }
Color * LoadImagePalette(Image image, int maxPaletteSize, int *colorCount) { return nullptr; }
Image LoadImageRaw(const char *fileName, int width, int height, int format, int headerSize) { return Image{}; }
Material LoadMaterialDefault(void) { return Material{}; }
Material * LoadMaterials(const char *fileName, int *materialCount) { return nullptr; }
Model LoadModel(const char *fileName) { return Model{}; }
ModelAnimation * LoadModelAnimations(const char *fileName, int *animCount) { return nullptr; }
Model LoadModelFromMesh(Mesh mesh) { return Model{}; }
Music LoadMusicStream(const char *fileName) { return Music{}; }
Music LoadMusicStreamFromMemory(const char *fileType, const unsigned char *data, int dataSize) { return Music{}; }
int * LoadRandomSequence(unsigned int count, int min, int max) { return nullptr; }
RenderTexture2D LoadRenderTexture(int width, int height) { return RenderTexture2D{}; }
Shader LoadShader(const char *vsFileName, const char *fsFileName) { return Shader{}; }
Shader LoadShaderFromMemory(const char *vsCode, const char *fsCode) { return Shader{}; }
Sound LoadSound(const char *fileName) { return Sound{}; }
Sound LoadSoundAlias(Sound source) { return Sound{}; }
Sound LoadSoundFromWave(Wave wave) { return Sound{}; }
Texture2D LoadTexture(const char *fileName) { return Texture2D{}; }
TextureCubemap LoadTextureCubemap(Image image, int layout) { return TextureCubemap{}; }
Texture2D LoadTextureFromImage(Image image) { return Texture2D{}; }
char * LoadUTF8(const int *codepoints, int length) { return nullptr; }
VrStereoConfig LoadVrStereoConfig(VrDeviceInfo device) { return VrStereoConfig{}; }
Wave LoadWave(const char *fileName) { return Wave{}; }
Wave LoadWaveFromMemory(const char *fileType, const unsigned char *fileData, int dataSize) { return Wave{}; }
float * LoadWaveSamples(Wave wave) { return nullptr; }
int MakeDirectory(const char *dirPath) { return 0; }
void MaximizeWindow(void) { }
void * MemAlloc(unsigned int size) { return nullptr; }
void MemFree(void *ptr) { }
void * MemRealloc(void *ptr, unsigned int size) { return nullptr; }
void MinimizeWindow(void) { }
void OpenURL(const char *url) { }
void PauseAudioStream(AudioStream stream) { }
void PauseMusicStream(Music music) { }
void PauseSound(Sound sound) { }
void PlayAudioStream(AudioStream stream) { }
void PlayAutomationEvent(AutomationEvent event) { }
void PlayMusicStream(Music music) { }
void PlaySound(Sound sound) { }
void PollInputEvents(void) { }
void RestoreWindow(void) { }
void ResumeAudioStream(AudioStream stream) { }
void ResumeMusicStream(Music music) { }
void ResumeSound(Sound sound) { }
bool SaveFileText(const char *fileName, char *text) { return false; }
void SeekMusicStream(Music music, float position) { }
void SetAudioStreamBufferSizeDefault(int size) { }
void SetAudioStreamCallback(AudioStream stream, AudioCallback callback) { }
void SetAudioStreamPan(AudioStream stream, float pan) { }
void SetAudioStreamPitch(AudioStream stream, float pitch) { }
void SetAudioStreamVolume(AudioStream stream, float volume) { }
void SetAutomationEventBaseFrame(int frame) { }
void SetAutomationEventList(AutomationEventList *list) { }
void SetClipboardText(const char *text) { }
void SetConfigFlags(unsigned int flags) { }
void SetExitKey(int key) { }
int SetGamepadMappings(const char *mappings) { return 0; }
void SetGamepadVibration(int gamepad, float leftMotor, float rightMotor, float duration) { }
void SetGesturesEnabled(unsigned int flags) { }
void SetLoadFileDataCallback(LoadFileDataCallback callback) { }
void SetLoadFileTextCallback(LoadFileTextCallback callback) { }
void SetMasterVolume(float volume) { }
void SetMaterialTexture(Material *material, int mapType, Texture2D texture) { }
void SetModelMeshMaterial(Model *model, int meshId, int materialId) { }
void SetMouseCursor(int cursor) { }
void SetMouseOffset(int offsetX, int offsetY) { }
void SetMousePosition(int x, int y) { }
void SetMouseScale(float scaleX, float scaleY) { }
void SetMusicPan(Music music, float pan) { }
void SetMusicPitch(Music music, float pitch) { }
void SetMusicVolume(Music music, float volume) { }
void SetPixelColor(void *dstPtr, Color color, int format) { }
void SetSaveFileDataCallback(SaveFileDataCallback callback) { }
void SetSaveFileTextCallback(SaveFileTextCallback callback) { }
void SetShaderValue(Shader shader, int locIndex, const void *value, int uniformType) { }
void SetShaderValueMatrix(Shader shader, int locIndex, Matrix mat) { }
void SetShaderValueTexture(Shader shader, int locIndex, Texture2D texture) { }
void SetShaderValueV(Shader shader, int locIndex, const void *value, int uniformType, int count) { }
void SetShapesTexture(Texture2D texture, Rectangle source) { }
void SetSoundPan(Sound sound, float pan) { }
void SetSoundPitch(Sound sound, float pitch) { }
void SetSoundVolume(Sound sound, float volume) { }
void SetTextLineSpacing(int spacing) { }
void SetTextureFilter(Texture2D texture, int filter) { }
void SetTextureWrap(Texture2D texture, int wrap) { }
void SetTraceLogCallback(TraceLogCallback callback) { }
void SetTraceLogLevel(int logLevel) { }
void SetWindowFocused(void) { }
void SetWindowIcon(Image image) { }
void SetWindowIcons(Image *images, int count) { }
void SetWindowMaxSize(int width, int height) { }
void SetWindowMinSize(int width, int height) { }
void SetWindowMonitor(int monitor) { }
void SetWindowOpacity(float opacity) { }
void SetWindowPosition(int x, int y) { }
void SetWindowSize(int width, int height) { }
void SetWindowState(unsigned int flags) { }
void SetWindowTitle(const char *title) { }
void ShowCursor(void) { }
void StartAutomationEventRecording(void) { }
void StopAudioStream(AudioStream stream) { }
void StopAutomationEventRecording(void) { }
void StopMusicStream(Music music) { }
void StopSound(Sound sound) { }
void SwapScreenBuffer(void) { }
void TakeScreenshot(const char *fileName) { }
void TextAppend(char *text, const char *append, int *position) { }
int TextCopy(char *dst, const char *src) { return 0; }
int TextFindIndex(const char *text, const char *find) { return 0; }
char * TextInsert(const char *text, const char *insert, int position) { return nullptr; }
bool TextIsEqual(const char *text1, const char *text2) { return false; }
const char * TextJoin(const char **textList, int count, const char *delimiter) { return nullptr; }
unsigned int TextLength(const char *text) { return 0; }
char * TextReplace(const char *text, const char *replace, const char *by) { return nullptr; }
const char ** TextSplit(const char *text, char delimiter, int *count) { return nullptr; }
const char * TextSubtext(const char *text, int position, int length) { return nullptr; }
const char * TextToCamel(const char *text) { return nullptr; }
float TextToFloat(const char *text) { return 0; }
int TextToInteger(const char *text) { return 0; }
const char * TextToLower(const char *text) { return nullptr; }
const char * TextToPascal(const char *text) { return nullptr; }
const char * TextToSnake(const char *text) { return nullptr; }
const char * TextToUpper(const char *text) { return nullptr; }
void ToggleBorderlessWindowed(void) { }
void ToggleFullscreen(void) { }
void TraceLog(int logLevel, const char *text, ...) { }
void UnloadAudioStream(AudioStream stream) { }
void UnloadAutomationEventList(AutomationEventList list) { }
void UnloadCodepoints(int *codepoints) { }
void UnloadDroppedFiles(FilePathList files) { }
void UnloadFont(Font font) { }
void UnloadFontData(GlyphInfo *glyphs, int glyphCount) { }
void UnloadImagePalette(Color *colors) { }
void UnloadMaterial(Material material) { }
void UnloadMesh(Mesh mesh) { }
void UnloadModel(Model model) { }
void UnloadModelAnimation(ModelAnimation anim) { }
void UnloadModelAnimations(ModelAnimation *animations, int animCount) { }
void UnloadMusicStream(Music music) { }
void UnloadRandomSequence(int *sequence) { }
void UnloadRenderTexture(RenderTexture2D target) { }
void UnloadShader(Shader shader) { }
void UnloadSound(Sound sound) { }
void UnloadSoundAlias(Sound alias) { }
void UnloadTexture(Texture2D texture) { }
void UnloadUTF8(char *text) { }
void UnloadVrStereoConfig(VrStereoConfig config) { }
void UnloadWave(Wave wave) { }
void UnloadWaveSamples(float *samples) { }
void UpdateAudioStream(AudioStream stream, const void *data, int frameCount) { }
void UpdateCamera(Camera *camera, int mode) { }
void UpdateCameraPro(Camera *camera, Vector3 movement, Vector3 rotation, float zoom) { }
void UpdateMeshBuffer(Mesh mesh, int index, const void *data, int dataSize, int offset) { }
void UpdateModelAnimation(Model model, ModelAnimation anim, int frame) { }
void UpdateModelAnimationBones(Model model, ModelAnimation anim, int frame) { }
void UpdateMusicStream(Music music) { }
void UpdateSound(Sound sound, const void *data, int sampleCount) { }
void UpdateTexture(Texture2D texture, const void *pixels) { }
void UpdateTextureRec(Texture2D texture, Rectangle rec, const void *pixels) { }
void UploadMesh(Mesh *mesh, bool dynamic) { }
Wave WaveCopy(Wave wave) { return Wave{}; }
void WaveCrop(Wave *wave, int initFrame, int finalFrame) { }
void WaveFormat(Wave *wave, int sampleRate, int sampleSize, int channels) { }

// 529 entry points.
