#!/usr/bin/env bash
# Builds custom-doctrine-lua.odmod: Lua 5.4.7 plus this mod, as one wasm module.
#
# THE DOCTRINES ARE NOT IN THIS DIRECTORY. They are read straight out of
# sdk/examples/custom-doctrine/doctrines.json, the C example's copy, because
# these two mods ARE the same mod in two languages and a second copy of the
# data would drift from the first the day somebody tuned a lever. It is also
# the file PolicyRulesTest loads, so what this mod ships is what the suite
# checks against a real game.
#
# This turns that file into a Lua table and puts the table in front of main.lua
# in one chunk, because the sandbox has no filesystem and so no `require`.
#
# Needs emcc, for the reason ../hello-panel/build.sh gives: Lua wants a libc.
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../../../.." && pwd)"
sdk="$root/sdk"
luadir="$sdk/lua"

LUA_VER=5.4.7
src="$luadir/.lua-src/lua-$LUA_VER/src"

command -v emcc >/dev/null 2>&1 || {
    echo "emcc not found. Install Emscripten: https://emscripten.org/docs/getting_started/downloads.html" >&2
    exit 1
}

if [ ! -d "$src" ]; then
    echo "fetching lua-$LUA_VER..."
    mkdir -p "$luadir/.lua-src"
    curl -fsSL "https://www.lua.org/ftp/lua-$LUA_VER.tar.gz" \
        | tar xz -C "$luadir/.lua-src"
fi

# --- doctrines.json + main.lua -> bundle.lua ---------------------------------
doctrines="$sdk/examples/custom-doctrine/doctrines.json"
[ -f "$doctrines" ] || { echo "no $doctrines -- the C example is where the data lives" >&2; exit 1; }
python3 - "$doctrines" "$here/main.lua" "$here/bundle.lua" <<'PY'
import json, pathlib, sys

data, mod, out = (pathlib.Path(p) for p in sys.argv[1:4])
entries = json.loads(data.read_text())
if not isinstance(entries, list) or not entries:
    sys.exit("%s must be a non-empty array of doctrines" % data.name)


def lua_string(s: str) -> str:
    """A Lua string literal. Escaped rather than a [==[ long bracket: a
    definition that happened to contain the closing bracket would end the
    literal early, and JSON is exactly the kind of text that eventually does."""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':     out.append('\\"')
        elif ch == "\\":  out.append("\\\\")
        elif ch == "\n":  out.append("\\n")
        elif o < 0x20:    out.append("\\%d" % o)
        else:             out.append(ch)
    out.append('"')
    return "".join(out)


rows = []
for e in entries:
    ident = e.get("id", "")
    if not ident:
        sys.exit("every doctrine needs an id")
    # Minified: the definition crosses the ABI as bytes, and the whitespace
    # that makes doctrines.json readable is dead weight in the module.
    rows.append("  { id = %s,\n    json = %s },"
                % (lua_string(ident), lua_string(json.dumps(e, separators=(",", ":")))))

prelude = (
    "-- Generated by build.sh from %s. Do not edit.\n"
    "-- `local` at chunk scope, so main.lua below sees it without a global.\n"
    "local doctrines = {\n%s\n}\n\n" % (data.name, "\n".join(rows))
)
out.write_text(prelude + mod.read_text())
print("  bundled %d doctrine(s): %s"
      % (len(entries), ", ".join(e["id"] for e in entries)))
PY

# --- bundle.lua -> script.h --------------------------------------------------
python3 - "$here/bundle.lua" "$here/script.h" <<'PY'
import sys, pathlib
src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
data = src.read_bytes()
rows = [", ".join(f"0x{b:02x}" for b in data[i:i+16]) for i in range(0, len(data), 16)]
dst.write_text(
    "/* Generated by build.sh from %s. Do not edit. */\n"
    "#ifndef GBX_SCRIPT_H\n#define GBX_SCRIPT_H\n\n"
    "static const unsigned char gbx_script[] = {\n    %s\n};\n"
    "static const unsigned int gbx_script_len = %d;\n"
    "static const char gbx_script_name[] = \"@%s\";\n\n"
    "#endif\n" % (src.name, ",\n    ".join(rows), len(data), src.name)
)
print(f"  embedded {src.name} ({len(data)} bytes)")
PY

# --- Lua core ----------------------------------------------------------------
# Identical to ../hello-panel/build.sh; see that file for why each flag is
# load-bearing and why these four libraries are left out.
core="lapi lcode lctype ldebug ldo ldump lfunc lgc llex lmem lobject lopcodes
      lparser lstate lstring ltable ltm lundump lvm lzio
      lbaselib lcorolib lmathlib lstrlib ltablib lutf8lib"

srcs=""
for f in $core; do srcs="$srcs $src/$f.c"; done

obj="$luadir/.lua-src/lauxlib.o"
emcc -O2 -c -DNDEBUG \
     -DluaL_loadfilex=gbx_lua_unused_loadfilex \
     -ffunction-sections -fdata-sections \
     -I "$sdk" -I "$luadir" -I "$src" \
     -include "$luadir/gbx_throw.h" \
     -o "$obj" "$src/lauxlib.c"

# THREE flags, and the two ZEROES matter as much as the one.
#
# -DGBX_WITH_CONTENT=1 binds the gearbox:content group. Every wasm import must
# resolve at instantiation, so this and MANIFEST.json's "modules" move together
# or the host refuses the mod.
#
# -DGBX_WITH_UI=0 and -DGBX_WITH_GAMESTATE_READ=0 turn OFF what the Lua host
# binds by default. This mod draws nothing and reads no world, and without
# these the module still imported gearbox:ui and gearbox:gamestate.read -- and
# was refused at load, naming turn_number, a function it never calls. The
# alternative is to declare both in the manifest, which is a mod asking a
# player for the world and the screen in order to add two doctrines. Ask for
# what you use.
emcc -O2 -sSTANDALONE_WASM --no-entry \
     -sSUPPORT_LONGJMP=0 \
     -sERROR_ON_UNDEFINED_SYMBOLS=0 \
     -sMALLOC=emmalloc \
     -sINITIAL_MEMORY=8MB \
     -sSTACK_SIZE=256KB \
     -sASSERTIONS=0 \
     -DNDEBUG \
     -DGBX_WITH_CONTENT=1 \
     -DGBX_WITH_UI=0 \
     -DGBX_WITH_GAMESTATE_READ=0 \
     -ffunction-sections -fdata-sections -Wl,--gc-sections \
     -I "$sdk" -I "$luadir" -I "$src" -I "$here" \
     -include "$luadir/gbx_throw.h" \
     -o "$here/mod.wasm" \
     $srcs "$obj" "$luadir/gearbox_lua.c"

python3 "$root/tools/wasm_imports.py" "$here/mod.wasm"
"$root/tools/pack_odmod.sh" "$here" "$here/custom-doctrine-lua.odmod"

if [ -x "$root/build/odmod-check" ]; then
    "$root/build/odmod-check" "$here/custom-doctrine-lua.odmod"
fi
