#pragma once

// Sealing a player's orders so a turn store cannot read or forge them.
//
// WHY THIS EXISTS
//
// Every long-form store is a dumb bucket reached by a URL, and on some of them
// (jsonblob) anyone holding that URL can OVERWRITE what is there. So the store
// is never trusted with confidentiality or authenticity. Orders are sealed
// before they leave the player's machine and opened only by the host.
//
// WHAT THAT BUYS, PRECISELY
//
//   - Nobody can READ another player's orders before the turn resolves --
//     including the host, until it opens them, and including whoever runs the
//     store. Orders that leaked early would let someone counter them, which in
//     a game of simultaneous turns is the whole ballgame.
//   - Nobody can FORGE orders. Tampering is detected, and a submission that
//     fails to open is treated as NO SUBMISSION -- a case the turn logic
//     already handles, and announces.
//
// What it deliberately does NOT buy: availability. Someone who can overwrite a
// blob can destroy a turn. They cannot turn it into a different turn, which is
// the difference between an outage and a rigged game.
//
// THE KEY
//
// One key per session, generated by the host and handed to each player over the
// authenticated WebSocket in the lobby -- never through the store. A store that
// carried the key would be a store that could read everything in it.
//
// AES-256-GCM, from mbedTLS, which is already linked for TLS. The nonce is
// random per seal and carried with the ciphertext; the turn number and the
// player's pseudonym are bound in as associated data, so a sealed blob cannot
// be replayed as a different player's orders or as a different turn.

#include <cstdint>
#include <string>
#include <vector>

/** A session's order key. 32 bytes; see the header note on distribution. */
struct TurnSealKey {
    uint8_t bytes[32]{};

    bool valid() const;

    /** Base64url, for handing to players over the lobby connection. */
    std::string toText() const;
    static bool fromText(const std::string& text, TurnSealKey& out);
};

/** A fresh random key. False when the system RNG could not be read. */
bool turnSealKeyGenerate(TurnSealKey& out);

/**
 * Seal `plaintext` for one turn and one player.
 *
 * `turnNumber` and `psid` are bound in as associated data rather than
 * encrypted: they are not secret, and binding them is what stops a sealed blob
 * being replayed as another turn or attributed to somebody else.
 */
bool turnSeal(const TurnSealKey& key, uint32_t turnNumber, const std::string& psid,
              const std::vector<uint8_t>& plaintext, std::vector<uint8_t>& out);

/**
 * Open a sealed submission.
 *
 * False for every failure -- wrong key, tampering, truncation, the wrong turn,
 * the wrong player. Callers must treat false as NO SUBMISSION and must not
 * distinguish the causes to anyone: which check failed is not a player's
 * business and telling them is an oracle.
 */
bool turnOpen(const TurnSealKey& key, uint32_t turnNumber, const std::string& psid,
              const std::vector<uint8_t>& sealed, std::vector<uint8_t>& out);

/** True when this build can seal at all (false without networking/mbedTLS). */
bool turnSealAvailable();
