#!/usr/bin/env bash
# Builds custom-doctrine.odmod. Needs a clang that can target wasm32.
#
# The doctrines themselves are in doctrines.json, in the game's own policy
# format. This turns that file into doctrines.h -- one (id, json) pair per
# entry -- so the mod's content stays editable, diffable JSON instead of string
# literals escaped by hand into C, and so the array is split by a parser that
# already exists rather than by one written in freestanding C.
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../../.." && pwd)"

# --- doctrines.json -> doctrines.h -------------------------------------------
python3 - "$here/doctrines.json" "$here/doctrines.h" <<'PY'
import json, pathlib, sys

src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
entries = json.loads(src.read_text())
if not isinstance(entries, list) or not entries:
    sys.exit("%s must be a non-empty array of doctrines" % src.name)


def c_string(b: bytes) -> str:
    """Bytes as a C string literal. Escaped rather than emitted as a char
    array so the generated header stays readable when a definition is wrong,
    which is when anybody opens it."""
    out = []
    for ch in b:
        if ch == 0x22:      out.append('\\"')
        elif ch == 0x5C:    out.append("\\\\")
        elif ch == 0x0A:    out.append("\\n")
        elif 0x20 <= ch < 0x7F:
            out.append(chr(ch))
        else:
            # \xNN would swallow a following hex digit; octal cannot.
            out.append("\\%03o" % ch)
    return '"' + "".join(out) + '"'


rows = []
for e in entries:
    ident = e.get("id", "")
    if not ident:
        sys.exit("every doctrine needs an id")
    # Minified: the definition crosses the ABI as bytes, and the whitespace
    # that makes doctrines.json readable is dead weight in the module.
    blob = json.dumps(e, separators=(",", ":")).encode()
    idb = ident.encode()
    rows.append("    { %s, %d,\n      %s, %d },"
                % (c_string(idb), len(idb), c_string(blob), len(blob)))

dst.write_text(
    "/* Generated by build.sh from %s. Do not edit. */\n"
    "#ifndef GBX_DOCTRINES_H\n#define GBX_DOCTRINES_H\n\n"
    "typedef struct {\n"
    "    const char* id;\n"
    "    unsigned    id_len;\n"
    "    const char* json;\n"
    "    unsigned    json_len;\n"
    "} gbx_doctrine;\n\n"
    "static const gbx_doctrine gbx_doctrines[] = {\n%s\n};\n"
    "static const unsigned gbx_doctrine_count = %d;\n\n"
    "#endif\n" % (src.name, "\n".join(rows), len(entries))
)
print("  embedded %d doctrine(s): %s"
      % (len(entries), ", ".join(e["id"] for e in entries)))
PY

# --- compile ------------------------------------------------------------------
CC="${CC:-}"
if [ -z "$CC" ]; then
    for c in "$(command -v clang || true)" \
             /opt/homebrew/Cellar/emscripten/*/libexec/llvm/bin/clang \
             /usr/local/Cellar/emscripten/*/libexec/llvm/bin/clang \
             /opt/homebrew/opt/llvm/bin/clang; do
        [ -x "$c" ] || continue
        if "$c" --print-targets 2>/dev/null | grep -qi wasm32; then CC="$c"; break; fi
    done
fi
[ -n "$CC" ] || { echo "no wasm32-capable clang found (set CC=)"; exit 1; }

"$CC" --target=wasm32 -nostdlib -O2 -I "$root/sdk" -I "$here" \
      -Wl,--no-entry -Wl,--allow-undefined \
      -o "$here/mod.wasm" "$here/mod.c"

python3 "$root/tools/wasm_imports.py" "$here/mod.wasm"
"$root/tools/pack_odmod.sh" "$here" "$here/custom-doctrine.odmod"

# The same checks the game runs at load time, if the tool has been built.
if [ -x "$root/build/odmod-check" ]; then
    "$root/build/odmod-check" "$here/custom-doctrine.odmod"
fi
