#!/usr/bin/env bash
# Shared build for every JS/TS mod: embeds a script into QuickJS and packs the
# .odmod. Both examples call this; a mod of your own can too.
#
#   sdk/js/build_mod.sh <mod-dir> <script.js> <output-name.odmod>
#
# <mod-dir> must contain MANIFEST.json. The script must already be JavaScript --
# TypeScript is compiled by the caller (see examples/hello-panel-ts/build.sh),
# because QuickJS only speaks JS and doing the tsc step here would hide that.
#
# Needs emcc, for the same reason the Lua SDK does: QuickJS wants a libc, and
# Emscripten's standalone-wasm sysroot provides one while importing nothing but
# wasi_snapshot_preview1.
set -eu

[ $# -eq 3 ] || { echo "usage: build_mod.sh <mod-dir> <script.js> <out.odmod>" >&2; exit 2; }
moddir="$(cd "$1" && pwd)"
script="$2"
outname="$3"

jsdir="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$jsdir/../.." && pwd)"
sdk="$root/sdk"

QJS_VER=2025-04-26
src="$jsdir/.quickjs-src/quickjs-$QJS_VER"

command -v emcc >/dev/null 2>&1 || {
    echo "emcc not found. Install Emscripten: https://emscripten.org/docs/getting_started/downloads.html" >&2
    exit 1
}
[ -f "$moddir/MANIFEST.json" ] || { echo "no MANIFEST.json in $moddir" >&2; exit 1; }
[ -f "$script" ] || { echo "no such script: $script" >&2; exit 1; }

# --- QuickJS source, fetched once and cached ---------------------------------
if [ ! -d "$src" ]; then
    echo "fetching quickjs-$QJS_VER..."
    mkdir -p "$jsdir/.quickjs-src"
    curl -fsSL "https://bellard.org/quickjs/quickjs-$QJS_VER.tar.xz" \
        | tar xJ -C "$jsdir/.quickjs-src"
fi

# --- script -> script.h ------------------------------------------------------
# There is no filesystem in the sandbox, so the script travels as bytes in the
# module's data section.
python3 - "$script" "$moddir/script.h" <<'PY'
import sys, pathlib
src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
data = src.read_bytes()
# The trailing NUL is load-bearing: JS_Eval requires a zero-terminated buffer,
# unlike Lua's luaL_loadbuffer. Without it QuickJS reads past the array into
# whatever the linker put next and fails with a baffling ReferenceError for an
# identifier that appears nowhere in the script. gbx_script_len stays the real
# length, so the terminator is never evaluated.
blob = data + b"\x00"
rows = [", ".join(f"0x{b:02x}" for b in blob[i:i+16]) for i in range(0, len(blob), 16)]
dst.write_text(
    "/* Generated by build_mod.sh from %s. Do not edit. */\n"
    "#ifndef GBX_SCRIPT_H\n#define GBX_SCRIPT_H\n\n"
    "/* NUL-terminated; gbx_script_len excludes the terminator. */\n"
    "static const unsigned char gbx_script[] = {\n    %s\n};\n"
    "static const unsigned int gbx_script_len = %d;\n"
    "static const char gbx_script_name[] = \"%s\";\n\n"
    "#endif\n" % (src.name, ",\n    ".join(rows), len(data), src.name)
)
print(f"  embedded {src.name} ({len(data)} bytes)")
PY

# --- QuickJS core ------------------------------------------------------------
# -DEMSCRIPTEN=1 is not redundant. QuickJS picks its malloc_usable_size
# implementation from the platform and has an Emscripten branch that correctly
# returns 0 -- but it tests `EMSCRIPTEN`, which current emcc no longer defines
# (it defines `__EMSCRIPTEN__`). Without this the build falls through to the
# glibc branch and fails on an undeclared malloc_usable_size. Defining it picks
# QuickJS's own answer rather than patching its source.
#
# quickjs-libc.c is deliberately NOT compiled. It is the half of QuickJS that
# reaches for a filesystem, a clock and a process -- std.open, os.exec and
# friends -- and leaving it out is what keeps this module's WASI surface down
# to the same handful the Lua SDK needs. console.log is provided by
# gearbox_qjs.c instead.
core="quickjs libregexp libunicode cutils dtoa"
srcs=""
for f in $core; do srcs="$srcs $src/$f.c"; done

emcc -O2 -sSTANDALONE_WASM --no-entry \
     -sSUPPORT_LONGJMP=0 \
     -sERROR_ON_UNDEFINED_SYMBOLS=0 \
     -sMALLOC=emmalloc \
     -sINITIAL_MEMORY=16MB \
     -sSTACK_SIZE=1MB \
     -sASSERTIONS=0 \
     -DNDEBUG -D_GNU_SOURCE \
     -DCONFIG_VERSION="\"$QJS_VER\"" \
     -DEMSCRIPTEN=1 \
     -ffunction-sections -fdata-sections -Wl,--gc-sections \
     -I "$sdk" -I "$jsdir" -I "$src" -I "$moddir" \
     -o "$moddir/mod.wasm" \
     $srcs "$jsdir/gearbox_qjs.c"

python3 "$root/tools/wasm_imports.py" "$moddir/mod.wasm"
"$root/tools/pack_odmod.sh" "$moddir" "$moddir/$outname"

ls -l "$moddir/mod.wasm" "$moddir/$outname" \
    | awk '{printf "  %-12s %8d bytes\n", $NF, $5}'
