#!/usr/bin/env python3
"""Turn CPython's stdlib zip into a C array of frozen modules.

    gen_frozen.py python312.zip frozen_stdlib.h [--only mod,mod,...]

WHY THIS EXISTS

A Gearbox mod has no filesystem: every WASI path call is refused by the host,
deliberately and permanently. CPython normally reads its standard library off
disk, and `Py_InitializeFromConfig` fails outright without `encodings` -- so a
Python mod cannot start at all unless the library travels inside the module.

CPython has a supported mechanism for exactly this. `PyImport_FrozenModules` is
documented as "embedding apps may change this pointer to point to their favorite
collection of frozen modules", and the import machinery checks it before it ever
touches a path. This script builds that collection.

The zip ships .pyc files, already compiled for the matching CPython. A .pyc is a
16-byte header followed by a marshalled code object, and the frozen table wants
exactly that marshalled tail -- so no compiler is involved here and no host
Python of the right version is needed. That matters: the host python3 is 3.14
and its marshal format would not load in 3.12.
"""

import sys
import zipfile

PYC_HEADER = 16  # magic (4) + flags (4) + mtime (4) + source size (4)


def module_name(entry):
    """encodings/__init__.pyc -> ('encodings', True); os.pyc -> ('os', False)"""
    assert entry.endswith(".pyc")
    parts = entry[:-4].split("/")
    if parts[-1] == "__init__":
        return ".".join(parts[:-1]), True
    return ".".join(parts), False


def main():
    if len(sys.argv) < 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    zip_path, out_path = sys.argv[1], sys.argv[2]

    only = None
    if "--only" in sys.argv:
        only = set(sys.argv[sys.argv.index("--only") + 1].split(","))

    mods = []
    with zipfile.ZipFile(zip_path) as z:
        for entry in sorted(z.namelist()):
            if not entry.endswith(".pyc"):
                continue
            name, is_pkg = module_name(entry)
            if not name:
                continue
            if only is not None and name.split(".")[0] not in only:
                continue
            blob = z.read(entry)[PYC_HEADER:]
            mods.append((name, is_pkg, blob))

    if not mods:
        print(f"gen_frozen: no modules selected from {zip_path}", file=sys.stderr)
        return 1

    out = [
        "/* Generated by sdk/python/tools/gen_frozen.py. Do not edit.\n"
        " *\n"
        " * CPython's standard library, marshalled, as frozen modules. See that\n"
        " * script for why a Python mod cannot use the filesystem copy.\n"
        " */\n"
        "#ifndef GBX_FROZEN_STDLIB_H\n#define GBX_FROZEN_STDLIB_H\n"
    ]

    total = 0
    for i, (name, _pkg, blob) in enumerate(mods):
        total += len(blob)
        rows = ",\n    ".join(
            ", ".join(f"0x{b:02x}" for b in blob[j:j + 16])
            for j in range(0, len(blob), 16)
        )
        out.append(f"\n/* {name} */\nstatic const unsigned char gbx_frz_{i}[] = {{\n    {rows}\n}};\n")

    out.append("\nstatic const struct _frozen gbx_frozen_stdlib[] = {\n")
    for i, (name, pkg, blob) in enumerate(mods):
        out.append(f'    {{"{name}", gbx_frz_{i}, {len(blob)}, {1 if pkg else 0}, NULL}},\n')
    # The terminating {NULL,...} entry is required: CPython scans until it sees
    # a null name.
    out.append("    {NULL, NULL, 0, 0, NULL}\n};\n\n#endif\n")

    with open(out_path, "w") as f:
        f.write("".join(out))

    print(f"  froze {len(mods)} modules, {total // 1024} KiB of marshalled code")
    return 0


if __name__ == "__main__":
    sys.exit(main())
