// GENERATED by tools/gen_bindings.py from sdk/abi.json. Do not edit.
//
// Raw imports only; the safe wrappers are in lib.rs.

#[link(wasm_import_module = "gearbox:core")]
extern "C" {
    /// Write a line to the game log and the mod menu's log view. Messages
    /// longer than 2048 bytes are truncated. An out-of-bounds (ptr,len) is
    /// refused and logged as an error against your mod rather than read.
    /// `(iii)`
    pub fn log(level: u32, msg: *const u8, msg_len: u32);

    /// Fill a gearbox_env_t. Write your own sizeof into out->size FIRST; the
    /// host writes at most that many bytes, so an older mod stays safe against
    /// a newer host. If size is 0 or larger than the host's struct, the host
    /// uses its own size.
    /// `(i)`
    pub fn env(out: *mut u8);

    /// Unrecoverable error. Traps out of the current call, disables the mod,
    /// and shows the message to the user. Prefer returning an error from a hook
    /// where you can.
    /// `(ii)`
    pub fn abort(msg: *const u8, msg_len: u32);

    /// The instruction budget for the current hook, or 0xFFFFFFFFFFFFFFFF when
    /// unmetered. This is the LIMIT, not a live countdown: it does not decrease
    /// as you run. Use it to size your work up front and count your own
    /// iterations.
    /// `()I`
    pub fn fuel_budget() -> u64;

}

#[link(wasm_import_module = "gearbox:gamestate.read")]
extern "C" {
    /// The current turn. 0 when no world is loaded.
    /// `()i`
    pub fn turn_number() -> u32;

    /// How many countries exist. 0 when no world is loaded. Rebel factions are
    /// not included.
    /// `()i`
    pub fn country_count() -> u32;

    /// The country at index in [0, country_count). Returns GEARBOX_INVALID
    /// (0xFFFFFFFF) if out of range. Ordering is stable within a turn but not
    /// across turns.
    /// `(i)i`
    pub fn country_at(index: u32) -> u32;

    /// Two-call sizing. Writes at most cap bytes of UTF-8 and returns the FULL
    /// length. Call with cap 0 to size, then again to fill. A return greater
    /// than cap means truncation, not failure. Returns 0 for an unknown
    /// country.
    /// `(iii)i`
    pub fn country_name(country: u32, buf: *mut u8, cap: u32) -> u32;

    /// Treasury balance. 0 for an unknown country.
    /// `(i)F`
    pub fn country_treasury(country: u32) -> f64;

    /// How many provinces the country owns. 0 for an unknown country.
    /// `(i)i`
    pub fn country_province_count(country: u32) -> u32;

    /// Population of a province. 0 for an unknown province.
    /// `(i)I`
    pub fn province_population(province: u32) -> i64;

    /// Owning country, or GEARBOX_INVALID if unowned or unknown.
    /// `(i)i`
    pub fn province_owner(province: u32) -> u32;

}

#[link(wasm_import_module = "gearbox:ui")]
extern "C" {
    /// Register a panel and return its handle. Returns 0 (invalid) when
    /// headless, when UI was revoked, or when you already hold 8 panels. Titles
    /// are truncated to 64 bytes. Call this from mod_load, not from your draw
    /// hook.
    /// `(iiii)i`
    pub fn panel_register(title: *const u8, title_len: u32, min_w: u32, min_h: u32) -> u32;

    /// Filled rectangle in panel-relative coordinates. Colour is 0xRRGGBBAA.
    /// Coordinates outside the panel are clipped by the host; they cannot
    /// escape it.
    /// `(iiiiii)`
    pub fn draw_rect(panel: u32, x: i32, y: i32, w: i32, h: i32, rgba: u32);

    /// UTF-8 text in panel-relative coordinates. Truncated to 512 bytes per
    /// call.
    /// `(iiiiii)`
    pub fn draw_text(panel: u32, x: i32, y: i32, rgba: u32, text: *const u8, text_len: u32);

    /// Immediate-mode button: draws it and returns 1 on the frame it is
    /// clicked. One click activates one button -- the host consumes it, so
    /// overlapping rects do not all fire. Label truncated to 64 bytes.
    /// `(iiiiiii)i`
    pub fn button(panel: u32, x: i32, y: i32, w: i32, h: i32, label: *const u8, label_len: u32) -> u32;

}

#[link(wasm_import_module = "gearbox:assets")]
extern "C" {
    /// Byte size of one of your own data/ files, or 0 if there is no such
    /// asset. Names are relative to data/ and use '/' separators:
    /// data/flags/fr.png is "flags/fr.png".
    /// `(ii)i`
    pub fn asset_size(name: *const u8, name_len: u32) -> u32;

    /// Two-call sizing, like country_name. Writes at most cap bytes and returns
    /// the asset's full size. The name is looked up in your package's entry
    /// list, never resolved as a filesystem path.
    /// `(iiii)i`
    pub fn asset_read(name: *const u8, name_len: u32, buf: *mut u8, cap: u32) -> u32;

}

#[link(wasm_import_module = "gearbox:storage")]
extern "C" {
    /// Reads one of your own keys. Two-call sizing: returns the full value
    /// length and writes at most cap bytes. Returns GEARBOX_INVALID if the key
    /// is absent -- which is NOT the same as a zero-length value, so you can
    /// tell 'never stored' from 'stored empty'. Values are arbitrary bytes, not
    /// text.
    /// `(iiii)i`
    pub fn get(key: *const u8, key_len: u32, buf: *mut u8, cap: u32) -> u32;

    /// Stores bytes under one of your own keys. Returns 1 on success, 0 if a
    /// quota was exceeded (256 keys, 128-byte keys, 16 KiB per value, 64 KiB
    /// total per mod) -- the reason is written to your log. Not written to disk
    /// immediately: the store is flushed at turn boundaries and on unload,
    /// because a mod may call this from a draw hook.
    /// `(iiii)i`
    pub fn set(key: *const u8, key_len: u32, value: *const u8, value_len: u32) -> u32;

    /// Deletes one of your own keys. Returns 1 if it existed, 0 if it did not.
    /// `(ii)i`
    pub fn remove(key: *const u8, key_len: u32) -> u32;

}

#[link(wasm_import_module = "gearbox:map")]
extern "C" {
    /// Width of the province map in pixels. 0 when no world is loaded.
    /// `()i`
    pub fn width() -> u32;

    /// Height of the province map in pixels. 0 when no world is loaded.
    /// `()i`
    pub fn height() -> u32;

    /// How many provinces the loaded map has. 0 when no world is loaded.
    /// `()i`
    pub fn province_count() -> u32;

    /// Province handle at an index in [0, province_count). Returns
    /// GEARBOX_INVALID if out of range. The order is stable across runs, unlike
    /// the game's internal storage, so an index is safe to remember within a
    /// session.
    /// `(i)i`
    pub fn province_at(index: u32) -> u32;

    /// The province's name. Two-call sizing: returns the full length and writes
    /// at most cap bytes. Empty for an unknown province.
    /// `(iii)i`
    pub fn province_name(province: u32, buf: *mut u8, cap: u32) -> u32;

    /// X pixel coordinate of the province's centre. 0 for an unknown province.
    /// `(i)F`
    pub fn province_center_x(province: u32) -> f64;

    /// Y pixel coordinate of the province's centre. 0 for an unknown province.
    /// `(i)F`
    pub fn province_center_y(province: u32) -> f64;

    /// 1 if the province is land, 0 if it is sea or unknown. Sampled at the
    /// province centre.
    /// `(i)i`
    pub fn province_is_land(province: u32) -> u32;

    /// How many provinces border this one. 0 for an unknown province.
    /// `(i)i`
    pub fn province_neighbor_count(province: u32) -> u32;

    /// The bordering province at an index in [0, province_neighbor_count).
    /// GEARBOX_INVALID if out of range. Adjacency is computed once when the map
    /// loads, so walking it is cheap.
    /// `(ii)i`
    pub fn province_neighbor_at(province: u32, index: u32) -> u32;

}

#[link(wasm_import_module = "gearbox:diplomacy")]
extern "C" {
    /// 1 if the two countries are at war. Relations are symmetric, so the
    /// argument order does not matter. 0 for unknown countries or for a country
    /// with itself.
    /// `(ii)i`
    pub fn at_war(a: u32, b: u32) -> u32;

    /// 1 if the two countries are allied.
    /// `(ii)i`
    pub fn allied(a: u32, b: u32) -> u32;

    /// 1 if the two countries have a non-aggression pact.
    /// `(ii)i`
    pub fn non_aggression(a: u32, b: u32) -> u32;

    /// 1 if the first country guarantees the second.
    /// `(ii)i`
    pub fn guaranteed(a: u32, b: u32) -> u32;

    /// PROPOSES a declaration of war, and returns 1 only if the game accepted
    /// it. It is routed through the same code path any other actor uses, so
    /// guarantee chains and war consequences follow exactly as normal -- a mod
    /// cannot produce a diplomatic state the game itself could not reach.
    /// Refused (0) if either country is unknown, they are the same country, or
    /// they are already at war. Either outcome is written to your mod log, so a
    /// player can see after the fact that a mod started a war.
    /// `(ii)i`
    pub fn propose_war(attacker: u32, defender: u32) -> u32;

}

#[link(wasm_import_module = "gearbox:gamestate.write")]
extern "C" {
    /// Sets a country's treasury outright. Returns 1 on success, 0 if the
    /// country is unknown or the value is not finite and within +/-1e12 -- NaN
    /// or infinity would silently poison every later calculation, so they are
    /// refused rather than stored.
    /// `(iF)i`
    pub fn set_country_treasury(country: u32, value: f64) -> u32;

    /// Adds to a country's treasury. Usually what you want instead of set: it
    /// composes with whatever the economy did this turn. Refused (0) if the
    /// result would leave the sane range.
    /// `(iF)i`
    pub fn add_country_treasury(country: u32, delta: f64) -> u32;

    /// Transfers a province to another country. Routed through the same code
    /// the game's own ceasefires use, so the province, the ownership lookup,
    /// the per-pixel country map and both countries' pixel lists all stay
    /// consistent -- and the previous owner's troops in that province are
    /// disbanded, as they are for any other transfer. Returns 0 if either
    /// handle is unknown or the country already owns it. Always written to your
    /// mod log: territory changing hands is the most consequential thing a mod
    /// can do.
    /// `(ii)i`
    pub fn set_province_owner(province: u32, country: u32) -> u32;

    /// Sets a province's population. Returns 0 if the province is unknown, the
    /// value is negative, or it exceeds 100 billion. The game stores population
    /// in two places -- a map and a dense array used by the population texture
    /// -- and this updates both, which is why it exists as an import rather
    /// than being something a mod could do by other means.
    /// `(iI)i`
    pub fn set_province_population(province: u32, value: i64) -> u32;

}

#[link(wasm_import_module = "gearbox:neural")]
extern "C" {
    /// How many floats are in the AI's feature vector. 0 when there is no AI or
    /// no world.
    /// `()i`
    pub fn feature_count() -> u32;

    /// Copies the feature vector the AI would see for a country, as 32-bit
    /// floats. Two-call sizing, but note cap counts FLOATS and the buffer must
    /// therefore be cap*4 bytes. This is a snapshot: writing to your copy does
    /// not affect the AI.
    /// `(iii)i`
    pub fn features(country: u32, buf: *mut u8, cap: u32) -> u32;

    /// How many reward channels the AI tracks (economy, politics, war, navy).
    /// `()i`
    pub fn reward_count() -> u32;

    /// The running mean reward for one channel, indexed in [0, reward_count). 0
    /// if out of range. OBSERVE ONLY: this capability has no import that writes
    /// to the model, the optimiser state or the reward history, which is
    /// deliberate -- a trained model is hours of work and a mod that could
    /// quietly retrain it is not something a user can meaningfully consent to.
    /// `(i)F`
    pub fn reward_mean(index: u32) -> f64;

}
