/* GENERATED by tools/gen_bindings.py from sdk/abi.json. Do not edit.
 *
 * Included by gearbox.h, which carries the prose. Everything here is
 * mechanical: constants, the env struct layout, and the declarations.
 */

#ifndef GEARBOX_GENERATED_H
#define GEARBOX_GENERATED_H

/* ------------------------------------------------- constants -- */
#define GEARBOX_INVALID 0xFFFFFFFFu
#define GEARBOX_MAJOR 1
#define GEARBOX_MINOR 3

typedef enum {
    GEARBOX_LOG_TRACE  = 0,
    GEARBOX_LOG_INFO   = 1,
    GEARBOX_LOG_WARN   = 2,
    GEARBOX_LOG_ERROR  = 3
} gearbox_log_level;

/* Layout is ABI. Fields are only ever appended, never reordered or resized. Total size is 28 bytes on wasm32. */
typedef struct {
    uint32_t  size;   /* You write sizeof(gearbox_env_t) here before calling env */
    uint32_t  gearbox_major;
    uint32_t  gearbox_minor;
    uint32_t  host_version;   /* (major<<16)|(minor<<8)|patch */
    uint8_t   platform;   /* enum:platform */
    uint8_t   is_web;   /* 1 under Emscripten. Fuel is NOT enforced there. */
    uint8_t   is_headless;   /* 1 when there is no renderer. UI imports no-op. */
    uint8_t   net_role;   /* enum:net_role. 0 in singleplayer, which is what an older mod reading this byte as reserved already saw. */
    uint32_t  screen_w;   /* 0 when headless */
    uint32_t  screen_h;   /* 0 when headless */
} gearbox_env_t;
_Static_assert(sizeof(gearbox_env_t) == 28,
               "gearbox_env_t layout is ABI");

/* --------------------------------------------------- imports -- */

/* Write a line to the game log and the mod menu's log view. Messages
 * longer than 2048 bytes are truncated. An out-of-bounds (ptr,len) is
 * refused and logged as an error against your mod rather than read.
 * gearbox:core "log"
 * `(iii)`
 */
GEARBOX_IMPORT("core", "log")
void gearbox_log(gearbox_log_level level, const char* msg, uint32_t msg_len);

/* Fill a gearbox_env_t. Write your own sizeof into out->size FIRST; the
 * host writes at most that many bytes, so an older mod stays safe against
 * a newer host. If size is 0 or larger than the host's struct, the host
 * uses its own size.
 * gearbox:core "env"
 * `(i)`
 */
GEARBOX_IMPORT("core", "env")
void gearbox_env(gearbox_env_t* out);

/* Unrecoverable error. Traps out of the current call, disables the mod,
 * and shows the message to the user. Prefer returning an error from a hook
 * where you can.
 * gearbox:core "abort"
 * `(ii)`
 */
GEARBOX_IMPORT("core", "abort")
void gearbox_abort(const char* msg, uint32_t msg_len) __attribute__((noreturn));

/* The instruction budget for the current hook, or 0xFFFFFFFFFFFFFFFF when
 * unmetered. This is the LIMIT, not a live countdown: it does not decrease
 * as you run. Use it to size your work up front and count your own
 * iterations.
 * gearbox:core "fuel_budget"
 * `()I`
 */
GEARBOX_IMPORT("core", "fuel_budget")
uint64_t gearbox_fuel_budget(void);

/* The current turn. 0 when no world is loaded.
 * gearbox:gamestate.read "turn_number"
 * `()i`
 */
GEARBOX_IMPORT("gamestate.read", "turn_number")
uint32_t gearbox_turn_number(void);

/* How many countries exist. 0 when no world is loaded. Rebel factions are
 * not included.
 * gearbox:gamestate.read "country_count"
 * `()i`
 */
GEARBOX_IMPORT("gamestate.read", "country_count")
uint32_t gearbox_country_count(void);

/* The country at index in [0, country_count). Returns GEARBOX_INVALID
 * (0xFFFFFFFF) if out of range. Ordering is stable within a turn but not
 * across turns.
 * gearbox:gamestate.read "country_at"
 * `(i)i`
 */
GEARBOX_IMPORT("gamestate.read", "country_at")
gearbox_country gearbox_country_at(uint32_t index);

/* Two-call sizing. Writes at most cap bytes of UTF-8 and returns the FULL
 * length. Call with cap 0 to size, then again to fill. A return greater
 * than cap means truncation, not failure. Returns 0 for an unknown
 * country.
 * gearbox:gamestate.read "country_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("gamestate.read", "country_name")
uint32_t gearbox_country_name(gearbox_country country, char* buf, uint32_t cap);

/* Treasury balance. 0 for an unknown country.
 * gearbox:gamestate.read "country_treasury"
 * `(i)F`
 */
GEARBOX_IMPORT("gamestate.read", "country_treasury")
double gearbox_country_treasury(gearbox_country country);

/* How many provinces the country owns. 0 for an unknown country.
 * gearbox:gamestate.read "country_province_count"
 * `(i)i`
 */
GEARBOX_IMPORT("gamestate.read", "country_province_count")
uint32_t gearbox_country_province_count(gearbox_country country);

/* Population of a province. 0 for an unknown province.
 * gearbox:gamestate.read "province_population"
 * `(i)I`
 */
GEARBOX_IMPORT("gamestate.read", "province_population")
int64_t gearbox_province_population(gearbox_province province);

/* Owning country, or GEARBOX_INVALID if unowned or unknown.
 * gearbox:gamestate.read "province_owner"
 * `(i)i`
 */
GEARBOX_IMPORT("gamestate.read", "province_owner")
gearbox_country gearbox_province_owner(gearbox_province province);

/* Register a panel and return its handle. Returns 0 (invalid) when
 * headless, when UI was revoked, or when you already hold 8 panels. Titles
 * are truncated to 64 bytes. Call this from mod_load, not from your draw
 * hook.
 * gearbox:ui "panel_register"
 * `(iiii)i`
 */
GEARBOX_IMPORT("ui", "panel_register")
gearbox_panel gearbox_panel_register(const char* title, uint32_t title_len, uint32_t min_w, uint32_t min_h);

/* Filled rectangle in panel-relative coordinates. Colour is 0xRRGGBBAA.
 * Coordinates outside the panel are clipped by the host; they cannot
 * escape it.
 * gearbox:ui "draw_rect"
 * `(iiiiii)`
 */
GEARBOX_IMPORT("ui", "draw_rect")
void gearbox_draw_rect(gearbox_panel panel, int32_t x, int32_t y, int32_t w, int32_t h, uint32_t rgba);

/* UTF-8 text in panel-relative coordinates. Truncated to 512 bytes per
 * call.
 * gearbox:ui "draw_text"
 * `(iiiiii)`
 */
GEARBOX_IMPORT("ui", "draw_text")
void gearbox_draw_text(gearbox_panel panel, int32_t x, int32_t y, uint32_t rgba, const char* text, uint32_t text_len);

/* Immediate-mode button: draws it and returns 1 on the frame it is
 * clicked. One click activates one button -- the host consumes it, so
 * overlapping rects do not all fire. Label truncated to 64 bytes.
 * gearbox:ui "button"
 * `(iiiiiii)i`
 */
GEARBOX_IMPORT("ui", "button")
uint32_t gearbox_button(gearbox_panel panel, int32_t x, int32_t y, int32_t w, int32_t h, const char* label, uint32_t label_len);

/* Byte size of one of your own data/ files, or 0 if there is no such
 * asset. Names are relative to data/ and use '/' separators:
 * data/flags/fr.png is "flags/fr.png".
 * gearbox:assets "size"
 * `(ii)i`
 */
GEARBOX_IMPORT("assets", "size")
uint32_t gearbox_asset_size(const char* name, uint32_t name_len);

/* Two-call sizing, like country_name. Writes at most cap bytes and returns
 * the asset's full size. The name is looked up in your package's entry
 * list, never resolved as a filesystem path.
 * gearbox:assets "read"
 * `(iiii)i`
 */
GEARBOX_IMPORT("assets", "read")
uint32_t gearbox_asset_read(const char* name, uint32_t name_len, void* buf, uint32_t cap);

/* Play a sound from your own mod's assets. `path` is relative to your mod
 * root; a path outside it is refused rather than resolved. Volume is 0..1
 * and is multiplied by the player's own effects setting, so a mod cannot
 * be louder than they allowed. Returns a handle, or 0 if it could not be
 * played.
 * gearbox:audio "play"
 * `(iif)i`
 */
GEARBOX_IMPORT("audio", "play")
uint32_t gearbox_play(const char* path, uint32_t path_len, float volume);

/* Stop a sound this mod started. A handle belonging to another mod, or one
 * that already finished, does nothing.
 * gearbox:audio "stop"
 * `(i)`
 */
GEARBOX_IMPORT("audio", "stop")
void gearbox_stop(uint32_t handle);

/* Change the volume of a playing sound, 0..1, again scaled by the player's
 * setting.
 * gearbox:audio "set_volume"
 * `(if)`
 */
GEARBOX_IMPORT("audio", "set_volume")
void gearbox_set_volume(uint32_t handle, float volume);

/* Whether that handle is still making sound.
 * gearbox:audio "is_playing"
 * `(i)i`
 */
GEARBOX_IMPORT("audio", "is_playing")
uint32_t gearbox_is_playing(uint32_t handle);

/* Send a message to the same mod running on another peer. `peer` is a peer
 * id -- the value `recv` reported in `from_peer` -- and -1 broadcasts to
 * every other peer, the host included. There is no fixed id for the host:
 * a host that plays holds an ordinary seat, and a dedicated one holds
 * none. The host stamps your mod id on the message, so you cannot send as
 * another mod, and it never carries game traffic: orders, deltas and chat
 * do not travel here. Messages larger than 8192 bytes are refused. Returns
 * 0 if this is not a network game, or the message was too large.
 * gearbox:net "send"
 * `(iii)i`
 */
GEARBOX_IMPORT("net", "send")
uint32_t gearbox_send(uint32_t peer, const char* data, uint32_t data_len);

/* Take the next message addressed to this mod, writing it into `out` and
 * the sender's peer id into `from_peer`. Returns the number of bytes
 * written, or 0 when the queue is empty. A message longer than `out_len`
 * is truncated rather than dropped, so a small buffer loses data instead
 * of stalling the queue.
 * gearbox:net "recv"
 * `(iii)i`
 */
GEARBOX_IMPORT("net", "recv")
uint32_t gearbox_recv(char* out, uint32_t out_len, char* from_peer);

/* How many players this session has, a playing host included. 0 when this
 * is not a network game, which is how a mod tells the difference.
 * Spectators are not counted.
 * gearbox:net "peer_count"
 * `()i`
 */
GEARBOX_IMPORT("net", "peer_count")
uint32_t gearbox_peer_count(void);

/* This machine's own peer id. 0 means this is not a network game, or this
 * is a dedicated host holding no seat -- a host that plays has an ordinary
 * peer id like anyone else, so do not use this to tell host from client.
 * `is_host` is that question.
 * gearbox:net "self_peer"
 * `()i`
 */
GEARBOX_IMPORT("net", "self_peer")
uint32_t gearbox_self_peer(void);

/* Whether this copy is the authoritative one. A mod that computes anything
 * the game depends on must do it here and send the result, not compute it
 * separately on each machine.
 * gearbox:net "is_host"
 * `()i`
 */
GEARBOX_IMPORT("net", "is_host")
uint32_t gearbox_is_host(void);

/* Reads one of your own keys. Two-call sizing: returns the full value
 * length and writes at most cap bytes. Returns GEARBOX_INVALID if the key
 * is absent -- which is NOT the same as a zero-length value, so you can
 * tell 'never stored' from 'stored empty'. Values are arbitrary bytes, not
 * text.
 * gearbox:storage "get"
 * `(iiii)i`
 */
GEARBOX_IMPORT("storage", "get")
uint32_t gearbox_get(const char* key, uint32_t key_len, char* buf, uint32_t cap);

/* Stores bytes under one of your own keys. Returns 1 on success, 0 if a
 * quota was exceeded (256 keys, 128-byte keys, 16 KiB per value, 64 KiB
 * total per mod) -- the reason is written to your log. Not written to disk
 * immediately: the store is flushed at turn boundaries and on unload,
 * because a mod may call this from a draw hook.
 * gearbox:storage "set"
 * `(iiii)i`
 */
GEARBOX_IMPORT("storage", "set")
uint32_t gearbox_set(const char* key, uint32_t key_len, const char* value, uint32_t value_len);

/* Deletes one of your own keys. Returns 1 if it existed, 0 if it did not.
 * gearbox:storage "remove"
 * `(ii)i`
 */
GEARBOX_IMPORT("storage", "remove")
uint32_t gearbox_remove(const char* key, uint32_t key_len);

/* Width of the province map in pixels. 0 when no world is loaded.
 * gearbox:map "width"
 * `()i`
 */
GEARBOX_IMPORT("map", "width")
uint32_t gearbox_width(void);

/* Height of the province map in pixels. 0 when no world is loaded.
 * gearbox:map "height"
 * `()i`
 */
GEARBOX_IMPORT("map", "height")
uint32_t gearbox_height(void);

/* How many provinces the loaded map has. 0 when no world is loaded.
 * gearbox:map "province_count"
 * `()i`
 */
GEARBOX_IMPORT("map", "province_count")
uint32_t gearbox_province_count(void);

/* Province handle at an index in [0, province_count). Returns
 * GEARBOX_INVALID if out of range. The order is stable across runs, unlike
 * the game's internal storage, so an index is safe to remember within a
 * session.
 * gearbox:map "province_at"
 * `(i)i`
 */
GEARBOX_IMPORT("map", "province_at")
gearbox_province gearbox_province_at(uint32_t index);

/* The province's name. Two-call sizing: returns the full length and writes
 * at most cap bytes. Empty for an unknown province.
 * gearbox:map "province_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("map", "province_name")
uint32_t gearbox_province_name(gearbox_province province, char* buf, uint32_t cap);

/* X pixel coordinate of the province's centre. 0 for an unknown province.
 * gearbox:map "province_center_x"
 * `(i)F`
 */
GEARBOX_IMPORT("map", "province_center_x")
double gearbox_province_center_x(gearbox_province province);

/* Y pixel coordinate of the province's centre. 0 for an unknown province.
 * gearbox:map "province_center_y"
 * `(i)F`
 */
GEARBOX_IMPORT("map", "province_center_y")
double gearbox_province_center_y(gearbox_province province);

/* 1 if the province is land, 0 if it is sea or unknown. Sampled at the
 * province centre.
 * gearbox:map "province_is_land"
 * `(i)i`
 */
GEARBOX_IMPORT("map", "province_is_land")
uint32_t gearbox_province_is_land(gearbox_province province);

/* How many provinces border this one. 0 for an unknown province.
 * gearbox:map "province_neighbor_count"
 * `(i)i`
 */
GEARBOX_IMPORT("map", "province_neighbor_count")
uint32_t gearbox_province_neighbor_count(gearbox_province province);

/* The bordering province at an index in [0, province_neighbor_count).
 * GEARBOX_INVALID if out of range. Adjacency is computed once when the map
 * loads, so walking it is cheap.
 * gearbox:map "province_neighbor_at"
 * `(ii)i`
 */
GEARBOX_IMPORT("map", "province_neighbor_at")
gearbox_province gearbox_province_neighbor_at(gearbox_province province, uint32_t index);

/* 1 if the two countries are at war. Relations are symmetric, so the
 * argument order does not matter. 0 for unknown countries or for a country
 * with itself.
 * gearbox:diplomacy "at_war"
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "at_war")
uint32_t gearbox_at_war(gearbox_country a, gearbox_country b);

/* 1 if the two countries are allied.
 * gearbox:diplomacy "allied"
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "allied")
uint32_t gearbox_allied(gearbox_country a, gearbox_country b);

/* 1 if the two countries have a non-aggression pact.
 * gearbox:diplomacy "non_aggression"
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "non_aggression")
uint32_t gearbox_non_aggression(gearbox_country a, gearbox_country b);

/* 1 if the first country guarantees the second.
 * gearbox:diplomacy "guaranteed"
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "guaranteed")
uint32_t gearbox_guaranteed(gearbox_country a, gearbox_country b);

/* PROPOSES a declaration of war, and returns 1 only if the game accepted
 * it. It is routed through the same code path any other actor uses, so
 * guarantee chains and war consequences follow exactly as normal -- a mod
 * cannot produce a diplomatic state the game itself could not reach.
 * Refused (0) if either country is unknown, they are the same country, or
 * they are already at war. Either outcome is written to your mod log, so a
 * player can see after the fact that a mod started a war.
 * gearbox:diplomacy "propose_war"
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "propose_war")
uint32_t gearbox_propose_war(gearbox_country attacker, gearbox_country defender);

/* Sets a country's treasury outright. Returns 1 on success, 0 if the
 * country is unknown or the value is not finite and within +/-1e12 -- NaN
 * or infinity would silently poison every later calculation, so they are
 * refused rather than stored.
 * gearbox:gamestate.write "set_country_treasury"
 * `(iF)i`
 */
GEARBOX_IMPORT("gamestate.write", "set_country_treasury")
uint32_t gearbox_set_country_treasury(gearbox_country country, double value);

/* Adds to a country's treasury. Usually what you want instead of set: it
 * composes with whatever the economy did this turn. Refused (0) if the
 * result would leave the sane range.
 * gearbox:gamestate.write "add_country_treasury"
 * `(iF)i`
 */
GEARBOX_IMPORT("gamestate.write", "add_country_treasury")
uint32_t gearbox_add_country_treasury(gearbox_country country, double delta);

/* Transfers a province to another country. Routed through the same code
 * the game's own ceasefires use, so the province, the ownership lookup,
 * the per-pixel country map and both countries' pixel lists all stay
 * consistent -- and the previous owner's troops in that province are
 * disbanded, as they are for any other transfer. Returns 0 if either
 * handle is unknown or the country already owns it. Always written to your
 * mod log: territory changing hands is the most consequential thing a mod
 * can do.
 * gearbox:gamestate.write "set_province_owner"
 * `(ii)i`
 */
GEARBOX_IMPORT("gamestate.write", "set_province_owner")
uint32_t gearbox_set_province_owner(gearbox_province province, gearbox_country country);

/* How many floats are in the AI's feature vector. 0 when there is no AI or
 * no world.
 * gearbox:neural "feature_count"
 * `()i`
 */
GEARBOX_IMPORT("neural", "feature_count")
uint32_t gearbox_feature_count(void);

/* Copies the feature vector the AI would see for a country, as 32-bit
 * floats. Two-call sizing, but note cap counts FLOATS and the buffer must
 * therefore be cap*4 bytes. This is a snapshot: writing to your copy does
 * not affect the AI.
 * gearbox:neural "features"
 * `(iii)i`
 */
GEARBOX_IMPORT("neural", "features")
uint32_t gearbox_features(gearbox_country country, char* buf, uint32_t cap);

/* How many reward channels the AI tracks (economy, politics, war, navy).
 * gearbox:neural "reward_count"
 * `()i`
 */
GEARBOX_IMPORT("neural", "reward_count")
uint32_t gearbox_reward_count(void);

/* The running mean reward for one channel, indexed in [0, reward_count). 0
 * if out of range. OBSERVE ONLY: this capability has no import that writes
 * to the model, the optimiser state or the reward history, which is
 * deliberate -- a trained model is hours of work and a mod that could
 * quietly retrain it is not something a user can meaningfully consent to.
 * gearbox:neural "reward_mean"
 * `(i)F`
 */
GEARBOX_IMPORT("neural", "reward_mean")
double gearbox_reward_mean(uint32_t index);

/* Sets a province's population. Returns 0 if the province is unknown, the
 * value is negative, or it exceeds 100 billion. The game stores population
 * in two places -- a map and a dense array used by the population texture
 * -- and this updates both, which is why it exists as an import rather
 * than being something a mod could do by other means.
 * gearbox:gamestate.write "set_province_population"
 * `(iI)i`
 */
GEARBOX_IMPORT("gamestate.write", "set_province_population")
uint32_t gearbox_set_province_population(gearbox_province province, int64_t value);

/* Queue a line from (x1,y1) to (x2,y2) in panel-relative pixels. Thickness
 * is clamped to 0.25..64. Clipped to your panel like every other command.
 * gearbox:ui "draw_line"
 * `(iiiiiFi)`
 */
GEARBOX_IMPORT("ui", "draw_line")
void gearbox_draw_line(gearbox_panel panel, uint32_t x1, uint32_t y1, uint32_t x2, uint32_t y2, double thickness, uint32_t rgba);

/* Queue a filled circle centred at (cx,cy), panel-relative. Radius is
 * clamped to 0..4096.
 * gearbox:ui "draw_circle"
 * `(iiiFi)`
 */
GEARBOX_IMPORT("ui", "draw_circle")
void gearbox_draw_circle(gearbox_panel panel, uint32_t cx, uint32_t cy, double radius, uint32_t rgba);

/* Queue an image from YOUR OWN package -- `name` is a path inside your
 * .odmod, resolved exactly as gearbox:assets/read resolves it, so you
 * cannot name a file on disk, a game asset, or another mod's art. Pass w
 * or h as 0 to use the image's own size. tint 0xFFFFFFFF draws it
 * unmodified. Decoded once and cached; a name that fails to decode draws
 * nothing and does not retry. PNG, JPG, BMP, TGA and GIF are recognised by
 * extension. This is the call that makes a real reskin possible.
 * gearbox:ui "draw_image"
 * `(iiiiiiii)`
 */
GEARBOX_IMPORT("ui", "draw_image")
void gearbox_draw_image(gearbox_panel panel, uint32_t x, uint32_t y, uint32_t w, uint32_t h, const char* name, uint32_t name_len, uint32_t tint);

/* Like draw_text but with a type size, clamped to 6..96. draw_text remains
 * 14pt, unchanged, so v1.0 mods look exactly as they did.
 * gearbox:ui "draw_text_sized"
 * `(iiiiiii)`
 */
GEARBOX_IMPORT("ui", "draw_text_sized")
void gearbox_draw_text_sized(gearbox_panel panel, uint32_t x, uint32_t y, uint32_t size, uint32_t rgba, const char* text, uint32_t text_len);

/* Width in pixels of `text` at `size`, measured with the font the game
 * will actually draw. Centring, right-alignment and wrapping all need this
 * before the text is queued.
 * gearbox:ui "measure_text"
 * `(iii)i`
 */
GEARBOX_IMPORT("ui", "measure_text")
uint32_t gearbox_measure_text(const char* text, uint32_t text_len, uint32_t size);

/* The width the host assigned your panel this frame, in pixels. Lay out
 * against this rather than against min_w -- the host may have given you
 * more.
 * gearbox:ui "panel_width"
 * `(i)i`
 */
GEARBOX_IMPORT("ui", "panel_width")
uint32_t gearbox_panel_width(gearbox_panel panel);

/* The height the host assigned your panel this frame, in pixels.
 * gearbox:ui "panel_height"
 * `(i)i`
 */
GEARBOX_IMPORT("ui", "panel_height")
uint32_t gearbox_panel_height(gearbox_panel panel);

/* Show or hide one of your panels. A hidden panel is not drawn and
 * receives no input, but keeps its handle and its registration.
 * gearbox:ui "panel_set_visible"
 * `(ii)`
 */
GEARBOX_IMPORT("ui", "panel_set_visible")
void gearbox_panel_set_visible(gearbox_panel panel, uint32_t visible);

/* Cursor X, panel-relative, or 0 when the cursor is not over your panel.
 * You cannot observe the pointer outside your own box.
 * gearbox:ui "mouse_x"
 * `(i)F`
 */
GEARBOX_IMPORT("ui", "mouse_x")
double gearbox_mouse_x(gearbox_panel panel);

/* Cursor Y, panel-relative, or 0 when the cursor is not over your panel.
 * gearbox:ui "mouse_y"
 * `(i)F`
 */
GEARBOX_IMPORT("ui", "mouse_y")
double gearbox_mouse_y(gearbox_panel panel);

/* Whether the cursor is over your panel this frame.
 * gearbox:ui "mouse_inside"
 * `(i)i`
 */
GEARBOX_IMPORT("ui", "mouse_inside")
uint32_t gearbox_mouse_inside(gearbox_panel panel);

/* The PLAYER's accent colour as 0x00RRGGBB -- not another mod's override.
 * Build your palette around this and you harmonise with what they chose.
 * gearbox:ui "theme_accent"
 * `()i`
 */
GEARBOX_IMPORT("ui", "theme_accent")
uint32_t gearbox_theme_accent(void);

/* Restyle the whole interface. The accent is read at over a hundred sites
 * -- every heading, highlight, selection and button -- so this is the
 * cheapest full reskin there is. It is NOT persisted: the game's settings
 * file keeps the player's own colour, and the override is dropped the
 * moment no mod is running, so it cannot outlive uninstalling you.
 * gearbox:ui "set_theme_accent"
 * `(i)i`
 */
GEARBOX_IMPORT("ui", "set_theme_accent")
uint32_t gearbox_set_theme_accent(uint32_t rgb);

/* How many ships exist in the world, across all owners.
 * gearbox:military.read "ship_count"
 * `()i`
 */
GEARBOX_IMPORT("military.read", "ship_count")
uint32_t gearbox_ship_count(void);

/* The ship id at `index` in 0..ship_count-1, or 0xFFFFFFFF past the end.
 * Ids are stable within a turn and not across turns -- do not store one.
 * gearbox:military.read "ship_at"
 * `(i)i`
 */
GEARBOX_IMPORT("military.read", "ship_at")
uint32_t gearbox_ship_at(uint32_t index);

/* Whether a ship id is still live. Check this before acting on an id you
 * read earlier in the same turn; ships sink.
 * gearbox:military.read "ship_exists"
 * `(i)i`
 */
GEARBOX_IMPORT("military.read", "ship_exists")
uint32_t gearbox_ship_exists(uint32_t ship);

/* The country that owns a ship, or 0xFFFFFFFF for an id that does not
 * exist.
 * gearbox:military.read "ship_owner"
 * `(i)i`
 */
GEARBOX_IMPORT("military.read", "ship_owner")
uint32_t gearbox_ship_owner(uint32_t ship);

/* The hull type as a lowercase string: "transport", "destroyer",
 * "battleship", "carrier", "submarine". Two-call sizing: call with cap 0
 * to learn the length, allocate, call again. Returns the full length
 * either way; the copy is truncated to cap.
 * gearbox:military.read "ship_type"
 * `(iii)i`
 */
GEARBOX_IMPORT("military.read", "ship_type")
uint32_t gearbox_ship_type(uint32_t ship, char* buf, uint32_t cap);

/* Longitude in degrees, -180..180. Ships live in world coordinates, not
 * provinces.
 * gearbox:military.read "ship_lon"
 * `(i)F`
 */
GEARBOX_IMPORT("military.read", "ship_lon")
double gearbox_ship_lon(uint32_t ship);

/* Latitude in degrees, -90..90.
 * gearbox:military.read "ship_lat"
 * `(i)F`
 */
GEARBOX_IMPORT("military.read", "ship_lat")
double gearbox_ship_lat(uint32_t ship);

/* Hull integrity, 0..100. A ship at 0 has already sunk and will not
 * appear.
 * gearbox:military.read "ship_health"
 * `(i)i`
 */
GEARBOX_IMPORT("military.read", "ship_health")
uint32_t gearbox_ship_health(uint32_t ship);

/* Crew aboard. For a transport this includes the embarked army, which is
 * why a sunk transport costs so much more than its hull.
 * gearbox:military.read "ship_crew"
 * `(i)i`
 */
GEARBOX_IMPORT("military.read", "ship_crew")
uint32_t gearbox_ship_crew(uint32_t ship);

/* How far this hull may move in one turn, in degrees. The resolver clamps
 * any order beyond it, so read this before ordering a move rather than
 * discovering the clamp afterwards.
 * gearbox:military.read "ship_range"
 * `(i)F`
 */
GEARBOX_IMPORT("military.read", "ship_range")
double gearbox_ship_range(uint32_t ship);

/* How many distinct owners have troops in a province. Usually 1; more than
 * one means a contested or garrisoned province.
 * gearbox:military.read "army_stack_count"
 * `(i)i`
 */
GEARBOX_IMPORT("military.read", "army_stack_count")
uint32_t gearbox_army_stack_count(uint32_t province);

/* The country owning stack `index` in a province, or 0xFFFFFFFF past the
 * end.
 * gearbox:military.read "army_stack_owner"
 * `(ii)i`
 */
GEARBOX_IMPORT("military.read", "army_stack_owner")
uint32_t gearbox_army_stack_owner(uint32_t province, uint32_t index);

/* How many troops are in that stack.
 * gearbox:military.read "army_stack_size"
 * `(ii)I`
 */
GEARBOX_IMPORT("military.read", "army_stack_size")
int64_t gearbox_army_stack_size(uint32_t province, uint32_t index);

/* A country's total troops everywhere, which is the number its own army
 * screen shows.
 * gearbox:military.read "country_army"
 * `(i)I`
 */
GEARBOX_IMPORT("military.read", "country_army")
int64_t gearbox_country_army(uint32_t country);

/* Fortification level, 0..5. Multiplies the defender's strength.
 * gearbox:military.read "province_fortification"
 * `(i)i`
 */
GEARBOX_IMPORT("military.read", "province_fortification")
uint32_t gearbox_province_fortification(uint32_t province);

/* Port level, 0..3. 0 means no port, so no embarking and no ship repair.
 * gearbox:military.read "province_port_level"
 * `(i)i`
 */
GEARBOX_IMPORT("military.read", "province_port_level")
uint32_t gearbox_province_port_level(uint32_t province);

/* Move `percent` (0..100) of the troops in `from` into the adjacent
 * province `to`. Into an enemy province this is an attack; into your own
 * or an ally's it is a transfer. Non-adjacent moves are refused. QUEUES AN
 * ORDER; it does not move anything. It lands in the same queue the
 * player's own click writes to and is validated by the same resolver at
 * end of turn, so a mod cannot teleport, cheat range, or attack across an
 * ocean. Returns 0 if the order is rejected outright.
 * gearbox:military.write "order_army_move"
 * `(iii)i`
 */
GEARBOX_IMPORT("military.write", "order_army_move")
uint32_t gearbox_order_army_move(uint32_t from, uint32_t to, uint32_t percent);

/* Sail a ship toward (lon,lat). The resolver routes around land and clamps
 * to ship_range, so a destination on land or beyond range moves the ship
 * as far as it legally can rather than failing. QUEUES AN ORDER; it does
 * not move anything. It lands in the same queue the player's own click
 * writes to and is validated by the same resolver at end of turn, so a mod
 * cannot teleport, cheat range, or attack across an ocean. Returns 0 if
 * the order is rejected outright.
 * gearbox:military.write "order_ship_move"
 * `(iFF)i`
 */
GEARBOX_IMPORT("military.write", "order_ship_move")
uint32_t gearbox_order_ship_move(uint32_t ship, double lon, double lat);

/* Attack another ship. Requires that you are at war with its owner and
 * that it is within range; both are checked by the resolver. QUEUES AN
 * ORDER; it does not move anything. It lands in the same queue the
 * player's own click writes to and is validated by the same resolver at
 * end of turn, so a mod cannot teleport, cheat range, or attack across an
 * ocean. Returns 0 if the order is rejected outright.
 * gearbox:military.write "order_ship_engage"
 * `(ii)i`
 */
GEARBOX_IMPORT("military.write", "order_ship_engage")
uint32_t gearbox_order_ship_engage(uint32_t ship, uint32_t target);

/* Bombard a coastal province. `ammo` names the shell type; pass an empty
 * string for the default. QUEUES AN ORDER; it does not move anything. It
 * lands in the same queue the player's own click writes to and is
 * validated by the same resolver at end of turn, so a mod cannot teleport,
 * cheat range, or attack across an ocean. Returns 0 if the order is
 * rejected outright.
 * gearbox:military.write "order_ship_bombard"
 * `(iiii)i`
 */
GEARBOX_IMPORT("military.write", "order_ship_bombard")
uint32_t gearbox_order_ship_bombard(uint32_t ship, uint32_t province, const char* ammo, uint32_t ammo_len);

/* How many technologies exist in the tree.
 * gearbox:research.read "node_count"
 * `()i`
 */
GEARBOX_IMPORT("research.read", "node_count")
uint32_t gearbox_node_count(void);

/* The stable string id of technology `index`, which is what
 * country_has_researched takes. Two-call sizing: call with cap 0 to learn
 * the length, allocate, call again. Returns the full length either way;
 * the copy is truncated to cap.
 * gearbox:research.read "node_id"
 * `(iii)i`
 */
GEARBOX_IMPORT("research.read", "node_id")
uint32_t gearbox_node_id(uint32_t index, char* buf, uint32_t cap);

/* The technology's display name, which is localised and NOT stable --
 * never match on it. Two-call sizing: call with cap 0 to learn the length,
 * allocate, call again. Returns the full length either way; the copy is
 * truncated to cap.
 * gearbox:research.read "node_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("research.read", "node_name")
uint32_t gearbox_node_name(uint32_t index, char* buf, uint32_t cap);

/* Which branch of the tree it sits in. Two-call sizing: call with cap 0 to
 * learn the length, allocate, call again. Returns the full length either
 * way; the copy is truncated to cap.
 * gearbox:research.read "node_category"
 * `(iii)i`
 */
GEARBOX_IMPORT("research.read", "node_category")
uint32_t gearbox_node_category(uint32_t index, char* buf, uint32_t cap);

/* Research points required.
 * gearbox:research.read "node_cost"
 * `(i)i`
 */
GEARBOX_IMPORT("research.read", "node_cost")
uint32_t gearbox_node_cost(uint32_t index);

/* Whether a country has completed a technology. Takes the id from node_id,
 * not the display name.
 * gearbox:research.read "country_has_researched"
 * `(iii)i`
 */
GEARBOX_IMPORT("research.read", "country_has_researched")
uint32_t gearbox_country_has_researched(uint32_t country, const char* node_id, uint32_t node_id_len);

/* Research funding as A SHARE OF INCOME, 0..1 -- not an absolute sum. That
 * is how the game stores it and how its own economy screen presents it.
 * gearbox:research.read "country_funding"
 * `(i)F`
 */
GEARBOX_IMPORT("research.read", "country_funding")
double gearbox_country_funding(uint32_t country);

/* Set research funding as a share of income. Clamped to 0..1; a value in
 * 'points per turn' is not a quantity this game has.
 * gearbox:research.write "set_country_funding"
 * `(iF)i`
 */
GEARBOX_IMPORT("research.write", "set_country_funding")
uint32_t gearbox_set_country_funding(uint32_t country, double share);

/* Economic axis of the political compass, -100 (planned) to 100 (market).
 * gearbox:politics.read "country_compass_econ"
 * `(i)F`
 */
GEARBOX_IMPORT("politics.read", "country_compass_econ")
double gearbox_country_compass_econ(uint32_t country);

/* Social axis, -100 (authoritarian) to 100 (libertarian).
 * gearbox:politics.read "country_compass_social"
 * `(i)F`
 */
GEARBOX_IMPORT("politics.read", "country_compass_social")
double gearbox_country_compass_social(uint32_t country);

/* This province's chance of rebelling, as the game itself computes it.
 * gearbox:politics.read "province_unrest"
 * `(i)F`
 */
GEARBOX_IMPORT("politics.read", "province_unrest")
double gearbox_province_unrest(uint32_t province);

/* How many policies exist.
 * gearbox:politics.read "policy_count"
 * `()i`
 */
GEARBOX_IMPORT("politics.read", "policy_count")
uint32_t gearbox_policy_count(void);

/* The stable string id of policy `index`. Two-call sizing: call with cap 0
 * to learn the length, allocate, call again. Returns the full length
 * either way; the copy is truncated to cap.
 * gearbox:politics.read "policy_id"
 * `(iii)i`
 */
GEARBOX_IMPORT("politics.read", "policy_id")
uint32_t gearbox_policy_id(uint32_t index, char* buf, uint32_t cap);

/* The policy's display name; localised, not stable, do not match on it.
 * Two-call sizing: call with cap 0 to learn the length, allocate, call
 * again. Returns the full length either way; the copy is truncated to cap.
 * gearbox:politics.read "policy_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("politics.read", "policy_name")
uint32_t gearbox_policy_name(uint32_t index, char* buf, uint32_t cap);

/* Whether a country currently has a policy active or implementing.
 * gearbox:politics.read "country_has_policy"
 * `(iii)i`
 */
GEARBOX_IMPORT("politics.read", "country_has_policy")
uint32_t gearbox_country_has_policy(uint32_t country, const char* policy_id, uint32_t policy_id_len);

/* How many named minority groups live in a province.
 * gearbox:politics.read "province_minority_count"
 * `(i)i`
 */
GEARBOX_IMPORT("politics.read", "province_minority_count")
uint32_t gearbox_province_minority_count(uint32_t province);

/* The minority's name. Two-call sizing: call with cap 0 to learn the
 * length, allocate, call again. Returns the full length either way; the
 * copy is truncated to cap.
 * gearbox:politics.read "province_minority_name"
 * `(iiii)i`
 */
GEARBOX_IMPORT("politics.read", "province_minority_name")
uint32_t gearbox_province_minority_name(uint32_t province, uint32_t index, char* buf, uint32_t cap);

/* That minority's share of the province's population, 0..1.
 * gearbox:politics.read "province_minority_share"
 * `(ii)F`
 */
GEARBOX_IMPORT("politics.read", "province_minority_share")
double gearbox_province_minority_share(uint32_t province, uint32_t index);

/* Enact or cancel a policy. GOES THROUGH THE GAME'S OWN enactPolicy, so
 * the cost, the prerequisites and the per-turn enactment cap all still
 * apply -- a country cannot end up running policies it could never have
 * afforded. Returns 1 if the policy is already in the requested state.
 * gearbox:politics.write "set_country_policy"
 * `(iiii)i`
 */
GEARBOX_IMPORT("politics.write", "set_country_policy")
uint32_t gearbox_set_country_policy(uint32_t country, const char* policy_id, uint32_t policy_id_len, uint32_t enabled);

/* Income per turn before upkeep.
 * gearbox:economy.read "country_income_gross"
 * `(i)F`
 */
GEARBOX_IMPORT("economy.read", "country_income_gross")
double gearbox_country_income_gross(uint32_t country);

/* Income per turn after army and navy upkeep. Negative means the treasury
 * is draining.
 * gearbox:economy.read "country_income_net"
 * `(i)F`
 */
GEARBOX_IMPORT("economy.read", "country_income_net")
double gearbox_country_income_net(uint32_t country);

/* What the standing army costs per turn.
 * gearbox:economy.read "country_army_upkeep"
 * `(i)F`
 */
GEARBOX_IMPORT("economy.read", "country_army_upkeep")
double gearbox_country_army_upkeep(uint32_t country);

/* What the fleet costs per turn. Ships a country is not using still cost
 * this, which is what makes scrapping a real decision.
 * gearbox:economy.read "country_navy_upkeep"
 * `(i)F`
 */
GEARBOX_IMPORT("economy.read", "country_navy_upkeep")
double gearbox_country_navy_upkeep(uint32_t country);

/* Whether a country is currently bankrupt.
 * gearbox:economy.read "country_is_bankrupt"
 * `(i)i`
 */
GEARBOX_IMPORT("economy.read", "country_is_bankrupt")
uint32_t gearbox_country_is_bankrupt(uint32_t country);

/* Industry level, 0..10.
 * gearbox:economy.read "province_industry_level"
 * `(i)i`
 */
GEARBOX_IMPORT("economy.read", "province_industry_level")
uint32_t gearbox_province_industry_level(uint32_t province);

/* What this province's industry specialises in, or an empty string for
 * none. Two-call sizing: call with cap 0 to learn the length, allocate,
 * call again. Returns the full length either way; the copy is truncated to
 * cap.
 * gearbox:economy.read "province_industry_specialization"
 * `(iii)i`
 */
GEARBOX_IMPORT("economy.read", "province_industry_specialization")
uint32_t gearbox_province_industry_specialization(uint32_t province, char* buf, uint32_t cap);

/* How much of a resource a province holds, 0..100. `which` is one of
 * "oil", "gold", "rubber", "gemstones", "metal"; anything else reads 0.
 * gearbox:economy.read "province_resource"
 * `(iii)F`
 */
GEARBOX_IMPORT("economy.read", "province_resource")
double gearbox_province_resource(uint32_t province, const char* which, uint32_t which_len);

/* Set a province's industry level, clamped to 0..10. This writes the built
 * level directly and does not charge for it -- it is a scenario-authoring
 * tool, not a build order.
 * gearbox:economy.write "set_province_industry_level"
 * `(ii)i`
 */
GEARBOX_IMPORT("economy.write", "set_province_industry_level")
uint32_t gearbox_set_province_industry_level(uint32_t province, uint32_t level);

/* Whether a province touches water. Ports, embarking and naval bombardment
 * all require it.
 * gearbox:map "province_is_coastal"
 * `(i)i`
 */
GEARBOX_IMPORT("map", "province_is_coastal")
uint32_t gearbox_province_is_coastal(uint32_t province);

/* Whether a fleet could get from one point to another by sea, using the
 * game's own navigation grid. You cannot compute this from province
 * neighbours: those describe LAND adjacency.
 * gearbox:map "sea_route_exists"
 * `(FFFF)i`
 */
GEARBOX_IMPORT("map", "sea_route_exists")
uint32_t gearbox_sea_route_exists(double from_lon, double from_lat, double to_lon, double to_lat);

/* Whether a world coordinate is land. Ordering a ship onto land is not an
 * error -- the resolver clamps it -- but knowing first is cheaper.
 * gearbox:map "point_is_land"
 * `(FF)i`
 */
GEARBOX_IMPORT("map", "point_is_land")
uint32_t gearbox_point_is_land(double lon, double lat);

/* Whether the map editor is open with a project loaded. EVERY OTHER CALL
 * IN THIS MODULE returns 0 or an empty string when this is 0, including
 * from inside a running game: the data behind them is an editor project,
 * and a game does not have one. Check this first.
 * gearbox:mapeditor "editor_active"
 * `()i`
 */
GEARBOX_IMPORT("mapeditor", "editor_active")
uint32_t gearbox_editor_active(void);

/* How many provinces the open project has. Returns a neutral value unless
 * the map editor is open with a project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_count"
 * `()i`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_count")
uint32_t gearbox_editor_province_count(void);

/* The province id at `index`, in ascending id order, or 0xFFFFFFFF past
 * the end. Returns a neutral value unless the map editor is open with a
 * project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_at"
 * `(i)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_at")
uint32_t gearbox_editor_province_at(uint32_t index);

/* Population. Returns a neutral value unless the map editor is open with a
 * project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_population"
 * `(i)I`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_population")
int64_t gearbox_editor_province_population(uint32_t province);

/* Industry level, 0..10. Returns a neutral value unless the map editor is
 * open with a project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_industry_level"
 * `(i)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_industry_level")
uint32_t gearbox_editor_province_industry_level(uint32_t province);

/* Fortification, 0..5. Returns a neutral value unless the map editor is
 * open with a project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_fortification"
 * `(i)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_fortification")
uint32_t gearbox_editor_province_fortification(uint32_t province);

/* Port level, 0..3. Returns a neutral value unless the map editor is open
 * with a project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_port_level"
 * `(i)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_port_level")
uint32_t gearbox_editor_province_port_level(uint32_t province);

/* Resource amount, 0..100. `which` is "oil", "gold", "rubber", "gemstones"
 * or "metal". Returns a neutral value unless the map editor is open with a
 * project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_resource"
 * `(iii)F`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_resource")
double gearbox_editor_province_resource(uint32_t province, const char* which, uint32_t which_len);

/* Province economic compass, -100..100. Returns a neutral value unless the
 * map editor is open with a project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_compass_econ"
 * `(i)F`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_compass_econ")
double gearbox_editor_province_compass_econ(uint32_t province);

/* Province social compass, -100..100. Returns a neutral value unless the
 * map editor is open with a project loaded -- see mapeditor/active.
 * gearbox:mapeditor "editor_province_compass_social"
 * `(i)F`
 */
GEARBOX_IMPORT("mapeditor", "editor_province_compass_social")
double gearbox_editor_province_compass_social(uint32_t province);

/* Set population, clamped to 0..2e9. Writes the SAME per-province data the
 * editor's own tools write, so it saves, exports and shows up in the
 * unsaved-changes prompt like any other edit. A province the project does
 * not have is refused rather than created: data without a shape on the
 * province bitmap exports a map the game cannot load.
 * gearbox:mapeditor "editor_set_province_population"
 * `(iI)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_province_population")
uint32_t gearbox_editor_set_province_population(uint32_t province, int64_t value);

/* Set industry level, clamped to 0..10. Writes the SAME per-province data
 * the editor's own tools write, so it saves, exports and shows up in the
 * unsaved-changes prompt like any other edit. A province the project does
 * not have is refused rather than created: data without a shape on the
 * province bitmap exports a map the game cannot load.
 * gearbox:mapeditor "editor_set_province_industry_level"
 * `(ii)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_province_industry_level")
uint32_t gearbox_editor_set_province_industry_level(uint32_t province, uint32_t level);

/* Set fortification, clamped to 0..5. Writes the SAME per-province data
 * the editor's own tools write, so it saves, exports and shows up in the
 * unsaved-changes prompt like any other edit. A province the project does
 * not have is refused rather than created: data without a shape on the
 * province bitmap exports a map the game cannot load.
 * gearbox:mapeditor "editor_set_province_fortification"
 * `(ii)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_province_fortification")
uint32_t gearbox_editor_set_province_fortification(uint32_t province, uint32_t level);

/* Set port level, clamped to 0..3. Writes the SAME per-province data the
 * editor's own tools write, so it saves, exports and shows up in the
 * unsaved-changes prompt like any other edit. A province the project does
 * not have is refused rather than created: data without a shape on the
 * province bitmap exports a map the game cannot load.
 * gearbox:mapeditor "editor_set_province_port_level"
 * `(ii)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_province_port_level")
uint32_t gearbox_editor_set_province_port_level(uint32_t province, uint32_t level);

/* Set a resource amount, clamped to 0..100. An unrecognised name is
 * refused rather than silently mapped onto oil. Writes the SAME
 * per-province data the editor's own tools write, so it saves, exports and
 * shows up in the unsaved-changes prompt like any other edit. A province
 * the project does not have is refused rather than created: data without a
 * shape on the province bitmap exports a map the game cannot load.
 * gearbox:mapeditor "editor_set_province_resource"
 * `(iiiF)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_province_resource")
uint32_t gearbox_editor_set_province_resource(uint32_t province, const char* which, uint32_t which_len, double amount);

/* Set both compass axes, each clamped to -100..100. Writes the SAME
 * per-province data the editor's own tools write, so it saves, exports and
 * shows up in the unsaved-changes prompt like any other edit. A province
 * the project does not have is refused rather than created: data without a
 * shape on the province bitmap exports a map the game cannot load.
 * gearbox:mapeditor "editor_set_province_compass"
 * `(iFF)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_province_compass")
uint32_t gearbox_editor_set_province_compass(uint32_t province, double econ, double social);

/* The project's map name. Two-call sizing: call with cap 0 to learn the
 * length, allocate, call again. Returns the full length either way; the
 * copy is truncated to cap.
 * gearbox:mapeditor "editor_map_name"
 * `(ii)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_map_name")
uint32_t gearbox_editor_map_name(char* buf, uint32_t cap);

/* Rename the map. Refused if empty or over 96 bytes.
 * gearbox:mapeditor "editor_set_map_name"
 * `(ii)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_map_name")
uint32_t gearbox_editor_set_map_name(const char* name, uint32_t name_len);

/* Set the author recorded in the exported .odmap. Up to 96 bytes.
 * gearbox:mapeditor "editor_set_author"
 * `(ii)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_author")
uint32_t gearbox_editor_set_author(const char* author, uint32_t author_len);

/* Set the licence recorded in the exported .odmap. Up to 96 bytes.
 * gearbox:mapeditor "editor_set_license"
 * `(ii)i`
 */
GEARBOX_IMPORT("mapeditor", "editor_set_license")
uint32_t gearbox_editor_set_license(const char* license, uint32_t license_len);

/* The peer id at `index` in 0..peer_count-1, or 0xFFFFFFFF past the end.
 * This is the id net/send takes.
 * gearbox:net "peer_at"
 * `(i)i`
 */
GEARBOX_IMPORT("net", "peer_at")
uint32_t gearbox_peer_at(uint32_t index);

/* That peer's display name -- deliberately NOT their account id or issuer.
 * A mod has no business correlating players across sessions. Two-call
 * sizing: call with cap 0 to learn the length, allocate, call again.
 * Returns the full length either way; the copy is truncated to cap.
 * gearbox:net "peer_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("net", "peer_name")
uint32_t gearbox_peer_name(uint32_t index, char* buf, uint32_t cap);

/* The largest payload net/send will accept. Chunk against this rather than
 * discovering the limit by having a message dropped.
 * gearbox:net "max_message_bytes"
 * `()i`
 */
GEARBOX_IMPORT("net", "max_message_bytes")
uint32_t gearbox_max_message_bytes(void);

/* How many decision modules the AI has. Each acts independently every
 * turn.
 * gearbox:neural "module_count"
 * `()i`
 */
GEARBOX_IMPORT("neural", "module_count")
uint32_t gearbox_module_count(void);

/* The module's name: "economy", "politics", "war", "navy". Two-call
 * sizing: call with cap 0 to learn the length, allocate, call again.
 * Returns the full length either way; the copy is truncated to cap.
 * gearbox:neural "module_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("neural", "module_name")
uint32_t gearbox_module_name(uint32_t module, char* buf, uint32_t cap);

/* How many actions that module can choose between.
 * gearbox:neural "action_count"
 * `(i)i`
 */
GEARBOX_IMPORT("neural", "action_count")
uint32_t gearbox_action_count(uint32_t module);

/* The action's name, e.g. "reinforce", "embark", "propose_alliance". THE
 * FEATURE VECTOR IS DELIBERATELY NOT NAMED: its 143 slots are an
 * implementation detail that has changed before and will again, and a mod
 * written against those names would break silently. What the AI CAN DO is
 * stable enough to build an advisor or a decision log against. Two-call
 * sizing: call with cap 0 to learn the length, allocate, call again.
 * Returns the full length either way; the copy is truncated to cap.
 * gearbox:neural "action_name"
 * `(iiii)i`
 */
GEARBOX_IMPORT("neural", "action_name")
uint32_t gearbox_action_name(uint32_t module, uint32_t action, char* buf, uint32_t cap);

/* Whether a country is played by the AI rather than by the local player.
 * gearbox:neural "country_is_ai"
 * `(i)i`
 */
GEARBOX_IMPORT("neural", "country_is_ai")
uint32_t gearbox_country_is_ai(uint32_t country);

/* Gradient updates the loaded model has been through -- roughly, how much
 * training it has seen.
 * gearbox:neural "update_count"
 * `()I`
 */
GEARBOX_IMPORT("neural", "update_count")
int64_t gearbox_update_count(void);

/* Whether an AI model is loaded at all. False in a game with no AI
 * players.
 * gearbox:neural "model_loaded"
 * `()i`
 */
GEARBOX_IMPORT("neural", "model_loaded")
uint32_t gearbox_model_loaded(void);

/* How many districts this country is divided into. Districts are built on
 * demand, so asking is what creates the default one for a country that has
 * never been divided.
 * gearbox:politics.read "country_district_count"
 * `(i)i`
 */
GEARBOX_IMPORT("politics.read", "country_district_count")
uint32_t gearbox_country_district_count(uint32_t country);

/* The district's name. Two-call sizing: call with cap 0 to learn the
 * length, allocate, call again. Returns the full length either way; the
 * copy is truncated to cap.
 * gearbox:politics.read "country_district_name"
 * `(iiii)i`
 */
GEARBOX_IMPORT("politics.read", "country_district_name")
uint32_t gearbox_country_district_name(uint32_t country, uint32_t index, char* buf, uint32_t cap);

/* This district's claim on the country's pacification budget, in percent.
 * The shares of a country's districts sum to 100.
 * gearbox:politics.read "country_district_share"
 * `(ii)i`
 */
GEARBOX_IMPORT("politics.read", "country_district_share")
uint32_t gearbox_country_district_share(uint32_t country, uint32_t index);

/* How many provinces this district holds.
 * gearbox:politics.read "country_district_province_count"
 * `(ii)i`
 */
GEARBOX_IMPORT("politics.read", "country_district_province_count")
uint32_t gearbox_country_district_province_count(uint32_t country, uint32_t index);

/* Province `n` of this district, or GEARBOX_INVALID if there is no such
 * one.
 * gearbox:politics.read "country_district_province"
 * `(iii)i`
 */
GEARBOX_IMPORT("politics.read", "country_district_province")
uint32_t gearbox_country_district_province(uint32_t country, uint32_t index, uint32_t n);

/* How many regional laws this district runs.
 * gearbox:politics.read "country_district_law_count"
 * `(ii)i`
 */
GEARBOX_IMPORT("politics.read", "country_district_law_count")
uint32_t gearbox_country_district_law_count(uint32_t country, uint32_t index);

/* The stable id of regional law `n` in this district. Two-call sizing:
 * call with cap 0 to learn the length, allocate, call again. Returns the
 * full length either way; the copy is truncated to cap.
 * gearbox:politics.read "country_district_law"
 * `(iiiii)i`
 */
GEARBOX_IMPORT("politics.read", "country_district_law")
uint32_t gearbox_country_district_law(uint32_t country, uint32_t index, uint32_t n, char* buf, uint32_t cap);

/* How many regional laws exist to choose from.
 * gearbox:politics.read "district_law_count"
 * `()i`
 */
GEARBOX_IMPORT("politics.read", "district_law_count")
uint32_t gearbox_district_law_count(void);

/* The stable id of regional law `index`. Two-call sizing: call with cap 0
 * to learn the length, allocate, call again. Returns the full length
 * either way; the copy is truncated to cap.
 * gearbox:politics.read "district_law_id"
 * `(iii)i`
 */
GEARBOX_IMPORT("politics.read", "district_law_id")
uint32_t gearbox_district_law_id(uint32_t index, char* buf, uint32_t cap);

/* The display name of regional law `index`, untranslated. Two-call sizing:
 * call with cap 0 to learn the length, allocate, call again. Returns the
 * full length either way; the copy is truncated to cap.
 * gearbox:politics.read "district_law_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("politics.read", "district_law_name")
uint32_t gearbox_district_law_name(uint32_t index, char* buf, uint32_t cap);

/* Whether this country publishes that figure in its profile: 1 if it does,
 * 0 if it keeps it to itself. See the disclosure_field enum. Publishing is
 * a decision with a consequence -- migrants read it -- rather than a
 * display setting.
 * gearbox:politics.read "country_discloses"
 * `(ii)i`
 */
GEARBOX_IMPORT("politics.read", "country_discloses")
uint32_t gearbox_country_discloses(uint32_t country, uint32_t field);

/* Set this district's claim on the pacification budget. The other
 * districts are rebalanced so the shares still sum to 100, exactly as
 * dragging the slider does. Returns 1 on success.
 * gearbox:politics.write "set_country_district_share"
 * `(iii)i`
 */
GEARBOX_IMPORT("politics.write", "set_country_district_share")
uint32_t gearbox_set_country_district_share(uint32_t country, uint32_t index, uint32_t percent);

/* Pass or repeal a regional law in this district. Returns 1 on success, 0
 * for an unknown law or district.
 * gearbox:politics.write "set_country_district_law"
 * `(iiiii)i`
 */
GEARBOX_IMPORT("politics.write", "set_country_district_law")
uint32_t gearbox_set_country_district_law(uint32_t country, uint32_t index, const char* law, uint32_t law_len, uint32_t on);

/* Publish or withhold one of the figures in this country's profile.
 * Returns 1 on success.
 * gearbox:politics.write "set_country_disclosure"
 * `(iii)i`
 */
GEARBOX_IMPORT("politics.write", "set_country_disclosure")
uint32_t gearbox_set_country_disclosure(uint32_t country, uint32_t field, uint32_t on);

/* How many kinds of soldier exist.
 * gearbox:military.read "troop_type_count"
 * `()i`
 */
GEARBOX_IMPORT("military.read", "troop_type_count")
uint32_t gearbox_troop_type_count(void);

/* The stable id of troop type `index` -- line, militia, assault, mech.
 * Never translated. Two-call sizing: call with cap 0 to learn the length,
 * allocate, call again. Returns the full length either way; the copy is
 * truncated to cap.
 * gearbox:military.read "troop_type_id"
 * `(iii)i`
 */
GEARBOX_IMPORT("military.read", "troop_type_id")
uint32_t gearbox_troop_type_id(uint32_t index, char* buf, uint32_t cap);

/* How many soldiers of that kind this country has, everywhere. 0 for a
 * troop type that does not exist.
 * gearbox:military.read "country_army_of_type"
 * `(iii)I`
 */
GEARBOX_IMPORT("military.read", "country_army_of_type")
int64_t gearbox_country_army_of_type(uint32_t country, const char* troop_type, uint32_t troop_type_len);

/* How many soldiers of that kind this country has standing in that
 * province.
 * gearbox:military.read "province_troops_of_type"
 * `(iiii)I`
 */
GEARBOX_IMPORT("military.read", "province_troops_of_type")
int64_t gearbox_province_troops_of_type(uint32_t province, uint32_t country, const char* troop_type, uint32_t troop_type_len);

/* How many research programmes this country may run at once, 1 to 3. This
 * is the effective number, including any override a script or a mod has
 * set.
 * gearbox:research.read "country_research_groups"
 * `(i)i`
 */
GEARBOX_IMPORT("research.read", "country_research_groups")
uint32_t gearbox_country_research_groups(uint32_t country);

/* Force how many research programmes a country may run, 1 to 3, or 0 to
 * hand the decision back to its economy. Outranks the economic gate in
 * both directions and is saved with the game. Returns 1 on success.
 * gearbox:research.write "set_country_research_groups"
 * `(ii)i`
 */
GEARBOX_IMPORT("research.write", "set_country_research_groups")
uint32_t gearbox_set_country_research_groups(uint32_t country, uint32_t groups);

/* What this country spent last turn, in total. The same figure its profile
 * publishes and the economy screen draws.
 * gearbox:economy.read "country_expenses"
 * `(i)F`
 */
GEARBOX_IMPORT("economy.read", "country_expenses")
double gearbox_country_expenses(uint32_t country);

/* What the whole country is worth: every industry level, fort, port and
 * division at what it cost to raise. A stock, where the income figures are
 * flows.
 * gearbox:economy.read "country_national_value"
 * `(i)F`
 */
GEARBOX_IMPORT("economy.read", "country_national_value")
double gearbox_country_national_value(uint32_t country);

/* How many people live in this country.
 * gearbox:economy.read "country_population"
 * `(i)I`
 */
GEARBOX_IMPORT("economy.read", "country_population")
int64_t gearbox_country_population(uint32_t country);

/* The AI's own version, e.g. "ParrotZero 8.4.0" -- ARCH.RULES.PATCH, and
 * independent of the game's version. ARCH is the network shape and action
 * space, RULES is behaviour a benchmark can see, PATCH cannot move a
 * number. A mod that reads the feature vector should check ARCH before
 * trusting its layout, and anything comparing measurements across builds
 * should record RULES. Two-call sizing: call with cap 0 to learn the
 * length, allocate, call again. Returns the full length either way; the
 * copy is truncated to cap.
 * gearbox:neural "ai_version"
 * `(ii)i`
 */
GEARBOX_IMPORT("neural", "ai_version")
uint32_t gearbox_ai_version(char* buf, uint32_t cap);

/* The AI's ARCH number on its own, which is also the model file's format
 * byte. The feature count and the action sets are only stable within one
 * ARCH; a bump means old weights are refused on purpose.
 * gearbox:neural "ai_arch"
 * `()i`
 */
GEARBOX_IMPORT("neural", "ai_arch")
uint32_t gearbox_ai_arch(void);

/* The posture the AI has chosen for this country -- 0 expand, 1
 * consolidate, 2 defend, 3 develop -- or GEARBOX_INVALID if it holds none
 * (a country the AI does not play, or one that has not been given a stance
 * yet). Held for several turns at a time rather than chosen fresh each
 * turn.
 * gearbox:neural "country_stance"
 * `(i)i`
 */
GEARBOX_IMPORT("neural", "country_stance")
uint32_t gearbox_country_stance(uint32_t country);

/* The stance's name: "expand", "consolidate", "defend", "develop". Never
 * translated, and stable within an ARCH. Two-call sizing: call with cap 0
 * to learn the length, allocate, call again. Returns the full length
 * either way; the copy is truncated to cap.
 * gearbox:neural "stance_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("neural", "stance_name")
uint32_t gearbox_stance_name(uint32_t index, char* buf, uint32_t cap);

/* How many stances there are to choose between.
 * gearbox:neural "stance_count"
 * `()i`
 */
GEARBOX_IMPORT("neural", "stance_count")
uint32_t gearbox_stance_count(void);

/* Which actions the host will accept for this module right now, one byte
 * per action: 1 legal, 0 not. Two-call sizing, like every other copy here.
 * MEANINGFUL ONLY INSIDE mod_ai_choose, because a legality mask is a fact
 * about a decision in progress; outside one it returns 0 and writes
 * nothing. Choosing an action whose byte is 0 is the same as deciding
 * nothing -- the host keeps its own choice, because an illegal action is
 * not a move it can make.
 * gearbox:neural.decide "action_valid"
 * `(iii)i`
 */
GEARBOX_IMPORT("neural.decide", "action_valid")
uint32_t gearbox_action_valid(uint32_t module, char* buf, uint32_t cap);

/* How many parties sit in a country's legislature. 0 when the party rules
 * are off, which is the default -- so a mod must treat 0 as 'this world
 * has no party politics' rather than as an error.
 * gearbox:politics.read "country_party_count"
 * `(i)i`
 */
GEARBOX_IMPORT("politics.read", "country_party_count")
uint32_t gearbox_country_party_count(uint32_t country);

/* The party's name. Two-call sizing: call with cap 0 to learn the length,
 * allocate, call again. Returns the full length either way; the copy is
 * truncated to cap.
 * gearbox:politics.read "country_party_name"
 * `(iiii)i`
 */
GEARBOX_IMPORT("politics.read", "country_party_name")
uint32_t gearbox_country_party_name(uint32_t country, uint32_t index, char* buf, uint32_t cap);

/* The party's abbreviation, for a list that has to fit -- "SPD", "INC".
 * Same two-call sizing as country_party_name. May be empty.
 * gearbox:politics.read "country_party_short_name"
 * `(iiii)i`
 */
GEARBOX_IMPORT("politics.read", "country_party_short_name")
uint32_t gearbox_country_party_short_name(uint32_t country, uint32_t index, char* buf, uint32_t cap);

/* That party's share of the country, 0..1. The shares of one country's
 * parties are a partition and sum to 1, so they may be compared directly
 * but must never be added across countries.
 * gearbox:politics.read "country_party_support"
 * `(ii)F`
 */
GEARBOX_IMPORT("politics.read", "country_party_support")
double gearbox_country_party_support(uint32_t country, uint32_t index);

/* Where the party stands on the economic axis, -100 (planned) to 100
 * (market) -- the same axis and scale as country_compass_econ, so the
 * distance between a party and its government is meaningful.
 * gearbox:politics.read "country_party_compass_econ"
 * `(ii)F`
 */
GEARBOX_IMPORT("politics.read", "country_party_compass_econ")
double gearbox_country_party_compass_econ(uint32_t country, uint32_t index);

/* Where the party stands on the social axis, -100 (authoritarian) to 100
 * (libertarian). Same scale as country_compass_social.
 * gearbox:politics.read "country_party_compass_social"
 * `(ii)F`
 */
GEARBOX_IMPORT("politics.read", "country_party_compass_social")
double gearbox_country_party_compass_social(uint32_t country, uint32_t index);

/* 1 when this party is a matter of record for the scenario's date -- it
 * existed, under this name -- and 0 when the name was generated from its
 * stance. A mod that displays party names should say which it is showing:
 * "Workers' Party" is a description, "SPD" is a claim. See
 * data/parties.json.
 * gearbox:politics.read "country_party_is_historical"
 * `(ii)i`
 */
GEARBOX_IMPORT("politics.read", "country_party_is_historical")
uint32_t gearbox_country_party_is_historical(uint32_t country, uint32_t index);

/* The index of the party that governs, or -1 if none does. That party
 * pulls the government compass toward its own stance every turn it holds
 * power, which is why the two are on the same scale.
 * gearbox:politics.read "country_ruling_party"
 * `(i)i`
 */
GEARBOX_IMPORT("politics.read", "country_ruling_party")
uint32_t gearbox_country_ruling_party(uint32_t country);

/* Whether a country id names a country that exists. A mod holding an id
 * from its own storage, a save, or a previous turn has no other way to ask
 * before using it -- a country can be annexed between turns, and every
 * other accessor answers 0 or an empty string for a dead id, which is
 * indistinguishable from a live country with nothing in it.
 * gearbox:gamestate.read "country_exists"
 * `(i)i`
 */
GEARBOX_IMPORT("gamestate.read", "country_exists")
uint32_t gearbox_country_exists(gearbox_country country);

/* Whether a province id names a province that exists. Same reason as
 * country_exists: a stored id needs a validity check that is not 'iterate
 * every province and compare'.
 * gearbox:gamestate.read "province_exists"
 * `(i)i`
 */
GEARBOX_IMPORT("gamestate.read", "province_exists")
uint32_t gearbox_province_exists(gearbox_province province);

/* Resident memory the whole game is using, in bytes. 0 where the platform
 * does not report it -- Windows and the web build both return 0 today, and
 * 0 means UNKNOWN rather than 'no memory'.\n\nTHIS IS A FACT ABOUT THE
 * MACHINE, not about the game, which is why it needs its own capability.
 * Every other reading a mod can take is deliberately opaque about the
 * host.
 * gearbox:core.protected "process_bytes"
 * `()I`
 */
GEARBOX_IMPORT("core.protected", "process_bytes")
uint64_t gearbox_process_bytes(void);

/* How large the game's own executable is on disk, in bytes. 0 if it cannot
 * be determined. Useful to a mod that reports build size or checks it is
 * running against the build it expects; useless for anything else, which
 * is the point.
 * gearbox:core.protected "image_bytes"
 * `()I`
 */
GEARBOX_IMPORT("core.protected", "image_bytes")
uint64_t gearbox_image_bytes(void);

/* How many mods are INSTALLED, enabled or not. A compatibility checker
 * needs to see the mod it conflicts with even when that mod is switched
 * off, because switching it on is what breaks things.
 * gearbox:core.protected "mod_count"
 * `()i`
 */
GEARBOX_IMPORT("core.protected", "mod_count")
uint32_t gearbox_mod_count(void);

/* The installed mod's manifest id -- the stable one, safe to compare.
 * Two-call sizing: call with cap 0 to learn the length, allocate, call
 * again.
 * gearbox:core.protected "mod_id"
 * `(iii)i`
 */
GEARBOX_IMPORT("core.protected", "mod_id")
uint32_t gearbox_mod_id(uint32_t index, char* buf, uint32_t cap);

/* Its display name, which is for showing a player and NOT for matching on:
 * it is author-chosen, may be translated, and two mods may share one.
 * Match on mod_id.
 * gearbox:core.protected "mod_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("core.protected", "mod_name")
uint32_t gearbox_mod_name(uint32_t index, char* buf, uint32_t cap);

/* Declare a field on every country. mode 0 HOLLOW, 1 PERSIST; type 0
 * number, 1 text. PERSIST is written into the save and read back. HOLLOW
 * is not: the mod redeclares it on every load and fills it from whatever
 * it can recompute, which is right for a cache and wrong for anything a
 * player would be upset to lose. Redeclaring the same field identically
 * SUCCEEDS -- that is what a hollow field does on every load. Redeclaring
 * it with a different type fails, because the values already stored are of
 * the old one. Refused for an empty name, a name over 64 bytes, or one
 * containing anything but printable ASCII.
 * gearbox:country "field_add"
 * `(iiii)i`
 */
GEARBOX_IMPORT("country", "field_add")
uint32_t gearbox_field_add(const char* name, uint32_t name_len, uint32_t mode, uint32_t type);

/* Forget one of YOUR fields and every country's value for it. Returns
 * whether it existed. A mod cannot remove another mod's field: fields are
 * keyed by (mod, name), so two mods may both add a field called morale and
 * neither can see the other's.
 * gearbox:country "field_remove"
 * `(ii)i`
 */
GEARBOX_IMPORT("country", "field_remove")
uint32_t gearbox_field_remove(const char* name, uint32_t name_len);

/* Whether you have declared this field AND own it right now. False for a
 * field read back from a save whose mod is not loaded -- such a field is
 * inert, though its values are kept.
 * gearbox:country "field_has"
 * `(ii)i`
 */
GEARBOX_IMPORT("country", "field_has")
uint32_t gearbox_field_has(const char* name, uint32_t name_len);

/* How many fields YOU have declared. Not how many exist: another mod's
 * fields are not yours to enumerate.
 * gearbox:country "field_count"
 * `()i`
 */
GEARBOX_IMPORT("country", "field_count")
uint32_t gearbox_field_count(void);

/* The name of your field at index, sorted by name so the order does not
 * shift between runs. Two-call sizing.
 * gearbox:country "field_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("country", "field_name")
uint32_t gearbox_field_name(uint32_t index, char* buf, uint32_t cap);

/* Set a country's value for one of your NUMBER fields. Refused if the
 * field is text, was never declared, or belongs to a mod that is not
 * loaded.
 * gearbox:country "set_number"
 * `(iiid)i`
 */
GEARBOX_IMPORT("country", "set_number")
uint32_t gearbox_set_number(const char* name, uint32_t name_len, gearbox_country country, double value);

/* A country's value, or 0 when the field or the country has none. 0 is a
 * real value too, so a mod that needs to tell unset from zero should keep
 * its own sentinel.
 * gearbox:country "get_number"
 * `(iii)F`
 */
GEARBOX_IMPORT("country", "get_number")
double gearbox_get_number(const char* name, uint32_t name_len, gearbox_country country);

/* Set a country's value for one of your TEXT fields.
 * gearbox:country "set_text"
 * `(iiiii)i`
 */
GEARBOX_IMPORT("country", "set_text")
uint32_t gearbox_set_text(const char* name, uint32_t name_len, gearbox_country country, const char* value, uint32_t value_len);

/* A country's text value, or empty. Two-call sizing.
 * gearbox:country "get_text"
 * `(iiiii)i`
 */
GEARBOX_IMPORT("country", "get_text")
uint32_t gearbox_get_text(const char* name, uint32_t name_len, gearbox_country country, char* buf, uint32_t cap);

/* Claim a command name in the map script language. A script line beginning
 * with it is then handed to your mod_script_command export, whole. FIRST
 * COME. A script writes `reinforce FRA 3`, not a mod id and a colon, so
 * the name is global: the first mod to claim it keeps it and the second
 * gets false rather than a silent overwrite, which would make the meaning
 * of a line depend on load order. Re-claiming your own succeeds, because a
 * mod redeclares its commands on every load. The language's own keywords
 * are refused. A mod that could register `if` or `set` would take over
 * every script in the game -- including maps that never asked for it,
 * since scripts ship inside .odmap files and mods are enabled globally.
 * Names must be an identifier: a letter, then letters, digits or
 * underscores, up to 48 bytes.
 * gearbox:scripts "command_add"
 * `(ii)i`
 */
GEARBOX_IMPORT("scripts", "command_add")
uint32_t gearbox_command_add(const char* name, uint32_t name_len);

/* Give up one of your own commands. False if it was not yours -- a mod
 * cannot unregister another mod's.
 * gearbox:scripts "command_remove"
 * `(ii)i`
 */
GEARBOX_IMPORT("scripts", "command_remove")
uint32_t gearbox_command_remove(const char* name, uint32_t name_len);

/* How many commands YOU have claimed.
 * gearbox:scripts "command_count"
 * `()i`
 */
GEARBOX_IMPORT("scripts", "command_count")
uint32_t gearbox_command_count(void);

/* The name of your command at index, sorted. Two-call sizing.
 * gearbox:scripts "command_name"
 * `(iii)i`
 */
GEARBOX_IMPORT("scripts", "command_name")
uint32_t gearbox_command_name(uint32_t index, char* buf, uint32_t cap);

/* Inside mod_script_command: which of your commands the script ran. Empty
 * outside that call -- there is no command then, and reporting the last
 * one would be a stale answer that looks like a live one. Two-call sizing.
 * gearbox:scripts "command_text"
 * `(ii)i`
 */
GEARBOX_IMPORT("scripts", "command_text")
uint32_t gearbox_command_text(char* buf, uint32_t cap);

/* Inside mod_script_command: the rest of the script line, verbatim --
 * unparsed and untrimmed, because your command knows its own grammar and
 * the engine does not. Empty outside that call. Two-call sizing.
 * gearbox:scripts "command_args"
 * `(ii)i`
 */
GEARBOX_IMPORT("scripts", "command_args")
uint32_t gearbox_command_args(char* buf, uint32_t cap);

/* Tint a province on the map. rgba is 0xRRGGBBAA. AN ALPHA OF ZERO REMOVES
 * THE TINT. One call does set and clear, so a fading effect that paints
 * transparent every frame cannot grow the list forever -- which is what a
 * separate clear call invites. Returns false when you are already holding
 * the maximum (4096 tints per mod, which is every province on the largest
 * map twice over). A refusal rather than a slower game: a mod's mistake
 * should not be paid for in frame time by a player who cannot see why.
 * gearbox:render "province_tint"
 * `(ii)i`
 */
GEARBOX_IMPORT("render", "province_tint")
uint32_t gearbox_province_tint(gearbox_province province, uint32_t rgba);

/* Put a short label at a province. Empty text, or an alpha of zero,
 * removes it. Truncated at 48 characters and stripped of control
 * characters rather than refused: a label one character too long is a
 * cosmetic mistake, and failing the call would have an author debugging a
 * silent nothing instead of seeing a clipped word. 512 labels per mod.
 * gearbox:render "province_label"
 * `(iiii)i`
 */
GEARBOX_IMPORT("render", "province_label")
uint32_t gearbox_province_label(gearbox_province province, const char* text, uint32_t text_len, uint32_t rgba);

/* Drop every tint and label YOU have drawn. A mod cannot clear another
 * mod's -- and unloading a mod clears its own automatically, because a
 * mark left behind by a mod that is no longer running is indistinguishable
 * from the game being wrong.
 * gearbox:render "clear"
 * `()i`
 */
GEARBOX_IMPORT("render", "clear")
uint32_t gearbox_render_clear(void);

/* How many tints you are currently holding.
 * gearbox:render "tint_count"
 * `()i`
 */
GEARBOX_IMPORT("render", "tint_count")
uint32_t gearbox_tint_count(void);

/* How many labels you are currently holding.
 * gearbox:render "label_count"
 * `()i`
 */
GEARBOX_IMPORT("render", "label_count")
uint32_t gearbox_label_count(void);

/* Add or replace one entry in a catalogue. kind 0 doctrine, 1 research, 2
 * troop type, 3 artillery, 4 district law. mode 0 HOLLOW, 1 PERSIST. The
 * definition is the SAME JSON the game's own data file uses, and goes
 * through the same parser -- not a second reading of the same fields,
 * which is how 'it works from the file but not from the mod' is made. AI
 * VISIBILITY IS A FIELD IN THE JSON: "aiVisible": true. It defaults to
 * FALSE, because content the AI was never trained against should not start
 * appearing in its options. For RESEARCH it matters more than it looks --
 * the tree feeds the neural feature vector, so a visible node changes the
 * shape of the model's input and a model whose parent no longer matches is
 * silently re-initialised. PERSIST writes the definition into the save, so
 * a world played with your doctrine keeps knowing what that doctrine was
 * after your mod is uninstalled -- otherwise the country still holds the
 * id and nothing can say what it did. HOLLOW is redeclared every load. Ids
 * are GLOBAL within a catalogue, unlike country fields: a country holds a
 * doctrine by id and a save records it that way, so two meanings for one
 * id would make a save ambiguous. Another mod's id is refused. Lower-case
 * letters, digits, underscore and at most one colon, 64 bytes.
 * gearbox:content "add"
 * `(iiiiii)i`
 */
GEARBOX_IMPORT("content", "add")
uint32_t gearbox_content_add(uint32_t kind, const char* id, uint32_t id_len, const char* json, uint32_t json_len, uint32_t mode);

/* How many entries of this kind YOU have added.
 * gearbox:content "count"
 * `(i)i`
 */
GEARBOX_IMPORT("content", "count")
uint32_t gearbox_content_count(uint32_t kind);

/* The id of your entry at index within a kind, sorted. Two-call sizing.
 * gearbox:content "id_at"
 * `(iiii)i`
 */
GEARBOX_IMPORT("content", "id_at")
uint32_t gearbox_content_id_at(uint32_t kind, uint32_t index, char* buf, uint32_t cap);

/* Which mod owns an id in a catalogue, or empty if nobody does. Lets a mod
 * check whether the content it is about to add already exists -- including
 * content another mod added, which is the collision it cannot otherwise
 * see coming.
 * gearbox:content "owner_of"
 * `(iiiii)i`
 */
GEARBOX_IMPORT("content", "owner_of")
uint32_t gearbox_content_owner_of(uint32_t kind, const char* id, uint32_t id_len, char* buf, uint32_t cap);

/* Remove one of your own entries. False if it was not yours.
 * gearbox:content "remove"
 * `(iii)i`
 */
GEARBOX_IMPORT("content", "remove")
uint32_t gearbox_content_remove(uint32_t kind, const char* id, uint32_t id_len);

/* --------------------------------------------------- exports -- */

/* Called once when your mod is enabled, before anything else. Return 0 to
 * accept the load; non-zero refuses it and the value is shown to the user.
 * There is no autorun, so this runs every session the user enables you --
 * never assume prior state.
 * `()i`
 */
GEARBOX_EXPORT("mod_load")
int32_t mod_load(void);

/* Called when disabled, reloaded, or at shutdown. Release what you hold.
 * Your state does not survive a reload and there is no hook to serialise
 * it.
 * `()`
 */
GEARBOX_EXPORT("mod_unload")
void mod_unload(void);

/* Called before the host processes a turn. Only invoked if GameProcess is
 * granted.
 * `(i)`
 */
GEARBOX_EXPORT("mod_pre_turn")
void mod_pre_turn(uint32_t turn);

/* Called after the host processes a turn. Only invoked if GameProcess is
 * granted.
 * `(i)`
 */
GEARBOX_EXPORT("mod_post_turn")
void mod_post_turn(uint32_t turn);

/* Called once per frame per visible panel you registered. Never called
 * when headless. Re-issue all your draw calls every frame; the command
 * list is cleared between frames.
 * `(iii)`
 */
GEARBOX_EXPORT("mod_draw_panel")
void mod_draw_panel(gearbox_panel panel, uint32_t width, uint32_t height);

/* Choose this country's action for one of the AI's decision modules, in
 * place of the built-in AI. Called once per AI country per module per
 * turn, and only if Neural.Decide is granted. Read the position with
 * neural.features() and the legal moves with neural.decide.action_valid();
 * return an action index in [0, action_count(module)). Return
 * GEARBOX_INVALID to decide nothing this time, which is not a failure --
 * the built-in AI chooses instead, so a mod may answer only the turns it
 * has an opinion about. An out-of-range or illegal answer is treated the
 * same way. The host keeps the last word either way: whatever is returned
 * is still put through the same legality and execution path as its own
 * choice, so this changes WHICH legal move is made and never what a legal
 * move is.
 * `(ii)i`
 */
GEARBOX_EXPORT("mod_ai_choose")
uint32_t mod_ai_choose(uint32_t country, uint32_t module);

/* Called when a map script runs a command you claimed with command_add.
 * Read which one with scripts.command_text and its arguments with
 * scripts.command_args -- the rest of the line verbatim, unparsed and
 * untrimmed, because your command knows its own grammar and the engine
 * does not. Return 1 if you handled it; 0 reports "Unknown command" to the
 * script author, which is the right answer for arguments you cannot make
 * sense of.
 * `()i`
 */
GEARBOX_EXPORT("mod_script_command")
uint32_t mod_script_command(void);

#endif /* GEARBOX_GENERATED_H */
