/* GENERATED by tools/gen_bindings.py from sdk/abi.json. Do not edit.
 *
 * Included by gearbox.h, which carries the prose. Everything here is
 * mechanical: constants, the env struct layout, and the declarations.
 */

#ifndef GEARBOX_GENERATED_H
#define GEARBOX_GENERATED_H

/* ------------------------------------------------- constants -- */
#define GEARBOX_INVALID 0xFFFFFFFFu
#define GEARBOX_MAJOR 1
#define GEARBOX_MINOR 0

typedef enum {
    GEARBOX_LOG_TRACE  = 0,
    GEARBOX_LOG_INFO   = 1,
    GEARBOX_LOG_WARN   = 2,
    GEARBOX_LOG_ERROR  = 3
} gearbox_log_level;

/* Layout is ABI. Fields are only ever appended, never reordered or resized. Total size is 28 bytes on wasm32. */
typedef struct {
    uint32_t  size;   /* You write sizeof(gearbox_env_t) here before calling env */
    uint32_t  gearbox_major;
    uint32_t  gearbox_minor;
    uint32_t  host_version;   /* (major<<16)|(minor<<8)|patch */
    uint8_t   platform;   /* enum:platform */
    uint8_t   is_web;   /* 1 under Emscripten. Fuel is NOT enforced there. */
    uint8_t   is_headless;   /* 1 when there is no renderer. UI imports no-op. */
    uint8_t   reserved0;
    uint32_t  screen_w;   /* 0 when headless */
    uint32_t  screen_h;   /* 0 when headless */
} gearbox_env_t;
_Static_assert(sizeof(gearbox_env_t) == 28,
               "gearbox_env_t layout is ABI");

/* --------------------------------------------------- imports -- */

/* Write a line to the game log and the mod menu's log view. Messages
 * longer than 2048 bytes are truncated. An out-of-bounds (ptr,len) is
 * refused and logged as an error against your mod rather than read.
 * `(iii)`
 */
GEARBOX_IMPORT("core", "log")
void gearbox_log(gearbox_log_level level, const char* msg, uint32_t msg_len);

/* Fill a gearbox_env_t. Write your own sizeof into out->size FIRST; the
 * host writes at most that many bytes, so an older mod stays safe against
 * a newer host. If size is 0 or larger than the host's struct, the host
 * uses its own size.
 * `(i)`
 */
GEARBOX_IMPORT("core", "env")
void gearbox_env(gearbox_env_t* out);

/* Unrecoverable error. Traps out of the current call, disables the mod,
 * and shows the message to the user. Prefer returning an error from a hook
 * where you can.
 * `(ii)`
 */
GEARBOX_IMPORT("core", "abort")
void gearbox_abort(const char* msg, uint32_t msg_len) __attribute__((noreturn));

/* The instruction budget for the current hook, or 0xFFFFFFFFFFFFFFFF when
 * unmetered. This is the LIMIT, not a live countdown: it does not decrease
 * as you run. Use it to size your work up front and count your own
 * iterations.
 * `()I`
 */
GEARBOX_IMPORT("core", "fuel_budget")
uint64_t gearbox_fuel_budget(void);

/* The current turn. 0 when no world is loaded.
 * `()i`
 */
GEARBOX_IMPORT("gamestate.read", "turn_number")
uint32_t gearbox_turn_number(void);

/* How many countries exist. 0 when no world is loaded. Rebel factions are
 * not included.
 * `()i`
 */
GEARBOX_IMPORT("gamestate.read", "country_count")
uint32_t gearbox_country_count(void);

/* The country at index in [0, country_count). Returns GEARBOX_INVALID
 * (0xFFFFFFFF) if out of range. Ordering is stable within a turn but not
 * across turns.
 * `(i)i`
 */
GEARBOX_IMPORT("gamestate.read", "country_at")
gearbox_country gearbox_country_at(uint32_t index);

/* Two-call sizing. Writes at most cap bytes of UTF-8 and returns the FULL
 * length. Call with cap 0 to size, then again to fill. A return greater
 * than cap means truncation, not failure. Returns 0 for an unknown
 * country.
 * `(iii)i`
 */
GEARBOX_IMPORT("gamestate.read", "country_name")
uint32_t gearbox_country_name(gearbox_country country, char* buf, uint32_t cap);

/* Treasury balance. 0 for an unknown country.
 * `(i)F`
 */
GEARBOX_IMPORT("gamestate.read", "country_treasury")
double gearbox_country_treasury(gearbox_country country);

/* How many provinces the country owns. 0 for an unknown country.
 * `(i)i`
 */
GEARBOX_IMPORT("gamestate.read", "country_province_count")
uint32_t gearbox_country_province_count(gearbox_country country);

/* Population of a province. 0 for an unknown province.
 * `(i)I`
 */
GEARBOX_IMPORT("gamestate.read", "province_population")
int64_t gearbox_province_population(gearbox_province province);

/* Owning country, or GEARBOX_INVALID if unowned or unknown.
 * `(i)i`
 */
GEARBOX_IMPORT("gamestate.read", "province_owner")
gearbox_country gearbox_province_owner(gearbox_province province);

/* Register a panel and return its handle. Returns 0 (invalid) when
 * headless, when UI was revoked, or when you already hold 8 panels. Titles
 * are truncated to 64 bytes. Call this from mod_load, not from your draw
 * hook.
 * `(iiii)i`
 */
GEARBOX_IMPORT("ui", "panel_register")
gearbox_panel gearbox_panel_register(const char* title, uint32_t title_len, uint32_t min_w, uint32_t min_h);

/* Filled rectangle in panel-relative coordinates. Colour is 0xRRGGBBAA.
 * Coordinates outside the panel are clipped by the host; they cannot
 * escape it.
 * `(iiiiii)`
 */
GEARBOX_IMPORT("ui", "draw_rect")
void gearbox_draw_rect(gearbox_panel panel, int32_t x, int32_t y, int32_t w, int32_t h, uint32_t rgba);

/* UTF-8 text in panel-relative coordinates. Truncated to 512 bytes per
 * call.
 * `(iiiiii)`
 */
GEARBOX_IMPORT("ui", "draw_text")
void gearbox_draw_text(gearbox_panel panel, int32_t x, int32_t y, uint32_t rgba, const char* text, uint32_t text_len);

/* Immediate-mode button: draws it and returns 1 on the frame it is
 * clicked. One click activates one button -- the host consumes it, so
 * overlapping rects do not all fire. Label truncated to 64 bytes.
 * `(iiiiiii)i`
 */
GEARBOX_IMPORT("ui", "button")
uint32_t gearbox_button(gearbox_panel panel, int32_t x, int32_t y, int32_t w, int32_t h, const char* label, uint32_t label_len);

/* Byte size of one of your own data/ files, or 0 if there is no such
 * asset. Names are relative to data/ and use '/' separators:
 * data/flags/fr.png is "flags/fr.png".
 * `(ii)i`
 */
GEARBOX_IMPORT("assets", "size")
uint32_t gearbox_asset_size(const char* name, uint32_t name_len);

/* Two-call sizing, like country_name. Writes at most cap bytes and returns
 * the asset's full size. The name is looked up in your package's entry
 * list, never resolved as a filesystem path.
 * `(iiii)i`
 */
GEARBOX_IMPORT("assets", "read")
uint32_t gearbox_asset_read(const char* name, uint32_t name_len, void* buf, uint32_t cap);

/* Reads one of your own keys. Two-call sizing: returns the full value
 * length and writes at most cap bytes. Returns GEARBOX_INVALID if the key
 * is absent -- which is NOT the same as a zero-length value, so you can
 * tell 'never stored' from 'stored empty'. Values are arbitrary bytes, not
 * text.
 * `(iiii)i`
 */
GEARBOX_IMPORT("storage", "get")
uint32_t gearbox_get(const char* key, uint32_t key_len, char* buf, uint32_t cap);

/* Stores bytes under one of your own keys. Returns 1 on success, 0 if a
 * quota was exceeded (256 keys, 128-byte keys, 16 KiB per value, 64 KiB
 * total per mod) -- the reason is written to your log. Not written to disk
 * immediately: the store is flushed at turn boundaries and on unload,
 * because a mod may call this from a draw hook.
 * `(iiii)i`
 */
GEARBOX_IMPORT("storage", "set")
uint32_t gearbox_set(const char* key, uint32_t key_len, const char* value, uint32_t value_len);

/* Deletes one of your own keys. Returns 1 if it existed, 0 if it did not.
 * `(ii)i`
 */
GEARBOX_IMPORT("storage", "remove")
uint32_t gearbox_remove(const char* key, uint32_t key_len);

/* Width of the province map in pixels. 0 when no world is loaded.
 * `()i`
 */
GEARBOX_IMPORT("map", "width")
uint32_t gearbox_width(void);

/* Height of the province map in pixels. 0 when no world is loaded.
 * `()i`
 */
GEARBOX_IMPORT("map", "height")
uint32_t gearbox_height(void);

/* How many provinces the loaded map has. 0 when no world is loaded.
 * `()i`
 */
GEARBOX_IMPORT("map", "province_count")
uint32_t gearbox_province_count(void);

/* Province handle at an index in [0, province_count). Returns
 * GEARBOX_INVALID if out of range. The order is stable across runs, unlike
 * the game's internal storage, so an index is safe to remember within a
 * session.
 * `(i)i`
 */
GEARBOX_IMPORT("map", "province_at")
gearbox_province gearbox_province_at(uint32_t index);

/* The province's name. Two-call sizing: returns the full length and writes
 * at most cap bytes. Empty for an unknown province.
 * `(iii)i`
 */
GEARBOX_IMPORT("map", "province_name")
uint32_t gearbox_province_name(gearbox_province province, char* buf, uint32_t cap);

/* X pixel coordinate of the province's centre. 0 for an unknown province.
 * `(i)F`
 */
GEARBOX_IMPORT("map", "province_center_x")
double gearbox_province_center_x(gearbox_province province);

/* Y pixel coordinate of the province's centre. 0 for an unknown province.
 * `(i)F`
 */
GEARBOX_IMPORT("map", "province_center_y")
double gearbox_province_center_y(gearbox_province province);

/* 1 if the province is land, 0 if it is sea or unknown. Sampled at the
 * province centre.
 * `(i)i`
 */
GEARBOX_IMPORT("map", "province_is_land")
uint32_t gearbox_province_is_land(gearbox_province province);

/* How many provinces border this one. 0 for an unknown province.
 * `(i)i`
 */
GEARBOX_IMPORT("map", "province_neighbor_count")
uint32_t gearbox_province_neighbor_count(gearbox_province province);

/* The bordering province at an index in [0, province_neighbor_count).
 * GEARBOX_INVALID if out of range. Adjacency is computed once when the map
 * loads, so walking it is cheap.
 * `(ii)i`
 */
GEARBOX_IMPORT("map", "province_neighbor_at")
gearbox_province gearbox_province_neighbor_at(gearbox_province province, uint32_t index);

/* 1 if the two countries are at war. Relations are symmetric, so the
 * argument order does not matter. 0 for unknown countries or for a country
 * with itself.
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "at_war")
uint32_t gearbox_at_war(gearbox_country a, gearbox_country b);

/* 1 if the two countries are allied.
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "allied")
uint32_t gearbox_allied(gearbox_country a, gearbox_country b);

/* 1 if the two countries have a non-aggression pact.
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "non_aggression")
uint32_t gearbox_non_aggression(gearbox_country a, gearbox_country b);

/* 1 if the first country guarantees the second.
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "guaranteed")
uint32_t gearbox_guaranteed(gearbox_country a, gearbox_country b);

/* PROPOSES a declaration of war, and returns 1 only if the game accepted
 * it. It is routed through the same code path any other actor uses, so
 * guarantee chains and war consequences follow exactly as normal -- a mod
 * cannot produce a diplomatic state the game itself could not reach.
 * Refused (0) if either country is unknown, they are the same country, or
 * they are already at war. Either outcome is written to your mod log, so a
 * player can see after the fact that a mod started a war.
 * `(ii)i`
 */
GEARBOX_IMPORT("diplomacy", "propose_war")
uint32_t gearbox_propose_war(gearbox_country attacker, gearbox_country defender);

/* Sets a country's treasury outright. Returns 1 on success, 0 if the
 * country is unknown or the value is not finite and within +/-1e12 -- NaN
 * or infinity would silently poison every later calculation, so they are
 * refused rather than stored.
 * `(iF)i`
 */
GEARBOX_IMPORT("gamestate.write", "set_country_treasury")
uint32_t gearbox_set_country_treasury(gearbox_country country, double value);

/* Adds to a country's treasury. Usually what you want instead of set: it
 * composes with whatever the economy did this turn. Refused (0) if the
 * result would leave the sane range.
 * `(iF)i`
 */
GEARBOX_IMPORT("gamestate.write", "add_country_treasury")
uint32_t gearbox_add_country_treasury(gearbox_country country, double delta);

/* Transfers a province to another country. Routed through the same code
 * the game's own ceasefires use, so the province, the ownership lookup,
 * the per-pixel country map and both countries' pixel lists all stay
 * consistent -- and the previous owner's troops in that province are
 * disbanded, as they are for any other transfer. Returns 0 if either
 * handle is unknown or the country already owns it. Always written to your
 * mod log: territory changing hands is the most consequential thing a mod
 * can do.
 * `(ii)i`
 */
GEARBOX_IMPORT("gamestate.write", "set_province_owner")
uint32_t gearbox_set_province_owner(gearbox_province province, gearbox_country country);

/* How many floats are in the AI's feature vector. 0 when there is no AI or
 * no world.
 * `()i`
 */
GEARBOX_IMPORT("neural", "feature_count")
uint32_t gearbox_feature_count(void);

/* Copies the feature vector the AI would see for a country, as 32-bit
 * floats. Two-call sizing, but note cap counts FLOATS and the buffer must
 * therefore be cap*4 bytes. This is a snapshot: writing to your copy does
 * not affect the AI.
 * `(iii)i`
 */
GEARBOX_IMPORT("neural", "features")
uint32_t gearbox_features(gearbox_country country, char* buf, uint32_t cap);

/* How many reward channels the AI tracks (economy, politics, war, navy).
 * `()i`
 */
GEARBOX_IMPORT("neural", "reward_count")
uint32_t gearbox_reward_count(void);

/* The running mean reward for one channel, indexed in [0, reward_count). 0
 * if out of range. OBSERVE ONLY: this capability has no import that writes
 * to the model, the optimiser state or the reward history, which is
 * deliberate -- a trained model is hours of work and a mod that could
 * quietly retrain it is not something a user can meaningfully consent to.
 * `(i)F`
 */
GEARBOX_IMPORT("neural", "reward_mean")
double gearbox_reward_mean(uint32_t index);

/* Sets a province's population. Returns 0 if the province is unknown, the
 * value is negative, or it exceeds 100 billion. The game stores population
 * in two places -- a map and a dense array used by the population texture
 * -- and this updates both, which is why it exists as an import rather
 * than being something a mod could do by other means.
 * `(iI)i`
 */
GEARBOX_IMPORT("gamestate.write", "set_province_population")
uint32_t gearbox_set_province_population(gearbox_province province, int64_t value);

/* --------------------------------------------------- exports -- */

/* Called once when your mod is enabled, before anything else. Return 0 to
 * accept the load; non-zero refuses it and the value is shown to the user.
 * There is no autorun, so this runs every session the user enables you --
 * never assume prior state.
 * `()i`
 */
GEARBOX_EXPORT("mod_load")
int32_t mod_load(void);

/* Called when disabled, reloaded, or at shutdown. Release what you hold.
 * Your state does not survive a reload and there is no hook to serialise
 * it.
 * `()`
 */
GEARBOX_EXPORT("mod_unload")
void mod_unload(void);

/* Called before the host processes a turn. Only invoked if GameProcess is
 * granted.
 * `(i)`
 */
GEARBOX_EXPORT("mod_pre_turn")
void mod_pre_turn(uint32_t turn);

/* Called after the host processes a turn. Only invoked if GameProcess is
 * granted.
 * `(i)`
 */
GEARBOX_EXPORT("mod_post_turn")
void mod_post_turn(uint32_t turn);

/* Called once per frame per visible panel you registered. Never called
 * when headless. Re-issue all your draw calls every frame; the command
 * list is cleared between frames.
 * `(iii)`
 */
GEARBOX_EXPORT("mod_draw_panel")
void mod_draw_panel(gearbox_panel panel, uint32_t width, uint32_t height);

#endif /* GEARBOX_GENERATED_H */
