/* GENERATED by tools/gen_bindings.py from sdk/abi.json. Do not edit.
 *
 * The wire-level ABI, for reference and for anyone binding it
 * directly. Mods should use the `gearbox` global in gearbox.d.ts,
 * which is the ergonomic shape.
 */

declare namespace GearboxRaw {
  // Write a line to the game log and the mod menu's log view. Messages
  // longer than 2048 bytes are truncated. An out-of-bounds (ptr,len) is
  // refused and logged as an error against your mod rather than read.
  // `(iii)`
  function log(level: number, msg: number, msgLen: number): void;

  // Fill a gearbox_env_t. Write your own sizeof into out->size FIRST; the
  // host writes at most that many bytes, so an older mod stays safe against
  // a newer host. If size is 0 or larger than the host's struct, the host
  // uses its own size.
  // `(i)`
  function env(out: number): void;

  // Unrecoverable error. Traps out of the current call, disables the mod,
  // and shows the message to the user. Prefer returning an error from a hook
  // where you can.
  // `(ii)`
  function abort(msg: number, msgLen: number): void;

  // The instruction budget for the current hook, or 0xFFFFFFFFFFFFFFFF when
  // unmetered. This is the LIMIT, not a live countdown: it does not decrease
  // as you run. Use it to size your work up front and count your own
  // iterations.
  // `()I`
  function fuelBudget(): number;

  // The current turn. 0 when no world is loaded.
  // `()i`
  function turnNumber(): number;

  // How many countries exist. 0 when no world is loaded. Rebel factions are
  // not included.
  // `()i`
  function countryCount(): number;

  // The country at index in [0, country_count). Returns GEARBOX_INVALID
  // (0xFFFFFFFF) if out of range. Ordering is stable within a turn but not
  // across turns.
  // `(i)i`
  function countryAt(index: number): number;

  // Two-call sizing. Writes at most cap bytes of UTF-8 and returns the FULL
  // length. Call with cap 0 to size, then again to fill. A return greater
  // than cap means truncation, not failure. Returns 0 for an unknown
  // country.
  // `(iii)i`
  function countryName(country: number, buf: number, cap: number): number;

  // Treasury balance. 0 for an unknown country.
  // `(i)F`
  function countryTreasury(country: number): number;

  // How many provinces the country owns. 0 for an unknown country.
  // `(i)i`
  function countryProvinceCount(country: number): number;

  // Population of a province. 0 for an unknown province.
  // `(i)I`
  function provincePopulation(province: number): number;

  // Owning country, or GEARBOX_INVALID if unowned or unknown.
  // `(i)i`
  function provinceOwner(province: number): number;

  // Register a panel and return its handle. Returns 0 (invalid) when
  // headless, when UI was revoked, or when you already hold 8 panels. Titles
  // are truncated to 64 bytes. Call this from mod_load, not from your draw
  // hook.
  // `(iiii)i`
  function panelRegister(title: number, titleLen: number, minW: number, minH: number): number;

  // Filled rectangle in panel-relative coordinates. Colour is 0xRRGGBBAA.
  // Coordinates outside the panel are clipped by the host; they cannot
  // escape it.
  // `(iiiiii)`
  function drawRect(panel: number, x: number, y: number, w: number, h: number, rgba: number): void;

  // UTF-8 text in panel-relative coordinates. Truncated to 512 bytes per
  // call.
  // `(iiiiii)`
  function drawText(panel: number, x: number, y: number, rgba: number, text: number, textLen: number): void;

  // Immediate-mode button: draws it and returns 1 on the frame it is
  // clicked. One click activates one button -- the host consumes it, so
  // overlapping rects do not all fire. Label truncated to 64 bytes.
  // `(iiiiiii)i`
  function button(panel: number, x: number, y: number, w: number, h: number, label: number, labelLen: number): number;

  // Byte size of one of your own data/ files, or 0 if there is no such
  // asset. Names are relative to data/ and use '/' separators:
  // data/flags/fr.png is "flags/fr.png".
  // `(ii)i`
  function assetSize(name: number, nameLen: number): number;

  // Two-call sizing, like country_name. Writes at most cap bytes and returns
  // the asset's full size. The name is looked up in your package's entry
  // list, never resolved as a filesystem path.
  // `(iiii)i`
  function assetRead(name: number, nameLen: number, buf: number, cap: number): number;

  // Play a sound from your own mod's assets. `path` is relative to your mod
  // root; a path outside it is refused rather than resolved. Volume is 0..1
  // and is multiplied by the player's own effects setting, so a mod cannot
  // be louder than they allowed. Returns a handle, or 0 if it could not be
  // played.
  // `(iif)i`
  function play(path: number, pathLen: number, volume: number): number;

  // Stop a sound this mod started. A handle belonging to another mod, or one
  // that already finished, does nothing.
  // `(i)`
  function stop(handle: number): void;

  // Change the volume of a playing sound, 0..1, again scaled by the player's
  // setting.
  // `(if)`
  function setVolume(handle: number, volume: number): void;

  // Whether that handle is still making sound.
  // `(i)i`
  function isPlaying(handle: number): number;

  // Send a message to the same mod running on another peer. `peer` is a peer
  // id -- the value `recv` reported in `from_peer` -- and -1 broadcasts to
  // every other peer, the host included. There is no fixed id for the host:
  // a host that plays holds an ordinary seat, and a dedicated one holds
  // none. The host stamps your mod id on the message, so you cannot send as
  // another mod, and it never carries game traffic: orders, deltas and chat
  // do not travel here. Messages larger than 8192 bytes are refused. Returns
  // 0 if this is not a network game, or the message was too large.
  // `(iii)i`
  function send(peer: number, data: number, dataLen: number): number;

  // Take the next message addressed to this mod, writing it into `out` and
  // the sender's peer id into `from_peer`. Returns the number of bytes
  // written, or 0 when the queue is empty. A message longer than `out_len`
  // is truncated rather than dropped, so a small buffer loses data instead
  // of stalling the queue.
  // `(iii)i`
  function recv(out: number, outLen: number, fromPeer: number): number;

  // How many players this session has, a playing host included. 0 when this
  // is not a network game, which is how a mod tells the difference.
  // Spectators are not counted.
  // `()i`
  function peerCount(): number;

  // This machine's own peer id. 0 means this is not a network game, or this
  // is a dedicated host holding no seat -- a host that plays has an ordinary
  // peer id like anyone else, so do not use this to tell host from client.
  // `is_host` is that question.
  // `()i`
  function selfPeer(): number;

  // Whether this copy is the authoritative one. A mod that computes anything
  // the game depends on must do it here and send the result, not compute it
  // separately on each machine.
  // `()i`
  function isHost(): number;

  // Reads one of your own keys. Two-call sizing: returns the full value
  // length and writes at most cap bytes. Returns GEARBOX_INVALID if the key
  // is absent -- which is NOT the same as a zero-length value, so you can
  // tell 'never stored' from 'stored empty'. Values are arbitrary bytes, not
  // text.
  // `(iiii)i`
  function get(key: number, keyLen: number, buf: number, cap: number): number;

  // Stores bytes under one of your own keys. Returns 1 on success, 0 if a
  // quota was exceeded (256 keys, 128-byte keys, 16 KiB per value, 64 KiB
  // total per mod) -- the reason is written to your log. Not written to disk
  // immediately: the store is flushed at turn boundaries and on unload,
  // because a mod may call this from a draw hook.
  // `(iiii)i`
  function set(key: number, keyLen: number, value: number, valueLen: number): number;

  // Deletes one of your own keys. Returns 1 if it existed, 0 if it did not.
  // `(ii)i`
  function remove(key: number, keyLen: number): number;

  // Width of the province map in pixels. 0 when no world is loaded.
  // `()i`
  function width(): number;

  // Height of the province map in pixels. 0 when no world is loaded.
  // `()i`
  function height(): number;

  // How many provinces the loaded map has. 0 when no world is loaded.
  // `()i`
  function provinceCount(): number;

  // Province handle at an index in [0, province_count). Returns
  // GEARBOX_INVALID if out of range. The order is stable across runs, unlike
  // the game's internal storage, so an index is safe to remember within a
  // session.
  // `(i)i`
  function provinceAt(index: number): number;

  // The province's name. Two-call sizing: returns the full length and writes
  // at most cap bytes. Empty for an unknown province.
  // `(iii)i`
  function provinceName(province: number, buf: number, cap: number): number;

  // X pixel coordinate of the province's centre. 0 for an unknown province.
  // `(i)F`
  function provinceCenterX(province: number): number;

  // Y pixel coordinate of the province's centre. 0 for an unknown province.
  // `(i)F`
  function provinceCenterY(province: number): number;

  // 1 if the province is land, 0 if it is sea or unknown. Sampled at the
  // province centre.
  // `(i)i`
  function provinceIsLand(province: number): number;

  // How many provinces border this one. 0 for an unknown province.
  // `(i)i`
  function provinceNeighborCount(province: number): number;

  // The bordering province at an index in [0, province_neighbor_count).
  // GEARBOX_INVALID if out of range. Adjacency is computed once when the map
  // loads, so walking it is cheap.
  // `(ii)i`
  function provinceNeighborAt(province: number, index: number): number;

  // 1 if the two countries are at war. Relations are symmetric, so the
  // argument order does not matter. 0 for unknown countries or for a country
  // with itself.
  // `(ii)i`
  function atWar(a: number, b: number): number;

  // 1 if the two countries are allied.
  // `(ii)i`
  function allied(a: number, b: number): number;

  // 1 if the two countries have a non-aggression pact.
  // `(ii)i`
  function nonAggression(a: number, b: number): number;

  // 1 if the first country guarantees the second.
  // `(ii)i`
  function guaranteed(a: number, b: number): number;

  // PROPOSES a declaration of war, and returns 1 only if the game accepted
  // it. It is routed through the same code path any other actor uses, so
  // guarantee chains and war consequences follow exactly as normal -- a mod
  // cannot produce a diplomatic state the game itself could not reach.
  // Refused (0) if either country is unknown, they are the same country, or
  // they are already at war. Either outcome is written to your mod log, so a
  // player can see after the fact that a mod started a war.
  // `(ii)i`
  function proposeWar(attacker: number, defender: number): number;

  // Sets a country's treasury outright. Returns 1 on success, 0 if the
  // country is unknown or the value is not finite and within +/-1e12 -- NaN
  // or infinity would silently poison every later calculation, so they are
  // refused rather than stored.
  // `(iF)i`
  function setCountryTreasury(country: number, value: number): number;

  // Adds to a country's treasury. Usually what you want instead of set: it
  // composes with whatever the economy did this turn. Refused (0) if the
  // result would leave the sane range.
  // `(iF)i`
  function addCountryTreasury(country: number, delta: number): number;

  // Transfers a province to another country. Routed through the same code
  // the game's own ceasefires use, so the province, the ownership lookup,
  // the per-pixel country map and both countries' pixel lists all stay
  // consistent -- and the previous owner's troops in that province are
  // disbanded, as they are for any other transfer. Returns 0 if either
  // handle is unknown or the country already owns it. Always written to your
  // mod log: territory changing hands is the most consequential thing a mod
  // can do.
  // `(ii)i`
  function setProvinceOwner(province: number, country: number): number;

  // How many floats are in the AI's feature vector. 0 when there is no AI or
  // no world.
  // `()i`
  function featureCount(): number;

  // Copies the feature vector the AI would see for a country, as 32-bit
  // floats. Two-call sizing, but note cap counts FLOATS and the buffer must
  // therefore be cap*4 bytes. This is a snapshot: writing to your copy does
  // not affect the AI.
  // `(iii)i`
  function features(country: number, buf: number, cap: number): number;

  // How many reward channels the AI tracks (economy, politics, war, navy).
  // `()i`
  function rewardCount(): number;

  // The running mean reward for one channel, indexed in [0, reward_count). 0
  // if out of range. OBSERVE ONLY: this capability has no import that writes
  // to the model, the optimiser state or the reward history, which is
  // deliberate -- a trained model is hours of work and a mod that could
  // quietly retrain it is not something a user can meaningfully consent to.
  // `(i)F`
  function rewardMean(index: number): number;

  // Sets a province's population. Returns 0 if the province is unknown, the
  // value is negative, or it exceeds 100 billion. The game stores population
  // in two places -- a map and a dense array used by the population texture
  // -- and this updates both, which is why it exists as an import rather
  // than being something a mod could do by other means.
  // `(iI)i`
  function setProvincePopulation(province: number, value: number): number;

  // Queue a line from (x1,y1) to (x2,y2) in panel-relative pixels. Thickness
  // is clamped to 0.25..64. Clipped to your panel like every other command.
  // `(iiiiiFi)`
  function drawLine(panel: number, x1: number, y1: number, x2: number, y2: number, thickness: number, rgba: number): void;

  // Queue a filled circle centred at (cx,cy), panel-relative. Radius is
  // clamped to 0..4096.
  // `(iiiFi)`
  function drawCircle(panel: number, cx: number, cy: number, radius: number, rgba: number): void;

  // Queue an image from YOUR OWN package -- `name` is a path inside your
  // .odmod, resolved exactly as gearbox:assets/read resolves it, so you
  // cannot name a file on disk, a game asset, or another mod's art. Pass w
  // or h as 0 to use the image's own size. tint 0xFFFFFFFF draws it
  // unmodified. Decoded once and cached; a name that fails to decode draws
  // nothing and does not retry. PNG, JPG, BMP, TGA and GIF are recognised by
  // extension. This is the call that makes a real reskin possible.
  // `(iiiiiiii)`
  function drawImage(panel: number, x: number, y: number, w: number, h: number, name: number, nameLen: number, tint: number): void;

  // Like draw_text but with a type size, clamped to 6..96. draw_text remains
  // 14pt, unchanged, so v1.0 mods look exactly as they did.
  // `(iiiiiii)`
  function drawTextSized(panel: number, x: number, y: number, size: number, rgba: number, text: number, textLen: number): void;

  // Width in pixels of `text` at `size`, measured with the font the game
  // will actually draw. Centring, right-alignment and wrapping all need this
  // before the text is queued.
  // `(iii)i`
  function measureText(text: number, textLen: number, size: number): number;

  // The width the host assigned your panel this frame, in pixels. Lay out
  // against this rather than against min_w -- the host may have given you
  // more.
  // `(i)i`
  function panelWidth(panel: number): number;

  // The height the host assigned your panel this frame, in pixels.
  // `(i)i`
  function panelHeight(panel: number): number;

  // Show or hide one of your panels. A hidden panel is not drawn and
  // receives no input, but keeps its handle and its registration.
  // `(ii)`
  function panelSetVisible(panel: number, visible: number): void;

  // Cursor X, panel-relative, or 0 when the cursor is not over your panel.
  // You cannot observe the pointer outside your own box.
  // `(i)F`
  function mouseX(panel: number): number;

  // Cursor Y, panel-relative, or 0 when the cursor is not over your panel.
  // `(i)F`
  function mouseY(panel: number): number;

  // Whether the cursor is over your panel this frame.
  // `(i)i`
  function mouseInside(panel: number): number;

  // The PLAYER's accent colour as 0x00RRGGBB -- not another mod's override.
  // Build your palette around this and you harmonise with what they chose.
  // `()i`
  function themeAccent(): number;

  // Restyle the whole interface. The accent is read at over a hundred sites
  // -- every heading, highlight, selection and button -- so this is the
  // cheapest full reskin there is. It is NOT persisted: the game's settings
  // file keeps the player's own colour, and the override is dropped the
  // moment no mod is running, so it cannot outlive uninstalling you.
  // `(i)i`
  function setThemeAccent(rgb: number): number;

  // How many ships exist in the world, across all owners.
  // `()i`
  function shipCount(): number;

  // The ship id at `index` in 0..ship_count-1, or 0xFFFFFFFF past the end.
  // Ids are stable within a turn and not across turns -- do not store one.
  // `(i)i`
  function shipAt(index: number): number;

  // Whether a ship id is still live. Check this before acting on an id you
  // read earlier in the same turn; ships sink.
  // `(i)i`
  function shipExists(ship: number): number;

  // The country that owns a ship, or 0xFFFFFFFF for an id that does not
  // exist.
  // `(i)i`
  function shipOwner(ship: number): number;

  // The hull type as a lowercase string: "transport", "destroyer",
  // "battleship", "carrier", "submarine". Two-call sizing: call with cap 0
  // to learn the length, allocate, call again. Returns the full length
  // either way; the copy is truncated to cap.
  // `(iii)i`
  function shipType(ship: number, buf: number, cap: number): number;

  // Longitude in degrees, -180..180. Ships live in world coordinates, not
  // provinces.
  // `(i)F`
  function shipLon(ship: number): number;

  // Latitude in degrees, -90..90.
  // `(i)F`
  function shipLat(ship: number): number;

  // Hull integrity, 0..100. A ship at 0 has already sunk and will not
  // appear.
  // `(i)i`
  function shipHealth(ship: number): number;

  // Crew aboard. For a transport this includes the embarked army, which is
  // why a sunk transport costs so much more than its hull.
  // `(i)i`
  function shipCrew(ship: number): number;

  // How far this hull may move in one turn, in degrees. The resolver clamps
  // any order beyond it, so read this before ordering a move rather than
  // discovering the clamp afterwards.
  // `(i)F`
  function shipRange(ship: number): number;

  // How many distinct owners have troops in a province. Usually 1; more than
  // one means a contested or garrisoned province.
  // `(i)i`
  function armyStackCount(province: number): number;

  // The country owning stack `index` in a province, or 0xFFFFFFFF past the
  // end.
  // `(ii)i`
  function armyStackOwner(province: number, index: number): number;

  // How many troops are in that stack.
  // `(ii)I`
  function armyStackSize(province: number, index: number): number;

  // A country's total troops everywhere, which is the number its own army
  // screen shows.
  // `(i)I`
  function countryArmy(country: number): number;

  // Fortification level, 0..5. Multiplies the defender's strength.
  // `(i)i`
  function provinceFortification(province: number): number;

  // Port level, 0..3. 0 means no port, so no embarking and no ship repair.
  // `(i)i`
  function provincePortLevel(province: number): number;

  // Move `percent` (0..100) of the troops in `from` into the adjacent
  // province `to`. Into an enemy province this is an attack; into your own
  // or an ally's it is a transfer. Non-adjacent moves are refused. QUEUES AN
  // ORDER; it does not move anything. It lands in the same queue the
  // player's own click writes to and is validated by the same resolver at
  // end of turn, so a mod cannot teleport, cheat range, or attack across an
  // ocean. Returns 0 if the order is rejected outright.
  // `(iii)i`
  function orderArmyMove(from: number, to: number, percent: number): number;

  // Sail a ship toward (lon,lat). The resolver routes around land and clamps
  // to ship_range, so a destination on land or beyond range moves the ship
  // as far as it legally can rather than failing. QUEUES AN ORDER; it does
  // not move anything. It lands in the same queue the player's own click
  // writes to and is validated by the same resolver at end of turn, so a mod
  // cannot teleport, cheat range, or attack across an ocean. Returns 0 if
  // the order is rejected outright.
  // `(iFF)i`
  function orderShipMove(ship: number, lon: number, lat: number): number;

  // Attack another ship. Requires that you are at war with its owner and
  // that it is within range; both are checked by the resolver. QUEUES AN
  // ORDER; it does not move anything. It lands in the same queue the
  // player's own click writes to and is validated by the same resolver at
  // end of turn, so a mod cannot teleport, cheat range, or attack across an
  // ocean. Returns 0 if the order is rejected outright.
  // `(ii)i`
  function orderShipEngage(ship: number, target: number): number;

  // Bombard a coastal province. `ammo` names the shell type; pass an empty
  // string for the default. QUEUES AN ORDER; it does not move anything. It
  // lands in the same queue the player's own click writes to and is
  // validated by the same resolver at end of turn, so a mod cannot teleport,
  // cheat range, or attack across an ocean. Returns 0 if the order is
  // rejected outright.
  // `(iiii)i`
  function orderShipBombard(ship: number, province: number, ammo: number, ammoLen: number): number;

  // How many technologies exist in the tree.
  // `()i`
  function nodeCount(): number;

  // The stable string id of technology `index`, which is what
  // country_has_researched takes. Two-call sizing: call with cap 0 to learn
  // the length, allocate, call again. Returns the full length either way;
  // the copy is truncated to cap.
  // `(iii)i`
  function nodeId(index: number, buf: number, cap: number): number;

  // The technology's display name, which is localised and NOT stable --
  // never match on it. Two-call sizing: call with cap 0 to learn the length,
  // allocate, call again. Returns the full length either way; the copy is
  // truncated to cap.
  // `(iii)i`
  function nodeName(index: number, buf: number, cap: number): number;

  // Which branch of the tree it sits in. Two-call sizing: call with cap 0 to
  // learn the length, allocate, call again. Returns the full length either
  // way; the copy is truncated to cap.
  // `(iii)i`
  function nodeCategory(index: number, buf: number, cap: number): number;

  // Research points required.
  // `(i)i`
  function nodeCost(index: number): number;

  // Whether a country has completed a technology. Takes the id from node_id,
  // not the display name.
  // `(iii)i`
  function countryHasResearched(country: number, nodeId: number, nodeIdLen: number): number;

  // Research funding as A SHARE OF INCOME, 0..1 -- not an absolute sum. That
  // is how the game stores it and how its own economy screen presents it.
  // `(i)F`
  function countryFunding(country: number): number;

  // Set research funding as a share of income. Clamped to 0..1; a value in
  // 'points per turn' is not a quantity this game has.
  // `(iF)i`
  function setCountryFunding(country: number, share: number): number;

  // Economic axis of the political compass, -100 (planned) to 100 (market).
  // `(i)F`
  function countryCompassEcon(country: number): number;

  // Social axis, -100 (authoritarian) to 100 (libertarian).
  // `(i)F`
  function countryCompassSocial(country: number): number;

  // This province's chance of rebelling, as the game itself computes it.
  // `(i)F`
  function provinceUnrest(province: number): number;

  // How many policies exist.
  // `()i`
  function policyCount(): number;

  // The stable string id of policy `index`. Two-call sizing: call with cap 0
  // to learn the length, allocate, call again. Returns the full length
  // either way; the copy is truncated to cap.
  // `(iii)i`
  function policyId(index: number, buf: number, cap: number): number;

  // The policy's display name; localised, not stable, do not match on it.
  // Two-call sizing: call with cap 0 to learn the length, allocate, call
  // again. Returns the full length either way; the copy is truncated to cap.
  // `(iii)i`
  function policyName(index: number, buf: number, cap: number): number;

  // Whether a country currently has a policy active or implementing.
  // `(iii)i`
  function countryHasPolicy(country: number, policyId: number, policyIdLen: number): number;

  // How many named minority groups live in a province.
  // `(i)i`
  function provinceMinorityCount(province: number): number;

  // The minority's name. Two-call sizing: call with cap 0 to learn the
  // length, allocate, call again. Returns the full length either way; the
  // copy is truncated to cap.
  // `(iiii)i`
  function provinceMinorityName(province: number, index: number, buf: number, cap: number): number;

  // That minority's share of the province's population, 0..1.
  // `(ii)F`
  function provinceMinorityShare(province: number, index: number): number;

  // Enact or cancel a policy. GOES THROUGH THE GAME'S OWN enactPolicy, so
  // the cost, the prerequisites and the per-turn enactment cap all still
  // apply -- a country cannot end up running policies it could never have
  // afforded. Returns 1 if the policy is already in the requested state.
  // `(iiii)i`
  function setCountryPolicy(country: number, policyId: number, policyIdLen: number, enabled: number): number;

  // Income per turn before upkeep.
  // `(i)F`
  function countryIncomeGross(country: number): number;

  // Income per turn after army and navy upkeep. Negative means the treasury
  // is draining.
  // `(i)F`
  function countryIncomeNet(country: number): number;

  // What the standing army costs per turn.
  // `(i)F`
  function countryArmyUpkeep(country: number): number;

  // What the fleet costs per turn. Ships a country is not using still cost
  // this, which is what makes scrapping a real decision.
  // `(i)F`
  function countryNavyUpkeep(country: number): number;

  // Whether a country is currently bankrupt.
  // `(i)i`
  function countryIsBankrupt(country: number): number;

  // Industry level, 0..10.
  // `(i)i`
  function provinceIndustryLevel(province: number): number;

  // What this province's industry specialises in, or an empty string for
  // none. Two-call sizing: call with cap 0 to learn the length, allocate,
  // call again. Returns the full length either way; the copy is truncated to
  // cap.
  // `(iii)i`
  function provinceIndustrySpecialization(province: number, buf: number, cap: number): number;

  // How much of a resource a province holds, 0..100. `which` is one of
  // "oil", "gold", "rubber", "gemstones", "metal"; anything else reads 0.
  // `(iii)F`
  function provinceResource(province: number, which: number, whichLen: number): number;

  // Set a province's industry level, clamped to 0..10. This writes the built
  // level directly and does not charge for it -- it is a scenario-authoring
  // tool, not a build order.
  // `(ii)i`
  function setProvinceIndustryLevel(province: number, level: number): number;

  // Whether a province touches water. Ports, embarking and naval bombardment
  // all require it.
  // `(i)i`
  function provinceIsCoastal(province: number): number;

  // Whether a fleet could get from one point to another by sea, using the
  // game's own navigation grid. You cannot compute this from province
  // neighbours: those describe LAND adjacency.
  // `(FFFF)i`
  function seaRouteExists(fromLon: number, fromLat: number, toLon: number, toLat: number): number;

  // Whether a world coordinate is land. Ordering a ship onto land is not an
  // error -- the resolver clamps it -- but knowing first is cheaper.
  // `(FF)i`
  function pointIsLand(lon: number, lat: number): number;

  // Whether the map editor is open with a project loaded. EVERY OTHER CALL
  // IN THIS MODULE returns 0 or an empty string when this is 0, including
  // from inside a running game: the data behind them is an editor project,
  // and a game does not have one. Check this first.
  // `()i`
  function editorActive(): number;

  // How many provinces the open project has. Returns a neutral value unless
  // the map editor is open with a project loaded -- see mapeditor/active.
  // `()i`
  function editorProvinceCount(): number;

  // The province id at `index`, in ascending id order, or 0xFFFFFFFF past
  // the end. Returns a neutral value unless the map editor is open with a
  // project loaded -- see mapeditor/active.
  // `(i)i`
  function editorProvinceAt(index: number): number;

  // Population. Returns a neutral value unless the map editor is open with a
  // project loaded -- see mapeditor/active.
  // `(i)I`
  function editorProvincePopulation(province: number): number;

  // Industry level, 0..10. Returns a neutral value unless the map editor is
  // open with a project loaded -- see mapeditor/active.
  // `(i)i`
  function editorProvinceIndustryLevel(province: number): number;

  // Fortification, 0..5. Returns a neutral value unless the map editor is
  // open with a project loaded -- see mapeditor/active.
  // `(i)i`
  function editorProvinceFortification(province: number): number;

  // Port level, 0..3. Returns a neutral value unless the map editor is open
  // with a project loaded -- see mapeditor/active.
  // `(i)i`
  function editorProvincePortLevel(province: number): number;

  // Resource amount, 0..100. `which` is "oil", "gold", "rubber", "gemstones"
  // or "metal". Returns a neutral value unless the map editor is open with a
  // project loaded -- see mapeditor/active.
  // `(iii)F`
  function editorProvinceResource(province: number, which: number, whichLen: number): number;

  // Province economic compass, -100..100. Returns a neutral value unless the
  // map editor is open with a project loaded -- see mapeditor/active.
  // `(i)F`
  function editorProvinceCompassEcon(province: number): number;

  // Province social compass, -100..100. Returns a neutral value unless the
  // map editor is open with a project loaded -- see mapeditor/active.
  // `(i)F`
  function editorProvinceCompassSocial(province: number): number;

  // Set population, clamped to 0..2e9. Writes the SAME per-province data the
  // editor's own tools write, so it saves, exports and shows up in the
  // unsaved-changes prompt like any other edit. A province the project does
  // not have is refused rather than created: data without a shape on the
  // province bitmap exports a map the game cannot load.
  // `(iI)i`
  function editorSetProvincePopulation(province: number, value: number): number;

  // Set industry level, clamped to 0..10. Writes the SAME per-province data
  // the editor's own tools write, so it saves, exports and shows up in the
  // unsaved-changes prompt like any other edit. A province the project does
  // not have is refused rather than created: data without a shape on the
  // province bitmap exports a map the game cannot load.
  // `(ii)i`
  function editorSetProvinceIndustryLevel(province: number, level: number): number;

  // Set fortification, clamped to 0..5. Writes the SAME per-province data
  // the editor's own tools write, so it saves, exports and shows up in the
  // unsaved-changes prompt like any other edit. A province the project does
  // not have is refused rather than created: data without a shape on the
  // province bitmap exports a map the game cannot load.
  // `(ii)i`
  function editorSetProvinceFortification(province: number, level: number): number;

  // Set port level, clamped to 0..3. Writes the SAME per-province data the
  // editor's own tools write, so it saves, exports and shows up in the
  // unsaved-changes prompt like any other edit. A province the project does
  // not have is refused rather than created: data without a shape on the
  // province bitmap exports a map the game cannot load.
  // `(ii)i`
  function editorSetProvincePortLevel(province: number, level: number): number;

  // Set a resource amount, clamped to 0..100. An unrecognised name is
  // refused rather than silently mapped onto oil. Writes the SAME
  // per-province data the editor's own tools write, so it saves, exports and
  // shows up in the unsaved-changes prompt like any other edit. A province
  // the project does not have is refused rather than created: data without a
  // shape on the province bitmap exports a map the game cannot load.
  // `(iiiF)i`
  function editorSetProvinceResource(province: number, which: number, whichLen: number, amount: number): number;

  // Set both compass axes, each clamped to -100..100. Writes the SAME
  // per-province data the editor's own tools write, so it saves, exports and
  // shows up in the unsaved-changes prompt like any other edit. A province
  // the project does not have is refused rather than created: data without a
  // shape on the province bitmap exports a map the game cannot load.
  // `(iFF)i`
  function editorSetProvinceCompass(province: number, econ: number, social: number): number;

  // The project's map name. Two-call sizing: call with cap 0 to learn the
  // length, allocate, call again. Returns the full length either way; the
  // copy is truncated to cap.
  // `(ii)i`
  function editorMapName(buf: number, cap: number): number;

  // Rename the map. Refused if empty or over 96 bytes.
  // `(ii)i`
  function editorSetMapName(name: number, nameLen: number): number;

  // Set the author recorded in the exported .odmap. Up to 96 bytes.
  // `(ii)i`
  function editorSetAuthor(author: number, authorLen: number): number;

  // Set the licence recorded in the exported .odmap. Up to 96 bytes.
  // `(ii)i`
  function editorSetLicense(license: number, licenseLen: number): number;

  // The peer id at `index` in 0..peer_count-1, or 0xFFFFFFFF past the end.
  // This is the id net/send takes.
  // `(i)i`
  function peerAt(index: number): number;

  // That peer's display name -- deliberately NOT their account id or issuer.
  // A mod has no business correlating players across sessions. Two-call
  // sizing: call with cap 0 to learn the length, allocate, call again.
  // Returns the full length either way; the copy is truncated to cap.
  // `(iii)i`
  function peerName(index: number, buf: number, cap: number): number;

  // The largest payload net/send will accept. Chunk against this rather than
  // discovering the limit by having a message dropped.
  // `()i`
  function maxMessageBytes(): number;

  // How many decision modules the AI has. Each acts independently every
  // turn.
  // `()i`
  function moduleCount(): number;

  // The module's name: "economy", "politics", "war", "navy". Two-call
  // sizing: call with cap 0 to learn the length, allocate, call again.
  // Returns the full length either way; the copy is truncated to cap.
  // `(iii)i`
  function moduleName(module: number, buf: number, cap: number): number;

  // How many actions that module can choose between.
  // `(i)i`
  function actionCount(module: number): number;

  // The action's name, e.g. "reinforce", "embark", "propose_alliance". THE
  // FEATURE VECTOR IS DELIBERATELY NOT NAMED: its 143 slots are an
  // implementation detail that has changed before and will again, and a mod
  // written against those names would break silently. What the AI CAN DO is
  // stable enough to build an advisor or a decision log against. Two-call
  // sizing: call with cap 0 to learn the length, allocate, call again.
  // Returns the full length either way; the copy is truncated to cap.
  // `(iiii)i`
  function actionName(module: number, action: number, buf: number, cap: number): number;

  // Whether a country is played by the AI rather than by the local player.
  // `(i)i`
  function countryIsAi(country: number): number;

  // Gradient updates the loaded model has been through -- roughly, how much
  // training it has seen.
  // `()I`
  function updateCount(): number;

  // Whether an AI model is loaded at all. False in a game with no AI
  // players.
  // `()i`
  function modelLoaded(): number;

}
