#!/usr/bin/env python3
"""Check the doctrine data the game will actually read.

WHY THIS EXISTS

Three ways the doctrine data can be right in the repository and wrong in play,
all of them found the hard way:

1. data/policies.json is GENERATED by tools/gen_policies.py. Editing the JSON
   works until somebody regenerates, and then it silently reverts.

2. Every shipped .odmap carries its OWN copy of policies.json, and the
   archive's copy WINS over data/ (Game::loadPolicies). So a doctrine change
   that is not pushed into the archives changes nothing for any shipped map --
   the file in the repository and the file the game loads are different files.

3. Incompatibility is a property of a PAIR. A start position that hands a
   country both halves of a conflicting pair is unreachable in play but
   perfectly writable in the map data.

  python3 tools/check_policies.py
"""
import itertools
import json
import os
import re
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    failures = []

    def fail(msg):
        failures.append(msg)
        print("  FAIL " + msg)

    path = os.path.join(ROOT, "data", "policies.json")
    with open(path) as f:
        text = f.read()
    policies = json.loads(text)["policies"]
    name = {p["id"]: p["name"] for p in policies}
    conflict = {p["id"]: set(p.get("incompatible_with", [])) for p in policies}

    # 1. generated file vs its generator
    gen = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "gen_policies.py"),
                          "--check"], capture_output=True, text=True)
    if gen.returncode != 0:
        fail("data/policies.json has drifted from tools/gen_policies.py "
             "(run: python3 tools/gen_policies.py)")

    # A TRADEOFF LINE THE PANEL CANNOT TRANSLATE.
    #
    # data/policies.json states each effect as a finished English sentence with
    # a number in it. Game_Policies.cpp takes the number out, translates the
    # FORM, and puts the number back where the target language wants it -- so
    # the forms it knows are a closed list in the source, and an effect whose
    # form is not on that list falls back to English. Silently, in one panel,
    # in nineteen languages. This is the only thing that says so.
    forms_src = os.path.join(ROOT, "src", "Game_Policies.cpp")
    known = set()
    if os.path.exists(forms_src):
        src = open(forms_src, encoding="utf-8").read()
        m = re.search(r"kTradeoffForms\[\]\s*=\s*\{(.*?)\};", src, re.S)
        if m:
            known = set(re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1)))
    number = re.compile(r"[+-]?\d+(?:\.\d+)?%?")
    for p_ in policies:
        t = p_.get("tradeoffs", {})
        for line in list(t.get("gains", [])) + list(t.get("costs", [])):
            form = number.sub("%s", line, count=1)
            if form not in known:
                fail("%s: the effect %r has no form in kTradeoffForms "
                     "(add %r to src/Game_Policies.cpp, then re-run "
                     "tools/i18n_extract.py)" % (p_["id"], line, form))

    # 2. every conflict names a doctrine that exists, both ways round, once
    for pid, others in conflict.items():
        for other in others:
            if other not in name:
                fail("%s conflicts with '%s', which is not a doctrine" % (pid, other))
            elif pid not in conflict[other]:
                fail("%s names %s, but %s does not name it back -- the pair would "
                     "depend on adoption order" % (pid, other, other))
        if pid in others:
            fail("%s conflicts with itself" % pid)
        raw = policies[[p["id"] for p in policies].index(pid)].get("incompatible_with", [])
        if len(raw) != len(set(raw)):
            fail("%s lists a conflict twice" % pid)

    # 3. the archives carry the same doctrines the repository does
    maps = sorted(f for f in os.listdir(os.path.join(ROOT, "data", "STDmaps"))
                  if f.endswith(".odmap"))
    if not maps:
        fail("no .odmap files found -- this check would pass vacuously")
    for m in maps:
        archive = os.path.join(ROOT, "data", "STDmaps", m)
        with zipfile.ZipFile(archive) as z:
            names = z.namelist()
            if "policies.json" in names:
                if z.read("policies.json").decode("utf-8") != text:
                    fail("%s embeds a policies.json that differs from data/ "
                         "(run: python3 tools/update_odmap_member.py policies.json "
                         "data/policies.json data/STDmaps/*.odmap)" % m)
            # 4. no start position holds both halves of a conflicting pair
            if "starting_policies.json" not in names:
                continue
            start = json.loads(z.read("starting_policies.json")).get("starting_policies", {})
            for iso, held in start.items():
                for a, b in itertools.combinations(held, 2):
                    if b in conflict.get(a, ()):
                        fail("%s: %s starts with %s and %s, which conflict"
                             % (m, iso, name.get(a, a), name.get(b, b)))

    pairs = {tuple(sorted((a, b))) for a, v in conflict.items() for b in v}
    if failures:
        print("policy data: %d problem(s)" % len(failures))
        return 1
    print("policy data: %d doctrines, %d conflicting pairs, %d map(s) in sync"
          % (len(policies), len(pairs), len(maps)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
