#!/usr/bin/env python3
"""
Recolour countries that touch a neighbour they cannot be told apart from.

    python3 tools/fix_map_colors.py --check     # report, change nothing
    python3 tools/fix_map_colors.py             # rewrite every map
    python3 tools/fix_map_colors.py --map 1939  # just one

WHAT WAS WRONG

The country palette was generated by walking a small ring of hues, so it hands
out the same colour repeatedly -- Modern Day has 970 pairs of states closer
than dE 9, including exact duplicates. Most of those never matter, because the
two countries are on different continents. The ones that matter are the pairs
that share a border, because then the border stops existing to the eye and the
two countries read as one.

On The Gathering Storm that produced two visible bugs:

  * Germany #8bc64b sits against Lithuania #aec64b. Lithuania reads as a
    detached piece of Germany roughly where East Prussia should be, so the
    Reich appears to be the wrong shape.
  * Mongolia #c0392b sits against the Soviet Union #c63b3b and simply
    disappears into it, so its border looks like a dent in the USSR.

WHAT THIS DOES

Adjacency is measured from the province raster itself: two countries are
neighbours if any of their pixels touch. A pair is a problem if the CIE76
distance between their colours is under MIN_DE. For each problem pair the
SMALLER country (fewer provinces) is recoloured, so the big recognisable
powers keep the colour players know them by; the replacement is chosen to
maximise the distance to everything that country actually touches.

Nothing else is touched. A country with no colliding neighbour keeps its
colour exactly, which is why this does not restyle the game.
"""

import colorsys
import json
import math
import os
import shutil
import sys
import tempfile
import zipfile
import io

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAPS_DIR = os.path.join(ROOT, "data", "STDmaps")
MAPS = ["1914.odmap", "1918.odmap", "1939.odmap", "1945.odmap", "1962.odmap",
        "map.odmap"]

# Below this, two adjacent fills read as one country. Deliberately low: the
# job is to fix "I cannot see the border", not to enforce high contrast
# everywhere. Germany against Italy sits at dE 23 and is perfectly legible,
# so the bar has to be under that or this turns into a restyle.
MIN_DE = 16.0

# Neither ocean nor unclaimed land takes part.
SKIP = {"UNC", "BLC", "SPC"}


def to_lab(hexstr):
    r, g, b = (int(hexstr[i:i + 2], 16) / 255 for i in (1, 3, 5))

    def lin(u):
        return u / 12.92 if u <= 0.04045 else ((u + 0.055) / 1.055) ** 2.4

    r, g, b = lin(r), lin(g), lin(b)
    x = r * .4124 + g * .3576 + b * .1805
    y = r * .2126 + g * .7152 + b * .0722
    z = r * .0193 + g * .1192 + b * .9505

    def f(t):
        return t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116

    fx, fy, fz = f(x / .9505), f(y / 1.0), f(z / 1.089)
    return (116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz))


def de(a, b):
    return math.dist(to_lab(a), to_lab(b))


def palette():
    """Candidate fills in the same register as the ones already on the map --
    the shipped colours sit around saturation .62 and value .78, so staying
    there is what keeps a recoloured country looking native."""
    out = []
    for h in range(0, 360, 4):
        for s, v in ((0.62, 0.78), (0.50, 0.72), (0.70, 0.84), (0.40, 0.62)):
            r, g, b = colorsys.hsv_to_rgb(h / 360.0, s, v)
            out.append("#%02x%02x%02x" % (int(r * 255), int(g * 255), int(b * 255)))
    return out


CANDIDATES = palette()


def adjacency(zf, provinces):
    """Countries whose pixels touch, straight off the raster."""
    a = np.array(Image.open(io.BytesIO(zf.read("provinces.png"))).convert("RGB"))
    pid = ((a[:, :, 0].astype(np.int64) << 16)
           | (a[:, :, 1].astype(np.int64) << 8)
           | a[:, :, 2].astype(np.int64))
    owner = np.zeros(pid.max() + 1, dtype=np.int64)
    for k, v in provinces.items():
        if int(k) <= pid.max():
            owner[int(k)] = v["country_id"]
    cid = owner[pid]
    pairs = set()
    for x, y in ((1, 0), (0, 1)):
        left = cid[:cid.shape[0] - y, :cid.shape[1] - x]
        right = cid[y:, x:]
        m = (left != right) & (left != 0) & (right != 0)
        for u, v in np.unique(np.stack([left[m], right[m]], 1), axis=0):
            pairs.add((int(min(u, v)), int(max(u, v))))
    return pairs


def fix_map(name, check):
    path = os.path.join(MAPS_DIR, name)
    work = tempfile.mkdtemp(prefix="odmapcol_")
    try:
        with zipfile.ZipFile(path) as z:
            entries = z.namelist()
            z.extractall(work)
            countries = json.load(open(os.path.join(work, "countries.json")))
            provinces = json.load(open(os.path.join(work, "provinces.json")))
            pairs = adjacency(z, provinces)

        iso = {int(k): v["iso_a3"] for k, v in countries.items()}
        col = {int(k): v["color"] for k, v in countries.items()}
        size = {}
        for v in provinces.values():
            size[v["country_id"]] = size.get(v["country_id"], 0) + 1

        nbrs = {}
        for u, v in pairs:
            if iso.get(u) in SKIP or iso.get(v) in SKIP:
                continue
            nbrs.setdefault(u, set()).add(v)
            nbrs.setdefault(v, set()).add(u)

        bad = sorted(
            (round(de(col[u], col[v]), 1), u, v)
            for u, v in pairs
            if u in col and v in col
            and iso.get(u) not in SKIP and iso.get(v) not in SKIP
            and de(col[u], col[v]) < MIN_DE)

        print(f"\n=== {name} — {len(pairs)} borders, {len(bad)} too close to read ===")
        if not bad:
            print("   every land border is legible")
            return 0

        changed = {}
        for d, u, v in bad:
            # Re-measure: an earlier recolour may already have separated them.
            if de(col[u], col[v]) >= MIN_DE:
                continue
            # Move the smaller one, so the big powers keep their identity.
            move = u if size.get(u, 0) <= size.get(v, 0) else v
            others = [col[n] for n in nbrs.get(move, ()) if n in col and n != move]
            used = {c for k, c in col.items() if k != move and iso.get(k) not in SKIP}
            best, best_score = None, None
            for cand in CANDIDATES:
                # Must clear every neighbour, with a little headroom so one
                # fix does not land on top of the next country along.
                if others and min(de(cand, o) for o in others) < MIN_DE * 1.25:
                    continue
                # Do not mint a colour already in use somewhere else on this
                # map -- that just moves the collision rather than fixing it.
                if any(de(cand, u2) < 8.0 for u2 in used):
                    continue
                # Of the legal colours, take the one CLOSEST to where this
                # country started. The point is legibility, not a restyle.
                score = de(cand, col[move])
                if best_score is None or score < best_score:
                    best, best_score = cand, score
            if best is None:
                print(f"   WARN  no free colour for {iso[move]}", file=sys.stderr)
                continue
            print(f"   {iso[u]:4s} vs {iso[v]:4s}  dE {d:4.1f}  ->  "
                  f"recolour {iso[move]:4s} {col[move]} to {best}")
            col[move] = best
            changed[move] = best

        if check or not changed:
            return 0

        for k, v in countries.items():
            if int(k) in changed:
                v["color"] = changed[int(k)]
                fc = v.get("flag_censored")
                # The censored flag is the country colour as a plain field, so
                # it has to follow, or a recoloured country grows a flag that
                # no longer matches it.
                if isinstance(fc, dict) and fc.get("censored") and fc.get("colors"):
                    fc["colors"] = [changed[int(k)]]

        with open(os.path.join(work, "countries.json"), "w", encoding="utf-8") as f:
            json.dump(countries, f, separators=(",", ":"))
        tmp = path + ".tmp"
        with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as z:
            for e in entries:
                if e.endswith("/"):
                    z.writestr(e, b"")
                else:
                    z.write(os.path.join(work, e), e)
        os.replace(tmp, path)
        print(f"   recoloured {len(changed)} countries, wrote {name}")
        return 0
    finally:
        shutil.rmtree(work, ignore_errors=True)


def main():
    check = "--check" in sys.argv
    only = None
    if "--map" in sys.argv:
        only = sys.argv[sys.argv.index("--map") + 1]
        if not only.endswith(".odmap"):
            only += ".odmap"
    for name in MAPS:
        if only and name != only:
            continue
        fix_map(name, check)
    if check:
        print("\n--check: nothing written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
