#!/usr/bin/env python3
"""Generate the GitHub wiki from sdk/abi.json and docs/.

Wiki pages are generated, not hand-written, for the same reason
docs/gearbox-abi.md is: the ABI is verified against the host by
tests/mod_abi_test.cpp, so anything derived from sdk/abi.json is correct by
construction. A hand-maintained wiki drifts, and a wrong API reference is worse
than none.

    python3 tools/gen_wiki.py          # writes wiki/
    python3 tools/gen_wiki.py --check  # fails if wiki/ is stale (CI)
    python3 tools/publish_wiki.py      # pushes wiki/ to the Wiki tab

THESE PAGES ARE READ IN TWO PLACES, and that decides how they link to each
other. The Wiki tab serves them at /wiki/Page-Name, where a link must be
`[text](Page-Name)`. The Code tab serves the same files out of wiki/, where
that link 404s and only `[text](Page-Name.md)` resolves. Someone browsing the
repository is reading the wiki whether or not they meant to -- README.md
already sends them into wiki/AI-Architecture.md -- so the copy in the tree is
the one written to work, and publish_wiki.py drops the `.md` on the way out.

wiki/README.md exists for the same reason: GitHub renders a folder's README
when you open the folder, so the Code tab gets a front page instead of a bare
file listing. It is not published -- the wiki's front page is Home.
"""

import json
import os
import re
import sys

# EVERY open() IN THIS FILE NAMES ITS ENCODING, and that is not decoration.
# Python takes the platform's preferred encoding when none is given, which is
# UTF-8 on macOS and Linux and cp1252 on Windows. These pages carry em dashes
# and arrows, so on Windows the file read back decoded into different text from
# the one just generated, --check called every generated page stale, and the
# Windows CI job failed on every commit while the other four platforms passed.
# The passthrough pages hid it: they are read with the same wrong codec they are
# compared against, so they mangled identically and matched.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "wiki")

GENERATED = ("<!-- Generated by tools/gen_wiki.py from sdk/abi.json. "
             "Edits here are overwritten; change the source instead. -->\n")

# Every page, in reading order, with the one line each gets in an index.
#
# One list, because three things are generated from it -- the sidebar the wiki
# shows, the table on Home, and wiki/README.md -- and a page that reached only
# two of them is a page half the readers never find. AI-Architecture is
# hand-written and lives only in wiki/; it is listed here so the generator
# still links to it.
PAGES = [
    ("Gearbox", [
        ("Home", "What Gearbox is, and the two rules that catch everyone."),
        ("Getting-Started", "Install, build and load your first mod with one command."),
        ("API-Reference", "Every function, its exact signature and semantics."),
        ("Capability-Modules", "What each permission grants, and what it costs you in user trust."),
        ("Languages", "Which languages work today, with sizes."),
        ("Troubleshooting", "Every rejection message, its cause and its fix."),
    ]),
    ("Engine", [
        ("AI-Architecture", "How the AI decides, learns, and what the shipped model is."),
    ]),
]

TITLES = {"Home": "Home", "Getting-Started": "Getting Started",
          "API-Reference": "API Reference", "Capability-Modules": "Capability Modules",
          "Languages": "Languages", "Troubleshooting": "Troubleshooting",
          "AI-Architecture": "AI Architecture"}


def link(page, text=None):
    """A link to another wiki page, in the form that works in BOTH tabs.

    See the module docstring: the `.md` is what makes it resolve while browsing
    the repository, and publish_wiki.py removes it for the Wiki tab."""
    return f"[{text or TITLES[page]}]({page}.md)"


def unlink_md(body):
    """Turn the in-repo link form back into the wiki's own.

    Relative links only: anything with a scheme or a slash in it is a link out
    of the wiki and must survive untouched. Kept here rather than in
    publish_wiki.py so the two halves of the rule cannot drift apart."""
    return re.sub(r"\]\((?!https?://|/)([A-Za-z0-9._-]+)\.md(#[^)]*)?\)",
                  lambda m: f"]({m.group(1)}{m.group(2) or ''})", body)



def todo_paragraph(todo):
    """The 'not yet' note, or a positive statement when there is no 'not yet'.

    Written as a function because the honest text differs in kind, not just in
    contents: an empty list rendered into a sentence produced 'Not implemented
    yet: .', and the paragraph after it claimed a mod cannot change game state
    long after GameState.Write shipped."""
    if not todo:
        return ("\nEvery capability module is implemented. A mod can read the world, change it,\n"
                "draw panels, run code on turn boundaries, read the map, read and propose\n"
                "diplomacy, observe the AI, and persist its own state.\n")
    return ("\nNot implemented yet: " + ", ".join(todo) + ". A mod requesting one of these is\n"
            "**refused at load** with a diagnostic naming the import — deliberately, because\n"
            "running you without a capability you believe you hold would be worse.\n")

def wat_sig(e):
    params = " ".join(p["type"] for p in e["params"])
    r = e.get("result")
    s = f'(import "{e["module"]}" "{e["name"]}" (func'
    if params:
        s += f" (param {params})"
    if r:
        s += f' (result {r["type"]})'
    return s + "))"


def main(check=False):
    abi = json.load(open(os.path.join(ROOT, "sdk", "abi.json"), encoding="utf-8"))
    os.makedirs(OUT, exist_ok=True)
    pages = {}

    impl = {m["name"]: m for m in abi["modules"]}
    by_mod = {}
    for i in abi["imports"]:
        by_mod.setdefault(i["module"], []).append(i)

    # ---------------------------------------------------------------- Home ---
    nfun = len(abi["imports"])
    live = [m["name"] for m in abi["modules"] if m["implemented"]]
    todo = [m["name"] for m in abi["modules"] if not m["implemented"]]
    todo_para = todo_paragraph(todo)
    pages["Home.md"] = GENERATED + f"""# Gearbox — the OpenDoctrines mod API

Gearbox v{abi['gearbox']}. A mod is a WebAssembly module that imports
{nfun} host functions and exports up to {len(abi['exports'])} of its own. That is
the whole contract — there is no framework and no runtime to learn.

Mods are sandboxed with **no ambient authority**: no filesystem, no network, no
processes. You get exactly the capabilities you declared in `MANIFEST.json` and
the user granted, delivered as WASM imports. Anything else does not exist inside
your module.

## Start here

| | |
|---|---|
""" + "\n".join(f"| **{link(page)}** | {blurb} |"
                for page, blurb in dict(PAGES)["Gearbox"]
                if page != "Home") + f"""

The engine's own pages sit beside these: """ + ", ".join(
        link(page) for page, _ in dict(PAGES)["Engine"]) + f""".

## What a mod can do today

Working: **{', '.join(live)}**.
{todo_para}

## Two rules that catch everyone

1. **Mods load only from the mod menu.** Not from a save, a map, a CLI flag, or
   another mod. Nothing of yours exists until a user enables you there.
2. **Your state does not survive a reload, and there is no hook to save it.**
   `mod_load` runs fresh every time. Never assume you ran last turn.
"""

    # ------------------------------------------------------- API Reference ---
    p = [GENERATED, f"# API Reference — Gearbox v{abi['gearbox']}\n",
         "Generated from `sdk/abi.json`, which is checked against the host's own",
         "capability table by `tests/mod_abi_test.cpp`. If a language binding",
         "disagrees with this page, the binding is wrong.\n",
         "Strings are `(ptr, len)` pairs of UTF-8 bytes in your linear memory.",
         "They are **not** null-terminated, and the host never keeps a pointer",
         "into your memory after a call returns.\n",
         "## Index\n"]
    for mod, entries in by_mod.items():
        cap = entries[0].get("capability") or "Core"
        p.append(f"- **{cap}** (`{mod}`): " +
                 ", ".join(f"[{e['name']}](#{e['name'].replace('_','-')})" for e in entries))
    p.append("")
    for mod, entries in by_mod.items():
        cap = entries[0].get("capability") or "Core"
        p.append(f"## {cap}\n")
        p.append(f"Import module `{mod}`. " +
                 ("Always granted; cannot be revoked.\n" if cap == "Core"
                  else f"Requires the `{cap}` capability in your manifest.\n"))
        for e in entries:
            p.append(f"### {e['name']}\n")
            p.append("```wat\n" + wat_sig(e) + "\n```\n")
            if e["params"]:
                p.append("| Parameter | Type | |")
                p.append("|---|---|---|")
                for q in e["params"]:
                    role = q.get("role", "")
                    note = {"ptr": "pointer into your memory", "len": "byte length",
                            "color": "`0xRRGGBBAA`", "bool": "0 or 1"}.get(role, "")
                    if role.startswith("handle:"):
                        note = f"opaque {role.split(':')[1]} handle"
                    p.append(f"| `{q['name']}` | `{q['type']}` | {note} |")
                p.append("")
            r = e.get("result")
            p.append(f"**Returns:** " + (f"`{r['type']}`" if r else "nothing") +
                     ("  — does not return, traps your mod." if e.get("noreturn") else ""))
            p.append("")
            p.append(e["doc"] + "\n")

    p.append("## Exports\n")
    p.append("Functions **you** provide. Only `mod_load` is required; a missing")
    p.append("optional export is simply not called.\n")
    for e in abi["exports"]:
        params = " ".join(q["type"] for q in e["params"])
        r = e.get("result")
        sig = f'(func (export "{e["name"]}")'
        if params:
            sig += f" (param {params})"
        if r:
            sig += f' (result {r["type"]})'
        p.append(f"### {e['name']}\n")
        p.append("```wat\n" + sig + " ...)\n```\n")
        p.append(f"**Required:** {'yes' if e.get('required') else 'no'}. "
                 f"**Capability:** {e.get('capability') or 'none'}\n")
        p.append(e["doc"] + "\n")

    env = abi["env_struct"]
    p.append("## The env struct\n")
    p.append(f"`{env['size_bytes']}` bytes on wasm32. Layout is part of the ABI:")
    p.append("fields are only appended, never reordered. Write your own struct")
    p.append("size into `size` *before* calling `env` — the host writes at most")
    p.append("that many bytes, so an older mod is safe against a newer host.\n")
    p.append("| Offset | Field | Type | |")
    p.append("|---|---|---|---|")
    for f in env["fields"]:
        p.append(f"| {f['offset']} | `{f['name']}` | `{f['type']}` | {f.get('doc','')} |")
    p.append("")
    for name, vals in abi["enums"].items():
        p.append(f"**`{name}`** — " + ", ".join(f"`{k}`={v}" for k, v in vals.items()) + "\n")
    pages["API-Reference.md"] = "\n".join(p)

    # --------------------------------------------------- Capability Modules --
    p = [GENERATED, "# Capability Modules\n",
         "Permissions in the OS sense. A mod receives imports **only** for the",
         "modules it declared and the user granted; anything else is absent from",
         "its import object, so calling it is a link failure at load, not a",
         "runtime check that can be bypassed.\n",
         "Users can revoke individual modules per mod in the mod menu's",
         "**Advanced** panel — so **a mod must tolerate being granted less than",
         "it asked for**.\n",
         "| Module | Grants | Functions | Revocable | Status |",
         "|---|---|---|---|---|"]
    for m in abi["modules"]:
        fns = by_mod.get(m["import"], []) if m["import"] else []
        names = ", ".join(f"`{f['name']}`" for f in fns) or "—"
        p.append(f"| `{m['name']}` | {m['grants']} | {names} | "
                 f"{'yes' if m['revocable'] else '**no**'} | "
                 f"{'implemented' if m['implemented'] else '**not implemented**'} |")
    p.append("""
`GameProcess` grants no imports — it gates whether the host *calls* your
`mod_pre_turn` / `mod_post_turn` exports.

Deliberately absent: any filesystem, network, process, or clock-with-identity
capability. There is no module that grants them, so they cannot be requested.
WASI's `fd_*` and `path_*` imports are never linked into the runtime.

## Asking for less is worth something

Requesting `GameState.Write` when you only read is not neutral — users see the
list before granting, and are right to be suspicious. Declare the least you
need.

## Mods and AI Learning never coexist

The experimental `AI Learning` option mutates the trained model as you play.
A mod can change what the AI observes, so the two are mutually exclusive: you
will never observe a turn where both are active.
""")
    pages["Capability-Modules.md"] = "\n".join(p)

    # ------------------------------------------------------ Getting Started --
    pages["Getting-Started.md"] = GENERATED + """# Getting Started

## One command

```bash
tools/gearbox doctor          # what toolchains do you have?
tools/gearbox new my-mod      # scaffold a mod
tools/gearbox dev my-mod      # compile, verify, pack, and install it
```

`dev` is the one to remember. It builds, checks the module imports nothing
outside the ABI, packs the `.odmod`, and copies it into the game's mods folder —
so recompiling never means hunting for a directory and copying files by hand.

Then in the game: **Mod Menu → Reload modloader**. Mods never load any other
way, and never mid-game without a reload.

On Windows use `tools\\gearbox.ps1` (PowerShell), or the bash script under Git
Bash / WSL. Set `GEARBOX_MODS_DIR` if your install lives somewhere unusual.

## Installing toolchains

```bash
tools/sdk_toolchains.sh install     # Zig, TinyGo, wabt, Rust, AssemblyScript
tools/sdk_toolchains.sh clean       # remove all of it
```

Everything lands in `.toolchains/` inside the repo — not Homebrew, not your home
directory — so `clean` is an `rm -rf` that cannot break anything else. C and C++
need only a wasm32-capable clang; Apple's cannot target wasm32, but the one
inside Emscripten can.

## Your first mod, in full

```c
#include "gearbox.h"
#define S(lit) lit, (uint32_t)(sizeof(lit) - 1)

static gearbox_panel g_panel;

GEARBOX_EXPORT("mod_load")
int32_t mod_load(void) {
    gearbox_env_t env; env.size = sizeof env;
    gearbox_env(&env);
    if (env.is_headless) return 0;      /* training run: no renderer */
    g_panel = gearbox_panel_register(S("Hello"), 200, 100);
    return 0;                           /* non-zero refuses the load */
}

GEARBOX_EXPORT("mod_draw_panel")
void mod_draw_panel(gearbox_panel p, uint32_t w, uint32_t h) {
    (void)w; (void)h;
    gearbox_draw_text(p, 8, 8, 0xFFFFFFFFu, S("Hello, world"));
}
```

## Before you ship

```bash
build/odmod-check my-mod.odmod              # same checks the game runs
build/odmod-check my-mod.odmod --revoke UI  # rehearse a user saying no
```

The second one matters: a user can revoke any capability you asked for, and a
mod that traps because of it is a bug in the mod.

## Things that will bite you

- **There is no libc.** No `snprintf`, no allocator unless you write one.
  Formatting an integer is nine lines and every mod needs it.
- **Strings are `(ptr, len)`,** never null-terminated.
- **Two-call sizing.** `country_name` returns the *full* length and writes at
  most `cap`. A return greater than `cap` means truncation, not failure.
- **`is_headless` is real.** Self-play runs thousands of turns with no
  renderer.
- **Fuel is finite** on desktop — exceed `limits.fuelPerTurn` and you are
  terminated mid-call. On web it is **not enforced**, so bound your own loops.
- **Your state does not survive a reload.** `mod_load` always runs fresh.
"""

    # ------------------------------------------------------------ passthrough -
    for src, dst, title in [
        ("docs/gearbox-troubleshooting.md", "Troubleshooting.md", None),
        ("docs/gearbox-languages.md", "Languages.md", None),
    ]:
        path = os.path.join(ROOT, src)
        if not os.path.exists(path):
            continue
        body = open(path, encoding="utf-8").read()
        # Wiki pages have no docs/ or sdk/ directory next to them.
        body = body.replace("](modding.md)", "](https://github.com/Pr1nted/Open-Doctrines/blob/main/docs/modding.md)")
        body = body.replace("](gearbox-troubleshooting.md", "](Troubleshooting.md")
        # Same rewrite, and it was missing: Troubleshooting links to the
        # languages page by its docs/ filename, which is a page that exists in
        # neither tab. The link check below is what found it.
        body = body.replace("](gearbox-languages.md", "](Languages.md")
        # And the label with it, where the label was the filename. "See
        # gearbox-languages.md" names a file that exists in docs/ and in
        # neither tab; the page it became is called Languages.
        body = body.replace("[gearbox-languages.md](", "[Languages](")
        body = body.replace("[gearbox-troubleshooting.md](", "[Troubleshooting](")
        body = body.replace("](../sdk/", "](https://github.com/Pr1nted/Open-Doctrines/blob/main/sdk/")
        body = body.replace("](../docs/", "](https://github.com/Pr1nted/Open-Doctrines/blob/main/docs/")
        pages[dst] = GENERATED + body

    # ------------------------------------------------------------- sidebar ---
    # The wiki's own navigation. Only the Wiki tab renders _Sidebar; the Code
    # tab gets README.md below, which is why both are generated from PAGES
    # rather than written out twice.
    p = [GENERATED]
    for section, entries in PAGES:
        p.append(f"### {section}")
        p += [f"- {link(page)}" for page, _ in entries]
        p.append("")
    pages["_Sidebar.md"] = "\n".join(p)

    # -------------------------------------------------- the Code tab's front --
    # GitHub renders this when you open wiki/ in the file browser, which is the
    # other half of "the wiki is readable in both tabs": without it the folder
    # is a list of filenames with no order and no explanation, and _Sidebar --
    # the thing that would have explained the order -- is invisible there.
    p = [GENERATED, "# OpenDoctrines wiki\n",
         "The source of the [Wiki tab](https://github.com/Pr1nted/Open-Doctrines/wiki),",
         "kept in the repository so it can be read, searched, diffed and reviewed",
         "here as well — the same pages, one commit history, no second place to",
         "keep in step.\n",
         "Most of it is generated from `sdk/abi.json` by `tools/gen_wiki.py`, which",
         "is what makes the API reference correct rather than merely current:",
         "`tests/mod_abi_test.cpp` checks that file against the host. Edit the",
         "source, not the page.\n"]
    for section, entries in PAGES:
        p.append(f"## {section}\n")
        for page, blurb in entries:
            p.append(f"- **{link(page)}** — {blurb}")
        p.append("")
    p.append("`_Sidebar.md` is the Wiki tab's navigation and has no effect here.\n")
    pages["README.md"] = "\n".join(p)

    if check:
        stale = []
        for name, body in pages.items():
            want = body if body.endswith("\n") else body + "\n"
            path = os.path.join(OUT, name)
            have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if have != want:
                stale.append(name + (" (missing)" if have is None else ""))
        if stale:
            print("wiki/ is stale, regenerate with tools/gen_wiki.py:")
            for name in stale:
                print(f"  {name}")
            return 1

        # Every page on disk, not only the generated ones -- AI-Architecture is
        # hand-written, and a link is exactly the kind of thing that rots there.
        #
        # A broken link is broken in BOTH tabs: the Code tab 404s on the file,
        # and publish_wiki.py's rewrite turns `Missing.md` into `Missing`, which
        # the wiki serves as an invitation to create the page. That is how
        # Troubleshooting came to link to `gearbox-languages.md` -- a docs/
        # filename that is not a page anywhere.
        broken = []
        for name in sorted(os.listdir(OUT)):
            if not name.endswith(".md"):
                continue
            for target in re.findall(r"\]\((?!https?://|/|#)([^)\s#]+)",
                                     open(os.path.join(OUT, name), encoding="utf-8").read()):
                if not os.path.exists(os.path.join(OUT, target)):
                    broken.append(f"{name} -> {target}")
        if broken:
            print("wiki/ has links to pages that do not exist:")
            for b in broken:
                print(f"  {b}")
            return 1

        print(f"wiki/ is up to date ({len(pages)} generated pages, links resolve)")
        return 0

    for name, body in pages.items():
        with open(os.path.join(OUT, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(body if body.endswith("\n") else body + "\n")
        print(f"  {name}  ({len(body.splitlines())} lines)")

    print(f"\nwrote {len(pages)} pages to {os.path.relpath(OUT, ROOT)}/")
    print("\nTo publish to the Wiki tab:")
    print("  python3 tools/publish_wiki.py")
    return 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv[1:]))
