#!/usr/bin/env python3
"""Generate the raw import layer of every SDK from sdk/abi.json.

    python3 tools/gen_bindings.py            # write the generated files
    python3 tools/gen_bindings.py --check    # fail if any is out of date

WHY

Adding one function to the ABI used to mean hand-editing ten bindings, each
declaring the same wire signature a different way, with nothing but a text lint
to catch a transposed argument. That is a bad trade at three languages and an
untenable one at thirteen.

Every binding here already has the same two layers, whether or not it says so:

    raw        the imports exactly as the host declares them. Mechanical, and
               derivable in full from abi.json -- this is what gets generated.
    ergonomic  two-call sizing collapsed into a string, INVALID turned into the
               language's own absent value, button returning a bool. Deliberate
               per-language design, hand-written, and it should stay that way:
               it is why these read as native rather than as generated stubs.

sdk/rust already split exactly this way (ffi.rs vs lib.rs) before any of this
existed; the generator just makes every language do it.

THE CHAIN

    host capability table  <--(ModAbiTest)-->  sdk/abi.json  --(this)--> bindings
                                                     |
                                                     +--(gen_abi_docs.py)--> docs

So the host, the docs and every binding are all pinned to one file, and
--check in tests/run_all.sh fails the build if a generated file was edited by
hand or left stale.

WHAT THIS DOES NOT DO

It does not verify that a binding's ergonomic layer is correct. Nothing textual
can. That is what the abi-conformance example and ModExamplesTest are for: they
run every import in every language and compare the output byte for byte.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ABI = os.path.join(ROOT, "sdk", "abi.json")

BANNER = "GENERATED by tools/gen_bindings.py from sdk/abi.json. Do not edit."


# --------------------------------------------------------------- helpers ----

def load():
    with open(ABI) as f:
        abi = json.load(f)
    # WasiStub is not part of any language binding: those imports come from an
    # interpreter's own libc, and a Rust or Zig binding declaring fd_write
    # would be wrong. See the same carve-out in check_bindings.py.
    imports = [i for i in abi["imports"] if i.get("capability") != "WasiStub"]
    return abi, imports


def camel(snake):
    head, *rest = snake.split("_")
    return head + "".join(w.capitalize() for w in rest)


def is_out_buffer(par):
    return par.get("role") == "ptr" and par.get("dir") == "out"


def binding_name(imp):
    """The name an SDK should expose. Usually the wire name, but abi.json can
    override it: gearbox:assets "size" and "read" are far too generic once
    lifted out of their module into a binding's namespace."""
    return imp.get("binding_name", imp["name"])


def is_signed(spec):
    """wasm's i32 says nothing about signedness; the binding must. Drawing
    coordinates are signed -- a panel-relative x of -4 legitimately means
    "start just off the left edge" -- while counts, lengths and handles are
    not. abi.json marks the exceptions."""
    if spec.get("signed"):
        return True
    if spec.get("unsigned"):
        return False
    return False


def num_kind(spec):
    """"i32" | "u32" | "i64" | "u64" | "f32" | "f64" for one param or result.

    wasm's own types carry no signedness, so it comes from abi.json: drawing
    coordinates are signed, counts and handles are not, and fuel_budget is an
    unsigned 64-bit whose maximum is the "unmetered" sentinel. Every emitter
    goes through this, so no two languages can disagree about a parameter."""
    ty = spec["type"]
    if ty in ("f32", "f64"):
        return ty
    if ty == "i64":
        return "u64" if spec.get("unsigned") else "i64"
    return "i32" if spec.get("signed") else "u32"


def doc_lines(imp):
    """The doc comment, wrapped, with the wire signature appended so a reader
    can always see what actually crosses the boundary."""
    text = (imp.get("doc") or "").strip()
    words, line, out = text.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > 72:
            out.append(line); line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    out.append(f"`{imp['signature']}`")
    return out


# ------------------------------------------------------------- emitters ----
# Each returns (relative path, file contents). Types are the wire types from
# abi.json, never a language's own -- widening or narrowing belongs in the
# ergonomic layer where it can be documented.

def emit_rust(abi, imports):
    T = {"i32": "i32", "u32": "u32", "i64": "i64", "u64": "u64",
         "f64": "f64", "f32": "f32"}
    out = [f"// {BANNER}", "//",
           "// Raw imports only; the safe wrappers are in lib.rs.", ""]
    by_mod = {}
    for imp in imports:
        by_mod.setdefault(imp["module"], []).append(imp)
    for module, group in by_mod.items():
        out.append(f'#[link(wasm_import_module = "{module}")]')
        out.append("extern \"C\" {")
        for imp in group:
            for d in doc_lines(imp):
                out.append(f"    /// {d}")
            args = []
            for p in imp["params"]:
                ty = T[num_kind(p)]
                if p.get("role") == "ptr":
                    ty = "*mut u8" if is_out_buffer(p) else "*const u8"
                args.append(f'{p["name"]}: {ty}')
            res = imp.get("result")
            ret = f' -> {T[num_kind(res)]}' if res else ""
            out.append(f'    pub fn {binding_name(imp)}({", ".join(args)}){ret};')
            out.append("")
        out.append("}")
        out.append("")
    return "src/ffi_generated.rs", "\n".join(out)


def emit_zig(abi, imports):
    T = {"i32": "i32", "u32": "u32", "i64": "i64", "u64": "u64",
         "f64": "f64", "f32": "f32"}
    out = [f"// {BANNER}", "//",
           "// Raw imports only; the ergonomic wrappers are in gearbox.zig.", ""]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"/// {d}")
        args = []
        for p in imp["params"]:
            ty = T[num_kind(p)]
            if p.get("role") == "ptr":
                ty = "?[*]u8" if is_out_buffer(p) else "?[*]const u8"
            args.append(f'{p["name"]}: {ty}')
        res = imp.get("result")
        # noreturn is load-bearing in Zig, not decoration: it lets the compiler
        # see that control does not come back from abort.
        ret = T[num_kind(res)] if res else ("noreturn" if imp.get("noreturn") else "void")
        out.append(f'pub extern "{imp["module"]}" fn {binding_name(imp)}'
                   f'({", ".join(args)}) {ret};')
        out.append("")
    return "raw_generated.zig", "\n".join(out)


def emit_go(abi, imports):
    T = {"i32": "int32", "u32": "uint32", "i64": "int64", "u64": "uint64",
         "f64": "float64", "f32": "float32"}
    out = [f"// {BANNER}", "//",
           "// Raw imports only; the ergonomic wrappers are in gearbox.go.", "",
           "package gearbox", "", 'import "unsafe"', "",
           "var _ = unsafe.Pointer(nil) // keep the import when no ptr is used",
           ""]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"// {d}")
        args = []
        for p in imp["params"]:
            ty = "unsafe.Pointer" if p.get("role") == "ptr" else T[num_kind(p)]
            args.append(f'{p["name"]} {ty}')
        res = imp.get("result")
        ret = f' {T[num_kind(res)]}' if res else ""
        out.append(f'//go:wasmimport {imp["module"]} {imp["name"]}')
        out.append(f'func raw{camel(binding_name(imp))[0].upper() + camel(binding_name(imp))[1:]}'
                   f'({", ".join(args)}){ret}')
        out.append("")
    return "raw_generated.go", "\n".join(out)


def emit_assemblyscript(abi, imports):
    T = {"i32": "i32", "u32": "u32", "i64": "i64", "u64": "u64",
         "f64": "f64", "f32": "f32"}
    out = [f"// {BANNER}", "//",
           "// Raw imports only; the ergonomic wrappers are in gearbox.ts.", ""]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"// {d}")
        args = []
        for p in imp["params"]:
            ty = "usize" if p.get("role") == "ptr" else T[num_kind(p)]
            args.append(f'{p["name"]}: {ty}')
        res = imp.get("result")
        ret = T[num_kind(res)] if res else "void"
        out.append(f'@external("{imp["module"]}", "{imp["name"]}")')
        # _camelCase, matching the convention gearbox.ts already uses for its
        # raw layer, so the ergonomic wrappers need no rewriting.
        out.append(f'export declare function _{camel(binding_name(imp))}'
                   f'({", ".join(args)}): {ret};')
        out.append("")
    return "assembly/raw_generated.ts", "\n".join(out)


def emit_java(abi, imports):
    T = {"i32": "int", "i64": "long", "f64": "double", "f32": "float"}
    out = [f"/* {BANNER}", " *",
           " * Raw imports only. The ergonomic wrappers, the UTF-8 codec and the",
           " * capability notes are in Gearbox.java.", " */", "",
           "package org.opendoctrines.gearbox;", "",
           "import org.teavm.interop.Import;", "",
           "public final class GearboxRaw {", "    private GearboxRaw() { }", ""]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"    /** {d} */" if len(doc_lines(imp)) == 1 else f"    // {d}")
        args = []
        for p in imp["params"]:
            # Pointers are int offsets into linear memory; see Address.ofData.
            ty = "int" if p.get("role") == "ptr" else T.get(p["type"], p["type"])
            args.append(f'{ty} {camel(p["name"])}')
        res = imp.get("result")
        ret = T.get(res["type"], res["type"]) if res else "void"
        out.append(f'    @Import(module = "{imp["module"]}", name = "{imp["name"]}")')
        out.append(f'    public static native {ret} {camel(binding_name(imp))}'
                   f'({", ".join(args)});')
        out.append("")
    out.append("}")
    return "gearbox/src/main/java/org/opendoctrines/gearbox/GearboxRaw.java", "\n".join(out)


def emit_typescript(abi, imports):
    """Declarations for the raw layer. The script-facing `gearbox` object is
    declared by hand in types/gearbox.d.ts, because its shape is the ergonomic
    one and deliberately differs from the wire signatures."""
    T = {"i32": "number", "i64": "number", "f64": "number", "f32": "number"}
    out = [f"/* {BANNER}", " *",
           " * The wire-level ABI, for reference and for anyone binding it",
           " * directly. Mods should use the `gearbox` global in gearbox.d.ts,",
           " * which is the ergonomic shape.", " */", "",
           "declare namespace GearboxRaw {"]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"  // {d}")
        args = ", ".join(f'{camel(p["name"])}: {T.get(p["type"], "number")}'
                         for p in imp["params"])
        res = imp.get("result")
        ret = T.get(res["type"], "number") if res else "void"
        out.append(f'  function {camel(binding_name(imp))}({args}): {ret};')
        out.append("")
    out.append("}")
    return "types/raw_generated.d.ts", "\n".join(out)


def c_type(spec, is_param, imp):
    """C type for one param or result. Handles keep their typedefs, and
    signedness comes from abi.json rather than from the wasm type, which does
    not carry it."""
    T = {"i32": "uint32_t", "i64": "int64_t", "f64": "double", "f32": "float"}
    role = spec.get("role", "")
    if role.startswith("handle:"):
        return "gearbox_" + role.split(":", 1)[1]
    if role == "enum:log_level":
        return "gearbox_log_level"
    if is_param and role == "ptr":
        if spec.get("struct"):
            return f"{spec['struct']}*"
        if is_out_buffer(spec):
            # An asset is arbitrary bytes; a name is text.
            return "void*" if imp.get("module") == "gearbox:assets" else "char*"
        return "const char*"
    if spec["type"] == "i32":
        return "int32_t" if spec.get("signed") else "uint32_t"
    if spec["type"] == "i64":
        return "uint64_t" if spec.get("unsigned") else "int64_t"
    return T.get(spec["type"], spec["type"])


def emit_c(abi, imports):
    """Declarations for sdk/gearbox.h, which #includes this.

    gearbox.h stays hand-written because it is the contract document and most
    of its value is the prose. What lives here is everything mechanical: the
    constants, the log-level enum, the env struct (whose layout is ABI and must
    not drift), the 18 imports and the 5 exports.

    C++, Lua, JavaScript and Python all reach the ABI through gearbox.h, so
    generating this one file gives five SDKs their raw layer from abi.json.
    """
    T = {"i32": "uint32_t", "i64": "int64_t", "f64": "double", "f32": "float"}
    ST = {"u32": "uint32_t", "u8": "uint8_t", "i32": "int32_t"}

    out = [f"/* {BANNER}", " *",
           " * Included by gearbox.h, which carries the prose. Everything here is",
           " * mechanical: constants, the env struct layout, and the declarations.",
           " */", "",
           "#ifndef GEARBOX_GENERATED_H", "#define GEARBOX_GENERATED_H", ""]

    out.append("/* ------------------------------------------------- constants -- */")
    for k, v in abi["constants"].items():
        out.append(f"#define {k} {v}{'u' if str(v).startswith('0x') else ''}")
    out.append("")

    # enums are plain {NAME: value} maps in abi.json.
    items = list(abi["enums"]["log_level"].items())
    out.append("typedef enum {")
    for i, (name, val) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        out.append(f"    GEARBOX_LOG_{name.upper():<6} = {val}{comma}")
    out += ["} gearbox_log_level;", ""]

    es = abi["env_struct"]
    out.append(f"/* {es.get('$comment','')} */")
    out.append("typedef struct {")
    for f in es["fields"]:
        c = ST.get(f["type"], f["type"])
        out.append(f"    {c:<9} {f['name']};"
                   + (f"   /* {f['doc']} */" if f.get("doc") else ""))
    out += [f"}} gearbox_env_t;",
            f"_Static_assert(sizeof(gearbox_env_t) == {es['size_bytes']},",
            '               "gearbox_env_t layout is ABI");', ""]

    out.append("/* --------------------------------------------------- imports -- */")
    for imp in imports:
        out.append("")
        for i, d in enumerate(doc_lines(imp)):
            out.append(f"/* {d}" if i == 0 else f" * {d}")
        out.append(" */")
        mod = imp["module"].split(":", 1)[1]
        args = [f'{c_type(p, True, imp)} {p["name"]}' for p in imp["params"]]
        res = imp.get("result")
        ret = c_type(res, False, imp) if res else "void"
        attr = ' __attribute__((noreturn))' if imp.get("noreturn") else ""
        out.append(f'GEARBOX_IMPORT("{mod}", "{imp["name"]}")')
        out.append(f'{ret} gearbox_{binding_name(imp)}({", ".join(args) or "void"}){attr};')

    out += ["", "/* --------------------------------------------------- exports -- */"]
    for exp in abi["exports"]:
        out.append("")
        for i, d in enumerate(doc_lines(exp)):
            out.append(f"/* {d}" if i == 0 else f" * {d}")
        out.append(" */")
        args = ", ".join(f'{c_type(p, True, exp)} {p["name"]}'
                         for p in exp.get("params", [])) or "void"
        res = exp.get("result")
        ret = c_type(res, False, exp) if res else "void"
        out.append(f'GEARBOX_EXPORT("{exp["name"]}")')
        out.append(f'{ret} {exp["name"]}({args});')

    out += ["", "#endif /* GEARBOX_GENERATED_H */"]
    return "gearbox_generated.h", "\n".join(out)


EMITTERS = [
    ("sdk",                emit_c),
    ("sdk/rust",           emit_rust),
    ("sdk/zig",            emit_zig),
    ("sdk/go",             emit_go),
    ("sdk/assemblyscript", emit_assemblyscript),
    ("sdk/java",           emit_java),
    ("sdk/js",             emit_typescript),
]


def main():
    check = "--check" in sys.argv
    abi, imports = load()

    stale, written = [], 0
    for base, emit in EMITTERS:
        rel, body = emit(abi, imports)
        path = os.path.join(ROOT, base, rel)
        if not body.endswith("\n"):
            body += "\n"

        current = None
        if os.path.exists(path):
            with open(path) as f:
                current = f.read()

        if check:
            if current != body:
                stale.append(os.path.join(base, rel))
            continue

        if current == body:
            print(f"  unchanged  {base}/{rel}")
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(body)
        print(f"  wrote      {base}/{rel}")
        written += 1

    if check:
        if stale:
            print("These generated bindings are out of date with sdk/abi.json:")
            for s in stale:
                print(f"    {s}")
            print("\nRun: python3 tools/gen_bindings.py")
            return 1
        print(f"ok    {len(EMITTERS)} generated binding(s) match sdk/abi.json")
        return 0

    print(f"\n{len(imports)} imports -> {len(EMITTERS)} bindings ({written} changed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
