#!/usr/bin/env python3
"""
Generate NOTICE.md and data/credits.txt from tools/provenance.json.

Only the third-party half of credits.txt is generated; the hand-written head
above the marker is preserved.

WHY GENERATED

Attribution rots. data/credits.txt listed Natural Earth and GREG and nothing
else, while map.odmap was shipping data derived from USGS, NGA, the World Bank
and ACOR — one of which (World Bank, CC BY 4.0) *requires* the attribution that
was missing. Hand-maintained credits fall behind the pipeline every time, and
you only find out when someone with standing to complain notices.

So it works the way sdk/abi.json already works for the mod ABI: one machine-
readable table, everything else generated from it, and `--check` in the test
suite fails the moment the generated files stop matching. Adding a dataset to
the pipeline without adding it here breaks the build, which is the point.

    python3 tools/gen_notices.py            # write
    python3 tools/gen_notices.py --check    # fail if stale

CREDITS FORMAT (parsed by Game::loadCredits, src/Game_Menus.cpp:225)
    @text   section heading        -text   a name/line
    $text   small print            ---     divider
    blank   spacer
The hand-written top of credits.txt is preserved; only the block below the
generated marker is rewritten.
"""

import json
import os
import sys

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(TOOLS_DIR)
PROVENANCE = os.path.join(TOOLS_DIR, "provenance.json")
NOTICE_MD = os.path.join(PROJECT_ROOT, "NOTICE.md")
CREDITS_TXT = os.path.join(PROJECT_ROOT, "data", "credits.txt")

# Everything from this line down in credits.txt is ours to rewrite. Anything
# above it is hand-written and left alone.
MARKER = "$--- generated from tools/provenance.json — do not edit below ---"


def load():
    with open(PROVENANCE, encoding="utf-8") as f:
        doc = json.load(f)
    if doc.get("schema") != 1:
        raise SystemExit(f"{PROVENANCE}: unsupported schema {doc.get('schema')!r}")
    return doc


def render_notice(doc):
    L = [
        "# Third-party notices",
        "",
        "Generated by `tools/gen_notices.py` from `tools/provenance.json`.",
        "Do not edit by hand — edit the table and regenerate.",
        "",
        "OpenDoctrines itself is under the OpenDoctrines Non-Commercial License",
        "(see [LICENSE](LICENSE)). The components below are under their own terms,",
        "and those terms govern those components.",
        "",
        "## Data",
        "",
    ]
    for d in doc["data"]:
        L += [
            f"### {d['name']}",
            "",
            f"- **Used for:** {d['what']}",
            f"- **Licence:** {d['license']}",
            f"- **Source:** <{d['url']}>",
            f"- **Consumed by:** `{d['used_by']}`",
        ]
        if d.get("attribution"):
            L.append(f"- **Required attribution:** {d['attribution_text']}")
        if d.get("license_file"):
            L.append(f"- **Full terms:** `data/licenses/{d['license_file']}`")
        L.append("")

    if doc.get("removed_data"):
        L += [
            "## Data deliberately not used",
            "",
            "Recorded because the absence is a decision, not an oversight, and",
            "because the next person to look for a world ethnic dataset will find",
            "the same one and wonder why it is not here.",
            "",
        ]
        for d in doc["removed_data"]:
            L += [
                f"### {d['name']} — removed {d['removed']}",
                "",
                f"- **Was used for:** {d['was']}",
                f"- **Why it went:** {d['why']}",
                f"- **Replaced by:** {d['replaced_by']}",
                "",
            ]

    L += ["## Libraries", "", "| Component | Version | Licence | Used for |", "|---|---|---|---|"]
    for lib in doc["libraries"]:
        L.append(f"| [{lib['name']}]({lib['url']}) | {lib['version']} | "
                 f"{lib['license']} | {lib['what']} |")
    L += ["", "## Fonts", ""]
    for f in doc["fonts"]:
        L += [f"### {f['name']}", "",
              f"- **File:** `{f['file']}`",
              f"- **Licence:** {f['license']}",
              f"- **Source:** <{f['url']}>",
              f"- **Notes:** {f['what']}",
              ""]
    L += ["## Artwork", ""]
    for a in doc["art"]:
        L += [f"- **{a['name']}** — {a['what']}. {a['license']}. "
              f"{a.get('note', '')} <{a['url']}>", ""]
    return "\n".join(L).rstrip() + "\n"


def render_credits_block(doc):
    """The generated tail of credits.txt, in the in-game credits format."""
    L = [MARKER, "", "@Map & World Data", "---"]
    for d in doc["data"]:
        L.append(f"- {d['name']} ({d['license']})")
    L += ["@"]

    attributed = [d for d in doc["data"] if d.get("attribution")]
    if attributed:
        L += ["@Required Attribution", "---"]
        for d in attributed:
            L.append(f"$ {d['attribution_text']}")
        L += ["@"]

    L += ["@Libraries", "---"]
    for lib in doc["libraries"]:
        L.append(f"- {lib['name']} ({lib['license']})")
    L += ["@"]

    L += ["@Fonts", "---"]
    for f in doc["fonts"]:
        L.append(f"- {f['name']} ({f['license']})")
    L += ["@"]

    L += ["@Artwork", "---"]
    for a in doc["art"]:
        L.append(f"- {a['name']} ({a['license']})")
    L += ["@", "",
          "$Full third-party notices: NOTICE.md",
          "$Per-flag licences: data/licenses/FLAGS.md"]
    return "\n".join(L) + "\n"


def compose_credits(doc):
    """Hand-written head + generated tail."""
    try:
        with open(CREDITS_TXT, encoding="utf-8") as f:
            existing = f.read()
    except FileNotFoundError:
        existing = ""
    head = existing.split(MARKER)[0].rstrip("\n")
    if not head:
        head = "@OpenDoctrines - Grand Strategy Game Engine\n---\n@Lead programmer\n---\n- Pr1nted\n@"
    return head + "\n\n" + render_credits_block(doc)


def write_or_check(path, content, check, stale):
    try:
        with open(path, encoding="utf-8") as f:
            current = f.read()
    except FileNotFoundError:
        current = None
    if current == content:
        return
    if check:
        stale.append(path)
        return
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path, PROJECT_ROOT)}")


def main(argv):
    check = "--check" in argv
    doc = load()

    stale = []
    write_or_check(NOTICE_MD, render_notice(doc), check, stale)
    write_or_check(CREDITS_TXT, compose_credits(doc), check, stale)

    if check:
        if stale:
            for p in stale:
                print(f"STALE {os.path.relpath(p, PROJECT_ROOT)}")
            print("run: python3 tools/gen_notices.py")
            return 1
        n = (len(doc["data"]) + len(doc["libraries"])
             + len(doc["fonts"]) + len(doc["art"]))
        print(f"notices: up to date ({n} components)")
        return 0

    print(f"Generated from {len(doc['data'])} datasets, {len(doc['libraries'])} libraries, "
          f"{len(doc['fonts'])} fonts, {len(doc['art'])} art sources.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
