#!/usr/bin/env python3
"""Generate the raw import layer of every SDK from sdk/abi.json.

    python3 tools/gen_bindings.py            # write the generated files
    python3 tools/gen_bindings.py --check    # fail if any is out of date

WHY

Adding one function to the ABI used to mean hand-editing ten bindings, each
declaring the same wire signature a different way, with nothing but a text lint
to catch a transposed argument. That is a bad trade at three languages and an
untenable one at thirteen.

Every binding here already has the same two layers, whether or not it says so:

    raw        the imports exactly as the host declares them. Mechanical, and
               derivable in full from abi.json -- this is what gets generated.
    ergonomic  two-call sizing collapsed into a string, INVALID turned into the
               language's own absent value, button returning a bool. Deliberate
               per-language design, hand-written, and it should stay that way:
               it is why these read as native rather than as generated stubs.

sdk/rust already split exactly this way (ffi.rs vs lib.rs) before any of this
existed; the generator just makes every language do it.

THE CHAIN

    host capability table  <--(ModAbiTest)-->  sdk/abi.json  --(this)--> bindings
                                                     |
                                                     +--(gen_abi_docs.py)--> docs

So the host, the docs and every binding are all pinned to one file, and
--check in tests/run_all.sh fails the build if a generated file was edited by
hand or left stale.

WHAT THIS DOES NOT DO

It does not verify that a binding's ergonomic layer is correct. Nothing textual
can. That is what the abi-conformance example and ModExamplesTest are for: they
run every import in every language and compare the output byte for byte.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ABI = os.path.join(ROOT, "sdk", "abi.json")

BANNER = "GENERATED by tools/gen_bindings.py from sdk/abi.json. Do not edit."


# --------------------------------------------------------------- helpers ----

def load():
    with open(ABI) as f:
        abi = json.load(f)
    # WasiStub is not part of any language binding: those imports come from an
    # interpreter's own libc, and a Rust or Zig binding declaring fd_write
    # would be wrong. See the same carve-out in check_bindings.py.
    imports = [i for i in abi["imports"] if i.get("capability") != "WasiStub"]
    return abi, imports


def camel(snake):
    head, *rest = snake.split("_")
    return head + "".join(w.capitalize() for w in rest)


def is_out_buffer(par):
    return par.get("role") == "ptr" and par.get("dir") == "out"


def binding_name(imp):
    """The name an SDK should expose. Usually the wire name, but abi.json can
    override it: gearbox:assets "size" and "read" are far too generic once
    lifted out of their module into a binding's namespace."""
    return imp.get("binding_name", imp["name"])


def is_signed(spec):
    """wasm's i32 says nothing about signedness; the binding must. Drawing
    coordinates are signed -- a panel-relative x of -4 legitimately means
    "start just off the left edge" -- while counts, lengths and handles are
    not. abi.json marks the exceptions."""
    if spec.get("signed"):
        return True
    if spec.get("unsigned"):
        return False
    return False


def num_kind(spec):
    """"i32" | "u32" | "i64" | "u64" | "f32" | "f64" for one param or result.

    wasm's own types carry no signedness, so it comes from abi.json: drawing
    coordinates are signed, counts and handles are not, and fuel_budget is an
    unsigned 64-bit whose maximum is the "unmetered" sentinel. Every emitter
    goes through this, so no two languages can disagree about a parameter."""
    ty = spec["type"]
    if ty in ("f32", "f64"):
        return ty
    if ty == "i64":
        return "u64" if spec.get("unsigned") else "i64"
    return "i32" if spec.get("signed") else "u32"


def doc_lines(imp):
    """The doc comment, wrapped, with the wire signature appended so a reader
    can always see what actually crosses the boundary."""
    text = (imp.get("doc") or "").strip()
    words, line, out = text.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > 72:
            out.append(line); line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    out.append(f"`{imp['signature']}`")
    return out


# ------------------------------------------------------------- emitters ----
# Each returns (relative path, file contents). Types are the wire types from
# abi.json, never a language's own -- widening or narrowing belongs in the
# ergonomic layer where it can be documented.

def emit_rust(abi, imports):
    T = {"i32": "i32", "u32": "u32", "i64": "i64", "u64": "u64",
         "f64": "f64", "f32": "f32"}
    out = [f"// {BANNER}", "//",
           "// Raw imports only; the safe wrappers are in lib.rs.", ""]
    by_mod = {}
    for imp in imports:
        by_mod.setdefault(imp["module"], []).append(imp)
    for module, group in by_mod.items():
        out.append(f'#[link(wasm_import_module = "{module}")]')
        out.append("extern \"C\" {")
        for imp in group:
            for d in doc_lines(imp):
                out.append(f"    /// {d}")
            args = []
            for p in imp["params"]:
                ty = T[num_kind(p)]
                if p.get("role") == "ptr":
                    ty = "*mut u8" if is_out_buffer(p) else "*const u8"
                args.append(f'{p["name"]}: {ty}')
            res = imp.get("result")
            ret = f' -> {T[num_kind(res)]}' if res else ""
            out.append(f'    pub fn {binding_name(imp)}({", ".join(args)}){ret};')
            out.append("")
        out.append("}")
        out.append("")
    return "src/ffi_generated.rs", "\n".join(out)


def emit_zig(abi, imports):
    T = {"i32": "i32", "u32": "u32", "i64": "i64", "u64": "u64",
         "f64": "f64", "f32": "f32"}
    out = [f"// {BANNER}", "//",
           "// Raw imports only; the ergonomic wrappers are in gearbox.zig.", ""]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"/// {d}")
        args = []
        for p in imp["params"]:
            ty = T[num_kind(p)]
            if p.get("role") == "ptr":
                ty = "?[*]u8" if is_out_buffer(p) else "?[*]const u8"
            args.append(f'{p["name"]}: {ty}')
        res = imp.get("result")
        # noreturn is load-bearing in Zig, not decoration: it lets the compiler
        # see that control does not come back from abort.
        ret = T[num_kind(res)] if res else ("noreturn" if imp.get("noreturn") else "void")
        out.append(f'pub extern "{imp["module"]}" fn {binding_name(imp)}'
                   f'({", ".join(args)}) {ret};')
        out.append("")
    return "raw_generated.zig", "\n".join(out)


def emit_go(abi, imports):
    T = {"i32": "int32", "u32": "uint32", "i64": "int64", "u64": "uint64",
         "f64": "float64", "f32": "float32"}
    out = [f"// {BANNER}", "//",
           "// Raw imports only; the ergonomic wrappers are in gearbox.go.", "",
           "package gearbox", "", 'import "unsafe"', "",
           "var _ = unsafe.Pointer(nil) // keep the import when no ptr is used",
           ""]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"// {d}")
        args = []
        for p in imp["params"]:
            ty = "unsafe.Pointer" if p.get("role") == "ptr" else T[num_kind(p)]
            args.append(f'{p["name"]} {ty}')
        res = imp.get("result")
        ret = f' {T[num_kind(res)]}' if res else ""
        out.append(f'//go:wasmimport {imp["module"]} {imp["name"]}')
        out.append(f'func raw{camel(binding_name(imp))[0].upper() + camel(binding_name(imp))[1:]}'
                   f'({", ".join(args)}){ret}')
        out.append("")
    return "raw_generated.go", "\n".join(out)


def emit_assemblyscript(abi, imports):
    T = {"i32": "i32", "u32": "u32", "i64": "i64", "u64": "u64",
         "f64": "f64", "f32": "f32"}
    out = [f"// {BANNER}", "//",
           "// Raw imports only; the ergonomic wrappers are in gearbox.ts.", ""]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"// {d}")
        args = []
        for p in imp["params"]:
            ty = "usize" if p.get("role") == "ptr" else T[num_kind(p)]
            args.append(f'{p["name"]}: {ty}')
        res = imp.get("result")
        ret = T[num_kind(res)] if res else "void"
        out.append(f'@external("{imp["module"]}", "{imp["name"]}")')
        # _camelCase, matching the convention gearbox.ts already uses for its
        # raw layer, so the ergonomic wrappers need no rewriting.
        out.append(f'export declare function _{camel(binding_name(imp))}'
                   f'({", ".join(args)}): {ret};')
        out.append("")
    return "assembly/raw_generated.ts", "\n".join(out)


def emit_java(abi, imports):
    T = {"i32": "int", "i64": "long", "f64": "double", "f32": "float"}
    out = [f"/* {BANNER}", " *",
           " * Raw imports only. The ergonomic wrappers, the UTF-8 codec and the",
           " * capability notes are in Gearbox.java.", " */", "",
           "package org.opendoctrines.gearbox;", "",
           "import org.teavm.interop.Import;", "",
           "public final class GearboxRaw {", "    private GearboxRaw() { }", ""]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"    /** {d} */" if len(doc_lines(imp)) == 1 else f"    // {d}")
        args = []
        for p in imp["params"]:
            # Pointers are int offsets into linear memory; see Address.ofData.
            ty = "int" if p.get("role") == "ptr" else T.get(p["type"], p["type"])
            args.append(f'{ty} {camel(p["name"])}')
        res = imp.get("result")
        ret = T.get(res["type"], res["type"]) if res else "void"
        out.append(f'    @Import(module = "{imp["module"]}", name = "{imp["name"]}")')
        out.append(f'    public static native {ret} {camel(binding_name(imp))}'
                   f'({", ".join(args)});')
        out.append("")
    out.append("}")
    return "gearbox/src/main/java/org/opendoctrines/gearbox/GearboxRaw.java", "\n".join(out)


def emit_typescript(abi, imports):
    """Declarations for the raw layer. The script-facing `gearbox` object is
    declared by hand in types/gearbox.d.ts, because its shape is the ergonomic
    one and deliberately differs from the wire signatures."""
    T = {"i32": "number", "i64": "number", "f64": "number", "f32": "number"}
    out = [f"/* {BANNER}", " *",
           " * The wire-level ABI, for reference and for anyone binding it",
           " * directly. Mods should use the `gearbox` global in gearbox.d.ts,",
           " * which is the ergonomic shape.", " */", "",
           "declare namespace GearboxRaw {"]
    for imp in imports:
        for d in doc_lines(imp):
            out.append(f"  // {d}")
        args = ", ".join(f'{camel(p["name"])}: {T.get(p["type"], "number")}'
                         for p in imp["params"])
        res = imp.get("result")
        ret = T.get(res["type"], "number") if res else "void"
        out.append(f'  function {camel(binding_name(imp))}({args}): {ret};')
        out.append("")
    out.append("}")
    return "types/raw_generated.d.ts", "\n".join(out)


def c_type(spec, is_param, imp):
    """C type for one param or result. Handles keep their typedefs, and
    signedness comes from abi.json rather than from the wasm type, which does
    not carry it."""
    T = {"i32": "uint32_t", "i64": "int64_t", "f64": "double", "f32": "float"}
    role = spec.get("role", "")
    if role.startswith("handle:"):
        return "gearbox_" + role.split(":", 1)[1]
    if role == "enum:log_level":
        return "gearbox_log_level"
    if is_param and role == "ptr":
        if spec.get("struct"):
            return f"{spec['struct']}*"
        if is_out_buffer(spec):
            # An asset is arbitrary bytes; a name is text.
            return "void*" if imp.get("module") == "gearbox:assets" else "char*"
        return "const char*"
    if spec["type"] == "i32":
        return "int32_t" if spec.get("signed") else "uint32_t"
    if spec["type"] == "i64":
        return "uint64_t" if spec.get("unsigned") else "int64_t"
    return T.get(spec["type"], spec["type"])


def emit_c(abi, imports):
    """Declarations for sdk/gearbox.h, which #includes this.

    gearbox.h stays hand-written because it is the contract document and most
    of its value is the prose. What lives here is everything mechanical: the
    constants, the log-level enum, the env struct (whose layout is ABI and must
    not drift), the 18 imports and the 5 exports.

    C++, Lua, JavaScript and Python all reach the ABI through gearbox.h, so
    generating this one file gives five SDKs their raw layer from abi.json.
    """
    T = {"i32": "uint32_t", "i64": "int64_t", "f64": "double", "f32": "float"}
    ST = {"u32": "uint32_t", "u8": "uint8_t", "i32": "int32_t"}

    out = [f"/* {BANNER}", " *",
           " * Included by gearbox.h, which carries the prose. Everything here is",
           " * mechanical: constants, the env struct layout, and the declarations.",
           " */", "",
           "#ifndef GEARBOX_GENERATED_H", "#define GEARBOX_GENERATED_H", ""]

    out.append("/* ------------------------------------------------- constants -- */")
    for k, v in abi["constants"].items():
        out.append(f"#define {k} {v}{'u' if str(v).startswith('0x') else ''}")
    out.append("")

    # enums are plain {NAME: value} maps in abi.json.
    items = list(abi["enums"]["log_level"].items())
    out.append("typedef enum {")
    for i, (name, val) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        out.append(f"    GEARBOX_LOG_{name.upper():<6} = {val}{comma}")
    out += ["} gearbox_log_level;", ""]

    es = abi["env_struct"]
    out.append(f"/* {es.get('$comment','')} */")
    out.append("typedef struct {")
    for f in es["fields"]:
        c = ST.get(f["type"], f["type"])
        out.append(f"    {c:<9} {f['name']};"
                   + (f"   /* {f['doc']} */" if f.get("doc") else ""))
    out += [f"}} gearbox_env_t;",
            f"_Static_assert(sizeof(gearbox_env_t) == {es['size_bytes']},",
            '               "gearbox_env_t layout is ABI");', ""]

    out.append("/* --------------------------------------------------- imports -- */")
    for imp in imports:
        out.append("")
        for i, d in enumerate(doc_lines(imp)):
            out.append(f"/* {d}" if i == 0 else f" * {d}")
        out.append(" */")
        mod = imp["module"].split(":", 1)[1]
        args = [f'{c_type(p, True, imp)} {p["name"]}' for p in imp["params"]]
        res = imp.get("result")
        ret = c_type(res, False, imp) if res else "void"
        attr = ' __attribute__((noreturn))' if imp.get("noreturn") else ""
        out.append(f'GEARBOX_IMPORT("{mod}", "{imp["name"]}")')
        out.append(f'{ret} gearbox_{binding_name(imp)}({", ".join(args) or "void"}){attr};')

    out += ["", "/* --------------------------------------------------- exports -- */"]
    for exp in abi["exports"]:
        out.append("")
        for i, d in enumerate(doc_lines(exp)):
            out.append(f"/* {d}" if i == 0 else f" * {d}")
        out.append(" */")
        args = ", ".join(f'{c_type(p, True, exp)} {p["name"]}'
                         for p in exp.get("params", [])) or "void"
        res = exp.get("result")
        ret = c_type(res, False, exp) if res else "void"
        out.append(f'GEARBOX_EXPORT("{exp["name"]}")')
        out.append(f'{ret} {exp["name"]}({args});')

    out += ["", "#endif /* GEARBOX_GENERATED_H */"]
    return "gearbox_generated.h", "\n".join(out)


EMITTERS = [
    ("sdk",                emit_c),
    ("sdk/rust",           emit_rust),
    ("sdk/zig",            emit_zig),
    ("sdk/go",             emit_go),
    ("sdk/assemblyscript", emit_assemblyscript),
    ("sdk/java",           emit_java),
    ("sdk/js",             emit_typescript),
]



# ---------------------------------------------------------------- python ----
#
# WHY THESE ARE GENERATED NOW
#
# sdk/python bound 6 of the 184 imports, sdk/lua 14 and sdk/js 34, while the
# six compiled SDKs bound all 184 -- because those six are generated from this
# file and the three interpreted ones were written by hand. That is the whole
# explanation for the gap, and hand-writing the missing 178 three more times
# would rebuild the same gap the next time an import is added.
#
# THE CAPABILITY GROUPS ARE NOT OPTIONAL. Every wasm import must resolve at
# instantiation whether or not the script ever calls it, so binding a
# capability forces the manifest to declare it. Emitting all 184
# unconditionally would make every Python mod demand MapEditor and Net. So the
# output is grouped, each group behind GBX_WITH_<CAP>, and a mod compiles in
# exactly what it declares.
#
# THE ERGONOMICS COME FROM abi.json, not from a table here: a result with
# role "handle:*" returns None when absent, role "bool" returns a real bool,
# role "len" with a trailing out buffer does the two-call sizing and hands
# back a str. That is what keeps sdk/python/README.md's promises true for all
# 184 rather than for the six somebody wrote out.

PY_SKIP = {
    # Hand-written in gearbox_py.c, and staying there.
    "env",          # fills a struct; the binding returns a dict instead
    "recv",         # out buffer AND an out pointer -- two results, one call
    "fuel_budget",  # u64 sentinel means "unmetered", which is float('inf')
    "abort",        # does not return, so it must not build a PyObject
    "log",          # takes the level enum, and print() is routed through it
    # BINARY, not text. The generated out-buffer path decodes UTF-8 and would
    # corrupt a PNG; the hand-written one returns bytes, which is what an asset
    # is. The ABI has no text/binary marker, so this is a named exception
    # rather than something derivable.
    "read",
}


def py_cap_macro(cap):
    """GBX_WITH_POLITICS_READ from "Politics.Read". None -> core, always on."""
    if not cap:
        return None
    return "GBX_WITH_" + cap.upper().replace(".", "_")


def py_param_kinds(imp):
    """Each param as a binding kind, pairing (ptr,len) into one argument."""
    ps = imp.get("params") or []
    out, k = [], 0
    while k < len(ps):
        p = ps[k]
        nxt = ps[k + 1] if k + 1 < len(ps) else None
        role = p.get("role")
        if role == "ptr" and nxt and nxt.get("role") == "len":
            out.append(("outbuf" if p.get("dir") == "out" else "instr", p))
            k += 2
            continue
        if role == "ptr":
            out.append(("rawptr", p))
            k += 1
            continue
        out.append((num_kind(p), p))
        k += 1
    return out


def py_emittable(imp):
    if imp["name"] in PY_SKIP:
        return False
    kinds = [k for k, _ in py_param_kinds(imp)]
    if "rawptr" in kinds:
        return False
    # At most one out buffer, and it must be last -- that is the shape the
    # two-call sizing idiom covers. `recv` is the only import that is not.
    if kinds.count("outbuf") > 1:
        return False
    if "outbuf" in kinds and kinds[-1] != "outbuf":
        return False
    return True


def emit_python(abi, imports):
    L = [
        "/* Generated by tools/gen_bindings.py from sdk/abi.json. Do not edit. */",
        "/*",
        " * Every host import as a Python function, grouped by capability.",
        " *",
        " * Included by gearbox_py.c, which keeps the handful that cannot be",
        " * generated: env (fills a struct), recv (two results), fuelBudget (a",
        " * sentinel that means infinity), abort (does not return) and log (the",
        " * level enum, and print() routes through it).",
        " */",
        "#ifndef GBX_PY_GENERATED_H",
        "#define GBX_PY_GENERATED_H",
        "",
    ]
    rows = [
        "/* Generated by tools/gen_bindings.py from sdk/abi.json. Do not edit. */",
        "/* Included inside gbx_methods[] in gearbox_py.c. */",
        "",
    ]

    by_cap = {}
    for imp in imports:
        if not py_emittable(imp):
            continue
        by_cap.setdefault(imp.get("capability"), []).append(imp)

    for cap in sorted(by_cap, key=lambda c: (c is not None, c or "")):
        macro = py_cap_macro(cap)
        group = by_cap[cap]
        head = f"/* ---- {cap or 'core'} ({len(group)}) ---- */"
        L.append(head)
        rows.append(head)
        if macro:
            L.append(f"#if {macro}")
            rows.append(f"#if {macro}")

        for imp in group:
            name = imp["name"]
            cname = "gbxpy_" + binding_name(imp)
            # The C SYMBOL is binding_name, not the wire name: gearbox:assets
            # "read" is gearbox_asset_read, and calling gearbox_read would not
            # link. emit_c uses binding_name at line 358 for exactly this.
            call = "gearbox_" + binding_name(imp)
            kinds = py_param_kinds(imp)
            res = imp.get("result") or {}
            rrole, rtype = res.get("role"), res.get("type")

            fmt, decls, args, pre, post = "", [], [], [], []
            for idx, (kind, p) in enumerate(kinds):
                v = f"a{idx}"
                if kind == "instr":
                    fmt += "s#"
                    decls.append(f"    const char *{v} = NULL; Py_ssize_t {v}_n = 0;")
                    args.append(f"{v}, (uint32_t){v}_n")
                elif kind == "outbuf":
                    args.append("NULL, 0")          # replaced by the sizing block
                elif kind == "f64":
                    fmt += "d"
                    decls.append(f"    double {v} = 0;")
                    args.append(v)
                elif kind in ("i64", "u64"):
                    fmt += "L"
                    decls.append(f"    long long {v} = 0;")
                    args.append(f"({'int64_t' if kind == 'i64' else 'uint64_t'}){v}")
                elif kind == "i32":
                    fmt += "i"
                    decls.append(f"    int {v} = 0;")
                    args.append(f"(int32_t){v}")
                else:                                # u32 and handles
                    fmt += "I"
                    decls.append(f"    unsigned int {v} = 0;")
                    args.append(f"(uint32_t){v}")

            has_out = any(k == "outbuf" for k, _ in kinds)
            noargs = not fmt
            L.append("")
            # The wire module and name, quoted, so a reader (and
            # check_bindings.py) can see exactly which import this binds.
            # gearbox_country_party_name has no word boundary before
            # "country_party_name", so the lint cannot find it in the symbol.
            L.append(f'/* {imp["module"]} "{imp["name"]}" */')
            for d in doc_lines(imp):
                L.append(f"/* {d} */")
            sig_args = "PyObject *self, PyObject *args"
            L.append(f"static PyObject *{cname}({sig_args}) {{")
            L.append("    (void)self;" + ("  (void)args;" if noargs else ""))
            L.extend(decls)
            if fmt:
                L.append(f'    if (!PyArg_ParseTuple(args, "{fmt}", '
                         + ", ".join("&a%d" % i for i, (k, _) in enumerate(kinds)
                                     if k != "outbuf")
                         + ")) return NULL;")
                # s# binds two variables; fix those up.
                for i, (k, _) in enumerate(kinds):
                    if k == "instr":
                        L[-1] = L[-1].replace(f"&a{i}", f"&a{i}, &a{i}_n")

            head_args = ", ".join(a for a in args if a != "NULL, 0")
            if has_out:
                # Two-call sizing, exactly as README.md promises: ask for the
                # length, allocate, ask again. A caller never sees a buffer.
                lead = (head_args + ", ") if head_args else ""
                L.append(f"    uint32_t need = {call}({lead}NULL, 0);")
                L.append('    if (need == 0) return PyUnicode_FromString("");')
                L.append("    char *buf = (char *)PyMem_Malloc(need);")
                L.append("    if (!buf) return PyErr_NoMemory();")
                L.append(f"    uint32_t got = {call}({lead}buf, need);")
                L.append("    if (got > need) got = need;")
                L.append('    PyObject *v = PyUnicode_DecodeUTF8(buf, (Py_ssize_t)got, "replace");')
                L.append("    PyMem_Free(buf);")
                L.append("    return v;")
            else:
                inner = f"{call}({head_args})"
                if not rtype:
                    L.append(f"    {inner};")
                    L.append("    Py_RETURN_NONE;")
                elif rrole == "bool":
                    L.append(f"    return PyBool_FromLong((long){inner});")
                elif rrole and rrole.startswith("handle:"):
                    # None, not a sentinel int -- the one place the binding
                    # deliberately departs from the wire, and it is documented.
                    L.append(f"    uint32_t h = {inner};")
                    L.append("    if (h == GEARBOX_INVALID) Py_RETURN_NONE;")
                    L.append("    return PyLong_FromUnsignedLong(h);")
                elif rtype in ("f32", "f64"):
                    L.append(f"    return PyFloat_FromDouble((double){inner});")
                elif rtype == "i64":
                    k = num_kind(res)
                    fn = ("PyLong_FromUnsignedLongLong((unsigned long long)"
                          if k == "u64" else "PyLong_FromLongLong((long long)")
                    L.append(f"    return {fn}{inner});")
                elif num_kind(res) == "i32":
                    L.append(f"    return PyLong_FromLong((long)(int32_t){inner});")
                else:
                    L.append(f"    return PyLong_FromUnsignedLong((unsigned long){inner});")
            L.append("}")

            flags = "METH_NOARGS" if noargs else "METH_VARARGS"
            doc = (imp.get("doc") or "").replace("\\", "\\\\").replace('"', '\\"')
            doc = doc.replace("\n", " ")[:180]
            rows.append(f'    {{"{camel(binding_name(imp))}", {cname}, {flags}, "{doc}"}},')

        if macro:
            L.append(f"#endif /* {macro} */")
            rows.append(f"#endif /* {macro} */")
        L.append("")
        rows.append("")

    L.append("#endif /* GBX_PY_GENERATED_H */")
    return "gearbox_py_generated.h", "\n".join(L), "gearbox_py_methods.inc", "\n".join(rows)




# ------------------------------------------------------------- lua & js ----
#
# Same classification as the Python emitter -- py_param_kinds and py_emittable
# are shared, because "which imports can be generated" is a property of the
# ABI and not of a language. What differs is only the codegen, and two
# deliberate conventions that each SDK already documented:
#
#   Lua  is 1-BASED. Its hand-written country_at subtracted one before calling
#        and says so ("Lua is 1-based; the ABI is 0-based. Convert here so
#        scripts read naturally"). 36 params are named "index", and those are
#        the ones that convert. Everything else -- a country or province
#        handle -- is an opaque id, not an ordinal, and must NOT be shifted.
#   JS   stays 0-based, as its hand-written country_at does, because JS arrays
#        are 0-based too.
#
# Getting that backwards would be silent: every index off by one, nothing
# crashing.

LUA_SKIP = {"env", "recv", "fuel_budget", "abort", "log", "read"}
JS_SKIP  = LUA_SKIP


def _is_index(par):
    """A 0-based ordinal the caller counts with, as opposed to a handle."""
    return par.get("name") == "index" and not par.get("role")


def emit_lua(abi, imports):
    L = ["/* Generated by tools/gen_bindings.py from sdk/abi.json. Do not edit. */",
         "/*",
         " * Every host import as a Lua function, grouped by capability.",
         " *",
         " * Included by gearbox_lua.c, which keeps the ones that cannot be",
         " * generated: log (the level enum, and print routes through it), env",
         " * (a struct), abort (does not return), fuelBudget (a sentinel meaning",
         " * infinity), assetRead (bytes, not text) and recv (two results).",
         " *",
         " * INDICES ARE 1-BASED HERE, as they are everywhere else in Lua; the",
         " * ABI is 0-based and the conversion happens at the boundary.",
         " */",
         "#ifndef GBX_LUA_GENERATED_H",
         "#define GBX_LUA_GENERATED_H",
         ""]
    rows = ["/* Generated by tools/gen_bindings.py from sdk/abi.json. Do not edit. */",
            "/* Included inside gbx_funcs[] in gearbox_lua.c. */",
            ""]

    by_cap = {}
    for imp in imports:
        if imp["name"] in LUA_SKIP or not py_emittable(imp):
            continue
        by_cap.setdefault(imp.get("capability"), []).append(imp)

    for cap in sorted(by_cap, key=lambda c: (c is not None, c or "")):
        macro = py_cap_macro(cap)
        head = f"/* ---- {cap or 'core'} ({len(by_cap[cap])}) ---- */"
        L.append(head); rows.append(head)
        if macro:
            L.append(f"#if {macro}"); rows.append(f"#if {macro}")

        for imp in by_cap[cap]:
            cname = "gbxlua_" + binding_name(imp)
            call = "gearbox_" + binding_name(imp)
            kinds = py_param_kinds(imp)
            res = imp.get("result") or {}
            rrole, rtype = res.get("role"), res.get("type")

            L.append("")
            L.append(f'/* {imp["module"]} "{imp["name"]}" */')
            for d in doc_lines(imp):
                L.append(f"/* {d} */")
            L.append(f"static int {cname}(lua_State *L) {{")
            if not kinds:
                L.append("    (void)L;")

            args, slot = [], 1
            for kind, par in kinds:
                v = f"a{slot}"
                if kind == "instr":
                    L.append(f"    size_t {v}_n = 0;")
                    L.append(f"    const char *{v} = luaL_checklstring(L, {slot}, &{v}_n);")
                    args.append(f"{v}, (uint32_t){v}_n")
                elif kind == "outbuf":
                    args.append("__OUT__")
                    continue
                elif kind == "f64":
                    L.append(f"    double {v} = (double)luaL_checknumber(L, {slot});")
                    args.append(v)
                elif kind in ("i64", "u64"):
                    L.append(f"    lua_Integer {v} = luaL_checkinteger(L, {slot});")
                    args.append(f"({'int64_t' if kind == 'i64' else 'uint64_t'}){v}")
                else:
                    L.append(f"    lua_Integer {v} = luaL_checkinteger(L, {slot});")
                    # 1-based only for ordinals; a handle is not an ordinal.
                    adj = " - 1" if _is_index(par) else ""
                    ctype = "int32_t" if kind == "i32" else "uint32_t"
                    args.append(f"({ctype})({v}{adj})")
                slot += 1

            head_args = ", ".join(a for a in args if a != "__OUT__")
            if any(a == "__OUT__" for a in args):
                lead = (head_args + ", ") if head_args else ""
                L.append(f"    uint32_t need = {call}({lead}NULL, 0);")
                L.append('    if (need == 0) { lua_pushliteral(L, ""); return 1; }')
                L.append("    luaL_Buffer b;")
                L.append("    char *dst = luaL_buffinitsize(L, &b, need);")
                L.append(f"    uint32_t got = {call}({lead}dst, need);")
                L.append("    if (got > need) got = need;   /* host grew it between calls */")
                L.append("    luaL_pushresultsize(&b, got);")
                L.append("    return 1;")
            else:
                inner = f"{call}({head_args})"
                if not rtype:
                    L.append(f"    {inner};")
                    L.append("    return 0;")
                elif rrole == "bool":
                    L.append(f"    lua_pushboolean(L, (int){inner});")
                    L.append("    return 1;")
                elif rrole and rrole.startswith("handle:"):
                    L.append(f"    uint32_t h = {inner};")
                    L.append("    if (h == GEARBOX_INVALID) lua_pushnil(L);")
                    L.append("    else lua_pushinteger(L, (lua_Integer)h);")
                    L.append("    return 1;")
                elif rtype in ("f32", "f64"):
                    L.append(f"    lua_pushnumber(L, (lua_Number){inner});")
                    L.append("    return 1;")
                else:
                    L.append(f"    lua_pushinteger(L, (lua_Integer){inner});")
                    L.append("    return 1;")
            L.append("}")
            rows.append(f'    {{"{camel(binding_name(imp))}", {cname}}},')

        if macro:
            L.append(f"#endif /* {macro} */"); rows.append(f"#endif /* {macro} */")
        L.append(""); rows.append("")

    L.append("#endif /* GBX_LUA_GENERATED_H */")
    return "gearbox_lua_generated.h", "\n".join(L), "gearbox_lua_funcs.inc", "\n".join(rows)


def emit_js(abi, imports):
    L = ["/* Generated by tools/gen_bindings.py from sdk/abi.json. Do not edit. */",
         "/*",
         " * Every host import as a QuickJS function, grouped by capability.",
         " *",
         " * Included by gearbox_qjs.c, which keeps log, env, abort, fuelBudget,",
         " * assetRead and recv -- see the note there.",
         " *",
         " * Indices are 0-BASED, as the ABI and JS arrays both are.",
         " */",
         "#ifndef GBX_JS_GENERATED_H",
         "#define GBX_JS_GENERATED_H",
         ""]
    rows = ["/* Generated by tools/gen_bindings.py from sdk/abi.json. Do not edit. */",
            "/* Included inside gbx_funcs[] in gearbox_qjs.c. */",
            ""]

    by_cap = {}
    for imp in imports:
        if imp["name"] in JS_SKIP or not py_emittable(imp):
            continue
        by_cap.setdefault(imp.get("capability"), []).append(imp)

    for cap in sorted(by_cap, key=lambda c: (c is not None, c or "")):
        macro = py_cap_macro(cap)
        head = f"/* ---- {cap or 'core'} ({len(by_cap[cap])}) ---- */"
        L.append(head); rows.append(head)
        if macro:
            L.append(f"#if {macro}"); rows.append(f"#if {macro}")

        for imp in by_cap[cap]:
            cname = "gbxjs_" + binding_name(imp)
            call = "gearbox_" + binding_name(imp)
            kinds = py_param_kinds(imp)
            res = imp.get("result") or {}
            rrole, rtype = res.get("role"), res.get("type")
            nargs = sum(1 for k, _ in kinds if k != "outbuf")

            L.append("")
            L.append(f'/* {imp["module"]} "{imp["name"]}" */')
            for d in doc_lines(imp):
                L.append(f"/* {d} */")
            L.append(f"static JSValue {cname}(JSContext *ctx, JSValueConst this_val,")
            L.append("                        int argc, JSValueConst *argv) {")
            L.append("    (void)this_val;" + ("  (void)argc; (void)argv;" if not kinds else ""))
            if nargs:
                L.append(f"    if (argc < {nargs}) return JS_ThrowTypeError(ctx, "
                         f'"{camel(binding_name(imp))} expects {nargs} argument(s)");')

            args, frees, slot = [], [], 0
            for kind, par in kinds:
                v = f"a{slot}"
                if kind == "instr":
                    L.append(f"    size_t {v}_n = 0;")
                    L.append(f"    const char *{v} = JS_ToCStringLen(ctx, &{v}_n, argv[{slot}]);")
                    L.append(f"    if (!{v}) return JS_EXCEPTION;")
                    args.append(f"{v}, (uint32_t){v}_n")
                    frees.append(v)
                elif kind == "outbuf":
                    args.append("__OUT__")
                    continue
                elif kind == "f64":
                    L.append(f"    double {v} = 0;")
                    L.append(f"    if (JS_ToFloat64(ctx, &{v}, argv[{slot}])) return JS_EXCEPTION;")
                    args.append(v)
                elif kind in ("i64", "u64"):
                    L.append(f"    int64_t {v} = 0;")
                    L.append(f"    if (JS_ToInt64(ctx, &{v}, argv[{slot}])) return JS_EXCEPTION;")
                    args.append(f"({'int64_t' if kind == 'i64' else 'uint64_t'}){v}")
                else:
                    L.append(f"    int32_t {v} = 0;")
                    L.append(f"    if (!arg_i32(ctx, argv[{slot}], &{v})) return JS_EXCEPTION;")
                    args.append(f"({'int32_t' if kind == 'i32' else 'uint32_t'}){v}")
                slot += 1

            def release(indent="    "):
                return [f"{indent}JS_FreeCString(ctx, {f});" for f in frees]

            head_args = ", ".join(a for a in args if a != "__OUT__")
            if any(a == "__OUT__" for a in args):
                lead = (head_args + ", ") if head_args else ""
                L.append(f"    uint32_t need = {call}({lead}0, 0);")
                L.extend(release())
                L.append('    if (need == 0) return JS_NewStringLen(ctx, "", 0);')
                L.append("    char stackbuf[128];")
                L.append("    char *buf = stackbuf;")
                L.append("    if (need > sizeof stackbuf) {")
                L.append("        buf = js_malloc(ctx, need);")
                L.append("        if (!buf) return JS_EXCEPTION;")
                L.append("    }")
                # The string args were freed above, so re-fetching is wrong;
                # sized getters never take one -- assert that by construction.
                L.append(f"    uint32_t got = {call}({lead}buf, need);")
                L.append("    if (got > need) got = need;")
                L.append("    JSValue v = JS_NewStringLen(ctx, buf, got);")
                L.append("    if (buf != stackbuf) js_free(ctx, buf);")
                L.append("    return v;")
            else:
                inner = f"{call}({head_args})"
                if not rtype:
                    L.append(f"    {inner};")
                    L.extend(release())
                    L.append("    return JS_UNDEFINED;")
                else:
                    L.append(f"    {'double' if rtype in ('f32','f64') else 'uint64_t'} r ="
                             f" ({'double' if rtype in ('f32','f64') else 'uint64_t'}){inner};")
                    L.extend(release())
                    if rrole == "bool":
                        L.append("    return JS_NewBool(ctx, (int)r);")
                    elif rrole and rrole.startswith("handle:"):
                        L.append("    if ((uint32_t)r == GEARBOX_INVALID) return JS_NULL;")
                        L.append("    return JS_NewUint32(ctx, (uint32_t)r);")
                    elif rtype in ("f32", "f64"):
                        L.append("    return JS_NewFloat64(ctx, r);")
                    elif rtype == "i64":
                        L.append("    return JS_NewFloat64(ctx, (double)r);")
                    elif num_kind(res) == "i32":
                        L.append("    return JS_NewInt32(ctx, (int32_t)r);")
                    else:
                        L.append("    return JS_NewUint32(ctx, (uint32_t)r);")
            L.append("}")
            rows.append(f'    JS_CFUNC_DEF("{camel(binding_name(imp))}", {nargs}, {cname}),')

        if macro:
            L.append(f"#endif /* {macro} */"); rows.append(f"#endif /* {macro} */")
        L.append(""); rows.append("")

    L.append("#endif /* GBX_JS_GENERATED_H */")
    return "gearbox_js_generated.h", "\n".join(L), "gearbox_js_funcs.inc", "\n".join(rows)


EMITTERS.append(("sdk/python", emit_python))
EMITTERS.append(("sdk/lua", emit_lua))
EMITTERS.append(("sdk/js", emit_js))


def main():
    check = "--check" in sys.argv
    abi, imports = load()

    stale, written = [], 0
    outputs = []
    for base, emit in EMITTERS:
        produced = emit(abi, imports)
        # An emitter may return one file (rel, body) or several, flattened as
        # (rel, body, rel, body, ...). The interpreted SDKs need two: the
        # function bodies, and the rows that go inside an existing table --
        # a preprocessor #if cannot live inside a macro, so the rows have to
        # be textually included where the table is.
        for k in range(0, len(produced), 2):
            outputs.append((base, produced[k], produced[k + 1]))

    for base, rel, body in outputs:
        path = os.path.join(ROOT, base, rel)
        if not body.endswith("\n"):
            body += "\n"

        current = None
        if os.path.exists(path):
            with open(path) as f:
                current = f.read()

        if check:
            if current != body:
                stale.append(os.path.join(base, rel))
            continue

        if current == body:
            print(f"  unchanged  {base}/{rel}")
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(body)
        print(f"  wrote      {base}/{rel}")
        written += 1

    if check:
        if stale:
            print("These generated bindings are out of date with sdk/abi.json:")
            for s in stale:
                print(f"    {s}")
            print("\nRun: python3 tools/gen_bindings.py")
            return 1
        print(f"ok    {len(outputs)} generated binding(s) match sdk/abi.json")
        return 0

    print(f"\n{len(imports)} imports -> {len(outputs)} bindings ({written} changed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
