#!/usr/bin/env python3
"""
Generate the no-op half of the dedicated server's raylib implementation.

    python3 tools/gen_server_raylib_stubs.py           # rewrite the file
    python3 tools/gen_server_raylib_stubs.py --check   # fail if it is stale

WHY GENERATED

src/server/ServerRaylib.cpp implements, by hand, every raylib function the
SIMULATION reads data through -- images, files, text, colour, time. This
generates the other half: the drawing, texture, shader, window, input and audio
entry points, as functions that do nothing.

There are over a hundred of them and they carry no decisions, so writing them
by hand would be a hundred chances to typo a signature for no benefit. They are
derived from raylib.h itself, which is the only thing that can be authoritative
about what raylib's API is.

The generated file is COMMITTED, not built on the fly: the server must build on
a machine with no Python, and a code generator in the build path is a build that
fails differently on every platform. --check keeps it honest, and runs in
tests/run_all.sh.

Nothing here is load-bearing for correctness. If a stub is missing the server
fails to LINK, naming the symbol -- which is the design: nothing can silently
reach a graphics layer that is not in the binary.
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "server", "ServerRaylibStubs.cpp")

# Where raylib.h is, in preference order. FetchContent puts one under each
# build directory; any of them will do, they are the same pinned release.
#
# A SYSTEM raylib counts too. This used to look only under build/, which meant
# the check failed outright on a machine that builds against Homebrew's raylib
# (CMakeLists prefers a system copy and never fetches one) or that simply keeps
# its build tree somewhere else. A generator that cannot find its input has to
# say so, but it should look everywhere the build itself would first.
CANDIDATES = [
    os.path.join(ROOT, b, d, "_deps", "raylib-src", "src", "raylib.h")
    for b in ("build", "cmake-build-debug", "build-release", "build-web", "build-android")
    for d in ("macos", "linux", "windows", "emscripten", "")
] + [
    "/opt/homebrew/include/raylib.h",
    "/usr/local/include/raylib.h",
    "/usr/include/raylib.h",
]


def find_header():
    for p in CANDIDATES:
        if os.path.exists(p):
            return p
    sys.exit("no raylib.h found -- configure a build directory, or install raylib")


def declarations(header_text):
    """name -> (return type, argument list), from raylib.h's RLAPI lines."""
    out = {}
    for line in header_text.splitlines():
        line = line.split("//")[0].strip()
        if not line.startswith("RLAPI "):
            continue
        m = re.match(r"RLAPI\s+(.+?)\s*\b(\w+)\s*\((.*)\)\s*;", line)
        if not m:
            continue
        ret, name, args = m.group(1).strip(), m.group(2), m.group(3).strip()
        out[name] = (ret, args or "void")
    return out


def implemented(path):
    """Function names ServerRaylib.cpp defines by hand.

    The argument list is matched WITHOUT newlines ([^;\\n]) on purpose. Allowing
    them lets the match run greedily to the last `) {` in the file, swallow every
    definition in between, and report one function as implemented where there
    were thirty -- which shows up as a duplicate-symbol link error naming
    whichever one happened to survive, and nothing pointing at this regex.
    """
    text = open(path).read()
    return set(re.findall(r"^[\w\* ]+?\b(\w+)\s*\([^;\n]*\)\s*\{", text, re.M))


def zero(ret):
    r = ret.replace("const", "").strip()
    if r == "void":
        return None
    if r.endswith("*"):
        return "nullptr"
    if r == "bool":
        return "false"
    if r in ("int", "unsigned int", "long", "float", "double", "char",
             "unsigned char", "unsigned short", "size_t"):
        return "0"
    return f"{r}{{}}"      # every raylib struct is aggregate-initialisable


def render(decls, skip):
    lines = [
        "// Generated by tools/gen_server_raylib_stubs.py -- do not edit by hand.",
        "//",
        "// The half of raylib the dedicated server does not do: drawing, textures,",
        "// shaders, windows, input, audio. Each entry point is present so the game's",
        "// source links, and does nothing when called.",
        "//",
        "// The hand-written half -- images, files, text, colour, time, everything the",
        "// simulation reads its own data through -- is in ServerRaylib.cpp, and the two",
        "// files together are the whole of raylib as far as the server is concerned. No",
        "// GL, no GLFW and no audio device is linked into the server binary at all.",
        "//",
        "// Regenerate after a raylib upgrade:  python3 tools/gen_server_raylib_stubs.py",
        "",
        '#include "raylib.h"',
        "",
    ]
    n = 0
    for name in sorted(decls):
        if name in skip:
            continue
        ret, args = decls[name]
        z = zero(ret)
        body = "" if z is None else f" return {z};"
        lines.append(f"{ret} {name}({args}) {{{body} }}")
        n += 1
    lines.append("")
    lines.append(f"// {n} entry points.")
    lines.append("")
    return "\n".join(lines), n


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed file is out of date")
    args = ap.parse_args()

    decls = declarations(open(find_header(), errors="ignore").read())
    skip = implemented(os.path.join(ROOT, "src", "server", "ServerRaylib.cpp"))
    text, n = render(decls, skip)

    if args.check:
        have = open(OUT).read() if os.path.exists(OUT) else ""
        if have != text:
            print("src/server/ServerRaylibStubs.cpp is stale.\n"
                  "Regenerate: python3 tools/gen_server_raylib_stubs.py")
            return 1
        print(f"ok    {n} raylib stubs match raylib.h")
        return 0

    open(OUT, "w").write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({n} entry points, "
          f"{len(skip)} implemented by hand)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
