#!/usr/bin/env python3
"""Berth the Modern Day fleets, using the same rules as the historical maps.

The open-water test and the hull vocabulary live in tools/naval_placement.py.
They used to live here and only here, in a shape nothing else could reuse --
which is how the historical maps came to be generated by a different script
with a different, much weaker idea of what counts as "in the sea", and shipped
with 98% of their hulls drawn overlapping the shore against 13% here.
"""
import json, os, sys, math, random
import numpy as np
from PIL import Image

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS_DIR)
from naval_placement import (clearance_field, coastal_anchor, find_berth,  # noqa: E402
                             hull_type, pixel_to_lonlat)
from fill_water_speckle import label_components, min_water_body  # noqa: E402

DATA_DIR = "data"
PROVINCES_JSON = os.path.join(DATA_DIR, "provinces.json")
COUNTRIES_JSON = os.path.join(DATA_DIR, "countries.json")
PORTS_JSON = os.path.join(DATA_DIR, "ports.json")
PROVINCES_PNG = os.path.join(DATA_DIR, "provinces.png")
LAND_SEA_PNG = os.path.join(DATA_DIR, "land_sea.png")
OUT_SHIPS = os.path.join(DATA_DIR, "ships.json")
MAP_W, MAP_H = 8192, 4096
random.seed(42)

NAVY_ENTRIES = [
    (5, 25, {"carrier": 2, "destroyer": 12, "boat": 11}),      # USA
    (23, 20, {"carrier": 1, "destroyer": 10, "boat": 9}),       # China
    (3, 15, {"carrier": 1, "destroyer": 7, "boat": 7}),        # Russia
    (10, 15, {"carrier": 1, "destroyer": 7, "boat": 7}),       # UK
    (47, 10, {"carrier": 1, "destroyer": 3, "boat": 6}),       # Japan (trimmed from 15)
    (27, 12, {"carrier": 1, "destroyer": 5, "boat": 6}),       # France
    (79, 15, {"carrier": 1, "destroyer": 7, "boat": 7}),       # India
    (68, 8, {"destroyer": 3, "boat": 5}),                       # S. Korea
    (40, 8, {"destroyer": 3, "boat": 5}),                       # Italy
    (51, 6, {"destroyer": 2, "boat": 4}),                       # Spain
    (215, 8, {"destroyer": 3, "boat": 5}),                      # Australia
    (2, 6, {"destroyer": 2, "boat": 4}),                        # Canada
    (62, 6, {"destroyer": 2, "boat": 4}),                       # Turkey
    (190, 6, {"destroyer": 2, "boat": 4}),                      # Brazil
    (19, 6, {"destroyer": 2, "boat": 4}),                       # Germany
    (22, 3, {"destroyer": 1, "boat": 2}),                       # Netherlands (trimmed from 5)
    (7, 5, {"destroyer": 2, "boat": 3}),                        # Sweden
]

def main():
    print("Loading province data...")
    with open(PROVINCES_JSON) as f:
        provinces = json.load(f)
    with open(COUNTRIES_JSON) as f:
        countries = json.load(f)
    try:
        with open(PORTS_JSON) as f:
            ports = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        print(f"  {PORTS_JSON} not found, generating empty ships.json")
        with open(OUT_SHIPS, "w") as f:
            json.dump([], f)
        print(f"Saved {OUT_SHIPS} (empty)")
        return

    prov = np.asarray(Image.open(PROVINCES_PNG).convert("RGB"), dtype=np.uint32)
    h, w, _ = prov.shape
    pid = prov[:, :, 0] << 16 | prov[:, :, 1] << 8 | prov[:, :, 2]
    land = np.asarray(Image.open(LAND_SEA_PNG).convert("L"), dtype=np.uint8) >= 128

    print("Labelling water and measuring clearance...")
    lbl, sizes = label_components(~land)
    big_water = (lbl > 0) & (sizes[lbl] >= min_water_body())
    clear = clearance_field(land)

    sel = pid != 0
    ys, xs = np.nonzero(sel)
    ids = pid[sel]
    top = int(ids.max()) + 1
    cnt = np.bincount(ids, minlength=top)
    sx = np.bincount(ids, weights=xs, minlength=top)
    sy = np.bincount(ids, weights=ys, minlength=top)

    # Harbours per country, best first, skipping any whose water is too narrow
    # to float a hull -- a reservoir passes the pixel-count test and is one
    # pixel across.
    by_country, unusable = {}, 0
    for pid_str, info in ports.items():
        p = int(pid_str)
        if p >= top or not cnt[p]:
            continue
        cid = provinces.get(pid_str, {}).get("country_id")
        if cid is None:
            continue
        centroid = (int(sx[p] / cnt[p]), int(sy[p] / cnt[p]))
        anchor = coastal_anchor(pid == p, big_water, centroid)
        if find_berth(clear, anchor[0], anchor[1], []) is None:
            unusable += 1
            continue
        by_country.setdefault(int(cid), []).append(
            (p, int(info.get("level", 1)), anchor))
    for v in by_country.values():
        v.sort(key=lambda t: (-t[1], t[0]))

    ships, taken, stranded = [], [], 0
    for cid, count, mix in NAVY_ENTRIES:
        harbours = by_country.get(cid, [])
        name = countries.get(str(cid), {}).get("name", str(cid))
        if not harbours:
            print(f"  {name}: no usable harbour, no fleet")
            continue
        # The declared mix, laid out in a fixed order rather than shuffled, so
        # that two runs of the pipeline produce the same navy.
        hulls = []
        for t in ("carrier", "destroyer", "boat"):
            hulls += [t] * mix.get(t, 0)
        while len(hulls) < count:
            hulls.append(hull_type(len(hulls)))
        hulls = hulls[:count]

        placed = 0
        for i, hull in enumerate(hulls):
            _p, _lvl, anchor = harbours[i % len(harbours)]
            berth = find_berth(clear, anchor[0], anchor[1], taken)
            if berth is None:
                stranded += 1
                continue
            bx, by, _c = berth
            taken.append((bx, by))
            lon, lat = pixel_to_lonlat(bx, by, w, h)
            ships.append({
                "country_id": cid,
                "type": hull,
                "lat": round(lat, 6),
                "lon": round(lon, 6),
                "health": 100,
                "crew": random.randint(300, 1500),
            })
            placed += 1
        print(f"  {name}: {placed} ships across {len(harbours)} harbours")

    if unusable:
        print(f"  {unusable} port(s) have no water wide enough for a hull")
    if stranded:
        print(f"  {stranded} ship(s) found no berth and were dropped")
    print(f"Total ships generated: {len(ships)}")
    with open(OUT_SHIPS, "w") as f:
        json.dump(ships, f, indent=2, separators=(",", ":"))
    print(f"Wrote {OUT_SHIPS}")


if __name__ == "__main__":
    main()
