#!/usr/bin/env python3
"""Outline the O.D. lockup into art/logo/od-mark.svg.

WHY THE LOGO IS PATHS AND THE ICON IS NOT

The app icon is a 1024x1024 political world map: it is colour, and a
black-and-white version of it is a grey smear. Everywhere the game needs ONE
flat colour, it needs a different mark, and that is what this builds.

The letterforms are the icon's own -- Press Start 2P, the face the Krita
sources are set in -- so the two read as one identity rather than two logos.
They are converted to SVG paths here rather than left as a <text> element,
because a text element renders as Press Start 2P only where that font is
installed and as something else everywhere else. A logo that changes shape
depending on the viewer's font list is not a logo.

The font is NOT redistributed by this: it is read from wherever it is
installed, and only outlines reach the repository. See art/README.md for the
licence note.

Run it after editing the lockup in Krita, or to change the text:

    python3 tools/make_logo_svg.py
    python3 tools/make_logo_svg.py --text "O.D." --out art/logo/od-mark.svg
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Where the face lives on each platform. Searched rather than configured,
# because the one person who edits the artwork already has it installed and
# should not have to say so.
FONT_DIRS = [
    os.path.expanduser("~/Library/Fonts"), "/Library/Fonts",      # macOS
    os.path.expanduser("~/.local/share/fonts"), "/usr/share/fonts",  # Linux
    os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts"),   # Windows
]
FONT_NAME = "PressStart2P-Regular.ttf"


def find_font():
    for d in FONT_DIRS:
        p = os.path.join(d, FONT_NAME)
        if os.path.isfile(p):
            return p
    for d in FONT_DIRS:
        if not os.path.isdir(d):
            continue
        for dirpath, _, names in os.walk(d):
            for n in names:
                if n.lower().replace(" ", "").startswith("pressstart2p"):
                    return os.path.join(dirpath, n)
    return None


def build(text, font_path):
    from fontTools.ttLib import TTFont
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.misc.transform import Transform

    f = TTFont(font_path)
    upm = f["head"].unitsPerEm
    gs, cmap, hmtx, glyf = f.getGlyphSet(), f.getBestCmap(), f["hmtx"], f["glyf"]

    paths, x = [], 0
    xmin = ymin = float("inf")
    xmax = ymax = float("-inf")
    for ch in text:
        if ord(ch) not in cmap:
            sys.exit(f"{font_path} has no glyph for {ch!r}")
        g = cmap[ord(ch)]
        sink = SVGPathPen(gs)
        # The font is Y-up and SVG is Y-down, so the outline is mirrored as it
        # is drawn rather than corrected with a transform on the group -- a
        # transform there would not survive someone editing the path data.
        gs[g].draw(TransformPen(sink, Transform(1, 0, 0, -1, x, 0)))
        d = sink.getCommands()
        if d.strip():
            paths.append(d)
        gl = glyf[g]
        if gl.numberOfContours:
            xmin = min(xmin, x + gl.xMin); xmax = max(xmax, x + gl.xMax)
            ymin = min(ymin, -gl.yMax);    ymax = max(ymax, -gl.yMin)
        x += hmtx[g][0]          # the font's own spacing, not eyeballed

    pad = upm * 0.10
    vx, vy = xmin - pad, ymin - pad
    vw, vh = (xmax - xmin) + 2 * pad, (ymax - ymin) + 2 * pad
    body = "\n".join(f'    <path d="{d}"/>' for d in paths)
    return f'''<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="{vx:.0f} {vy:.0f} {vw:.0f} {vh:.0f}"
     width="{vw / 4:.0f}" height="{vh / 4:.0f}" role="img" aria-label="Open Doctrines">
  <title>Open Doctrines</title>
  <!-- GENERATED by tools/make_logo_svg.py. Edit that, not this.

       ONE COLOUR, INHERITED. fill="currentColor" takes the colour of whatever
       it sits in, so black on a light page and white on a dark one are the
       same file. There is no second variant to keep in step, and nothing here
       encodes a palette.

       The glyphs are rectilinear, so crispEdges keeps their edges on device
       pixels instead of antialiasing them to grey at small sizes.

       NOTE FOR EDITORS: this is XML, so a double hyphen may not appear inside
       a comment. See packaging/windows/OpenDoctrines.manifest, which carries
       the same warning because the same mistake broke the Windows link once. -->
  <g fill="currentColor" shape-rendering="crispEdges">
{body}
  </g>
</svg>
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--text", default="O.D.")
    ap.add_argument("--out", default=os.path.join(ROOT, "art", "logo", "od-mark.svg"))
    ap.add_argument("--font", default=None)
    ap.add_argument("--check", action="store_true",
                    help="fail if the file on disk is not what this would write")
    a = ap.parse_args()

    font = a.font or find_font()
    if not font:
        sys.exit(f"{FONT_NAME} is not installed. It is on Google Fonts; this "
                 f"tool reads it from the system and never copies it into the "
                 f"repository.")
    svg = build(a.text, font)

    if a.check:
        if not os.path.exists(a.out):
            sys.exit(f"{a.out} does not exist")
        cur = open(a.out, encoding="utf-8").read()
        if cur != svg:
            sys.exit(f"{a.out} is not what tools/make_logo_svg.py produces; "
                     f"re-run it")
        print(f"ok    {os.path.relpath(a.out, ROOT)} matches the generator")
        return

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write(svg)
    print(f"wrote {os.path.relpath(a.out, ROOT)} from {os.path.basename(font)}")


if __name__ == "__main__":
    main()
