#!/usr/bin/env python3
"""Bake the timelapse watermark into a C++ header.

    python3 tools/make_watermark.py

WHY A BAKED BITMAP AND NOT TEXT

The timelapse exporter runs headless. `--export-timelapse` opens no window, so
there is no GL context, which rules out every raylib text path: GetFontDefault()
is filled in by InitWindow, ImageDrawText draws with it, and LoadFontEx ends in
a texture upload. A GIF exported from the command line is exactly the one that
ends up on a forum, so "the watermark only works when a window is open" would
have missed the case that matters.

So the mark is rendered ONCE, here, into an 8-bit alpha coverage map and emitted
as a header. Drawing it at export time is then a blend over the frame buffer --
no font, no context, no asset to ship or fail to find, and identical output on
every platform. At 180x11 the whole thing is under 2 KB of read-only data.

Alpha rather than 1-bit: a hard-edged 11px wordmark on a busy map reads as a
JPEG artefact. The coverage map keeps the antialiasing the font intended.
"""

import os
from PIL import Image, ImageDraw, ImageFont

TEXT = "OpenDoctrines  ·  pr1nted.itch.io"
FONT = "data/fonts/DejaVuSans.ttf"
SIZE = 11
OUT = "src/TimelapseMark.h"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    font = ImageFont.truetype(os.path.join(ROOT, FONT), SIZE)
    tmp = Image.new("L", (800, 40), 0)
    ImageDraw.Draw(tmp).text((4, 4), TEXT, fill=255, font=font)
    box = tmp.getbbox()
    mark = tmp.crop(box)
    w, h = mark.size
    data = list(mark.getdata())

    lines = []
    for i in range(0, len(data), 24):
        lines.append("    " + " ".join(f"{v:3d}," for v in data[i:i + 24]))

    header = f'''#pragma once

// GENERATED by tools/make_watermark.py -- do not edit by hand.
//
// "{TEXT}" rendered from {FONT} at {SIZE}px, stored as an
// 8-bit alpha coverage map. See that script for why this is baked rather than
// drawn with a font at export time (the exporter is headless: no GL, no fonts).

namespace odmark {{

inline constexpr int   WIDTH  = {w};
inline constexpr int   HEIGHT = {h};

inline constexpr unsigned char ALPHA[{w} * {h}] = {{
{chr(10).join(lines)}
}};

}}  // namespace odmark
'''
    out = os.path.join(ROOT, OUT)
    with open(out, "w") as f:
        f.write(header)
    print(f"wrote {OUT}: {w}x{h}, {w * h} bytes of alpha")


if __name__ == "__main__":
    main()
