#!/usr/bin/env python3
"""
Make the Ogg files smaller without changing a single decoded sample.

    python3 tools/shrink_audio.py                 # every .ogg under data/audio
    python3 tools/shrink_audio.py a.ogg b.ogg     # those files
    python3 tools/shrink_audio.py --check         # report only, write nothing

WHY

Music is 45 of the 62 megabytes a player downloads, and it is the one part no
general-purpose compressor can help with: Vorbis has already spent its entropy
budget, so deflate recovers 4% of it and a zip recovers nothing. That does not
mean the files are optimal. Two things in them are, and neither is audio.

  * PAGINATION. Ogg is a container: the Vorbis packets are wrapped in pages,
    each costing 27 bytes plus one byte per 255 bytes carried. The shipped
    files average a 4 KB page against a 65 KB maximum, so they pay that header
    about sixteen times more often than they need to. Re-muxing the SAME
    packets into full pages is free size.

  * ENTROPY CODING, via OptiVorbis. It rebuilds the Vorbis codebooks for the
    audio actually present instead of the ones the encoder guessed at up front,
    and it is worth 9% of the soundtrack -- 4.18 MB, more than every other
    saving in the release put together.

    THIS NEEDS THE DECODER PATCH, and shipping it without one is catastrophic
    rather than degraded. raylib's stb_vorbis used to refuse every optimised
    file with VORBIS_outofmem, which read like a format incompatibility and was
    written off as one for a while. It is not: OptiVorbis emits a codebook with
    `entries == 0`, which libvorbis and ffmpeg both accept, and stb_vorbis
    allocates its tables with

        return sz ? malloc(sz) : NULL;

    so a zero-size request comes back NULL and two callers read that as a failed
    allocation. tools/patch_raylib_vorbis.py fixes those two checks, CMakeLists
    applies it to the pinned raylib source, and the build fails outright if it
    cannot -- because the symptom otherwise is a game with no audio at all that
    every other check calls fine.

    --no-optivorbis turns it off for a build that has not taken the patch.

NOT A QUALITY TRADE, AND THAT IS CHECKED RATHER THAN CLAIMED. Every file is
decoded to raw PCM before and after and the two are compared byte for byte;
anything that does not match is discarded and the original left alone. A
re-encode -- oggenc, ffmpeg without `-c copy`, "just drop the bitrate a bit" --
would be a different operation entirely, and this tool will not do it.

THE LAST WORD BELONGS TO THE DECODER THE GAME SHIPS, not to the one that is
convenient to script. Two independent decoders agreeing that a file is unchanged
says nothing about whether a third can OPEN it, and that is exactly how the
OptiVorbis result passed every check here while being unplayable. After running
this, decode the result with raylib itself before believing it.

Deliberately NOT part of tools/run_pipeline.py. That pipeline builds the world
data, and it runs often; the audio is authored, changes rarely, and a full pass
takes far longer than it would ever save. Same arrangement as
tools/optimize_flag_svgs.py: run it when the content changes, not on a
schedule. What DOES belong in the pipeline is the map and image pass, because
those files are regenerated by the steps before it.

NEEDS ffmpeg for the remux and the PCM comparison. OptiVorbis is worth far more
than the remux alone -- 9% against the remux's 0.5% -- and is used when found.
Build it from source with:

    cargo install --git https://github.com/OptiVorbis/OptiVorbis --tag v0.3.2 \
        optivorbis_cli
"""

import argparse
import glob
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO = os.path.join(ROOT, "data", "audio")

# One Ogg page holds at most 255 segments of 255 bytes, so ~65 KB whatever we
# ask for. Asking for a long duration simply means every page fills up.
PAGE_SECONDS = 30


def have(tool):
    return shutil.which(tool) is not None


def pcm_digest(path):
    """The decoded audio, hashed by EVERY decoder available. None if none work.

    Two decoders, not one, and no channel or rate coercion on the way out.
    An earlier version of this asked ffmpeg for `-ac 2`, which upmixes -- and
    every sound effect in this game is MONO. The upmix normalised away a real
    difference: on 36 files the optimiser produced a stream that libvorbis
    decodes to 8108 bytes where the original gives 6218, and the gate passed
    them anyway because ffmpeg had resampled both to the same 32256 bytes. A
    conversion in the middle of a losslessness check can only hide things.

    So: raw native-channel PCM from ffmpeg, and oggdec (libvorbis, the
    reference implementation, sharing no code with ffmpeg). Both must agree
    with both, or the file is left alone.
    """
    digests = []
    try:
        out = subprocess.run(["ffmpeg", "-v", "error", "-i", path, "-f", "s32le", "-"],
                             capture_output=True, check=True).stdout
        digests.append(hashlib.sha256(out).hexdigest())
    except (OSError, subprocess.CalledProcessError):
        digests.append(None)
    if have("oggdec"):
        try:
            out = subprocess.run(["oggdec", "-Q", "-o", "-", path],
                                 capture_output=True, check=True).stdout
            digests.append(hashlib.sha256(out).hexdigest())
        except (OSError, subprocess.CalledProcessError):
            digests.append(None)
    # A decoder that failed is not evidence of sameness; refuse the file.
    if not digests or any(d is None for d in digests):
        return None
    return tuple(digests)


def remux(src, dst):
    """Same Vorbis packets, full pages. `-c:a copy` is what makes it lossless."""
    try:
        subprocess.run(["ffmpeg", "-v", "error", "-i", src, "-c:a", "copy",
                        "-page_duration", str(PAGE_SECONDS * 1_000_000), "-y", dst],
                       capture_output=True, check=True)
        return os.path.exists(dst) and os.path.getsize(dst) > 0
    except (OSError, subprocess.CalledProcessError):
        return False


def optivorbis(src, dst, enabled):
    """Rebuild the Vorbis entropy coding. OFF by default -- see the header."""
    if not enabled or not have("optivorbis"):
        return False
    try:
        subprocess.run(["optivorbis", src, dst], capture_output=True, check=True)
        return os.path.exists(dst) and os.path.getsize(dst) > 0
    except (OSError, subprocess.CalledProcessError):
        return False


def shrink_one(path, tmpdir, use_optivorbis=True):
    """(before, after, winner). Never returns a file whose PCM changed.

    Every candidate is verified on its own and the smallest SURVIVOR wins --
    they are not chained. Chaining them cost real ground: the remux changes the
    trailing granule position on short mono effects, so libvorbis decodes 8108
    bytes where it decoded 6218, and running it over OptiVorbis's output to save
    a further 33 bytes turned a sound that had compressed by half into a file
    that had to be thrown away whole. One stage being wrong for a file must not
    disqualify a stage that was right for it.
    """
    before = os.path.getsize(path)
    want = pcm_digest(path)
    if want is None:
        return before, before, False

    stem = os.path.join(tmpdir, "w")
    candidates = []
    if optivorbis(path, stem + "-ov.ogg", use_optivorbis):
        candidates.append(stem + "-ov.ogg")
        # The remux is still worth trying on top: on long tracks it fills pages
        # OptiVorbis left short, and there it is verifiably lossless.
        if remux(stem + "-ov.ogg", stem + "-ovmux.ogg"):
            candidates.append(stem + "-ovmux.ogg")
    if remux(path, stem + "-mux.ogg"):
        candidates.append(stem + "-mux.ogg")

    best, best_size = None, before
    for c in sorted(candidates, key=os.path.getsize):
        size = os.path.getsize(c)
        if size >= best_size:
            continue
        # The gate. Not "it probably round-trips" -- the samples, compared,
        # by every decoder on the machine.
        if pcm_digest(c) == want:
            best, best_size = c, size
            break
    if best is None:
        return before, before, False
    return before, best_size, best


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("files", nargs="*", help="Ogg files (default: everything under data/audio)")
    ap.add_argument("--check", action="store_true",
                    help="report what would be saved and write nothing")
    ap.add_argument("--quiet", action="store_true", help="only print the total")
    ap.add_argument("--no-optivorbis", action="store_true",
                    help="skip OptiVorbis. Only for a build that has not taken the "
                         "stb_vorbis patch -- see the header.")
    args = ap.parse_args()

    if not have("ffmpeg"):
        print("ffmpeg is needed for the remux and for the PCM comparison:\n"
              "  brew install ffmpeg", file=sys.stderr)
        return 1
    if not have("oggdec") and not args.quiet:
        print("  note: oggdec (vorbis-tools) not found -- the losslessness check will\n"
              "        run on ffmpeg alone. brew install vorbis-tools", file=sys.stderr)
    if args.no_optivorbis:
        print("  note: OptiVorbis skipped; re-pagination only, which is 0.5% where the\n"
              "        full pass is 9%.", file=sys.stderr)
    elif not have("optivorbis"):
        print("  note: optivorbis not found -- re-pagination only. Build it with:\n"
              "          cargo install --git https://github.com/OptiVorbis/OptiVorbis \\\n"
              "              --tag v0.3.2 optivorbis_cli", file=sys.stderr)

    paths = args.files or sorted(glob.glob(os.path.join(AUDIO, "**", "*.ogg"), recursive=True))
    if not paths:
        print("no .ogg files found")
        return 1

    total_before = total_after = 0
    changed = refused = 0
    with tempfile.TemporaryDirectory() as tmp:
        for p in paths:
            rel = os.path.relpath(p, ROOT)
            if not args.quiet:
                print(f"  {rel[:60]:<62} working...", end="", flush=True)
            before, after, best = shrink_one(p, tmp, not args.no_optivorbis)
            if not args.quiet:
                print("\r" + " " * 78 + "\r", end="")
            total_before += before
            total_after += after
            if not best:
                # Either nothing helped, or it did and the samples moved. The
                # second is the one worth hearing about.
                if after == before and pcm_digest(p) is None:
                    refused += 1
                    print(f"  {rel}: will not decode, left alone")
                continue
            changed += 1
            if not args.check:
                shutil.copy2(best, p + ".tmp")
                os.replace(p + ".tmp", p)
            if not args.quiet:
                verb = "would shrink" if args.check else "shrank"
                print(f"  {rel[:60]:<62} {before:>9} -> {after:>9} "
                      f"({after / before:5.1%}) {verb}")

    saved = total_before - total_after
    print(f"\n  {len(paths)} file(s), {changed} improved: "
          f"{total_before / 1e6:.2f} MB -> {total_after / 1e6:.2f} MB "
          f"({total_after / total_before:.1%}, {saved / 1e6:.2f} MB saved)")
    if refused:
        print(f"  {refused} file(s) could not be decoded and were left untouched")
    return 0


if __name__ == "__main__":
    sys.exit(main())
