#!/usr/bin/env python3
"""Keep the TempleOS build honest about the C++ one.

── WHAT THIS CAN AND CANNOT DO ──

It cannot port C++ to HolyC. There is no transpiler here and writing one for
tens of thousands of lines of raylib-flavoured C++ would be a larger project
than the game. Anybody promising that two independent implementations will
stay equal by themselves is promising something nobody delivers.

What it CAN do is make divergence loud, which is the part that actually
protects you. Two kinds of drift matter and they fail differently:

  * NUMBERS drift silently. If combat width is retuned in Game.h and the
    HolyC copy keeps the old figure, both builds run, neither complains, and
    the TempleOS game is quietly playing a different game. So the constants
    are GENERATED from the C++ and checked in; --check fails the build when
    they no longer match their source.

  * FEATURES drift visibly, but only if somebody looks. The C++ owns a list of
    map views with stable ids (kViewName[] in Game_Render.cpp). This reads
    that list, compares it with what the HolyC client implements, and names
    what is missing -- so adding a view to the desktop game fails CI until the
    TempleOS one has it too, or until it is explicitly recorded as skipped.

    python3 tools/templeos_sync.py            # regenerate
    python3 tools/templeos_sync.py --check    # fail if stale or diverged
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RENDER = ROOT / "src" / "Game_Render.cpp"
RESEARCH = ROOT / "src" / "Game_Research.cpp"
DATA = ROOT / "templeos" / "game.odd"
GAMEH = ROOT / "src" / "Game.h"
CLIENT = ROOT / "templeos" / "ODGame.HC"
OUT = ROOT / "templeos" / "Sync.HH"

# The constants the HolyC rules depend on, and what they are called in C++.
# Each is (holyc name, c++ name, scale) -- scaled because HolyC's rules work in
# integers and percent where the engine works in floats.
CONSTANTS = [
    ("SY_WIDTH_MIN",       "COMBAT_WIDTH_MIN",       1),
    ("SY_WIDTH_PER_AREA",  "COMBAT_WIDTH_PER_AREA",  1),
    ("SY_FORT_NARROW_PCT", "COMBAT_WIDTH_FORT_PCT",  1),
    ("SY_DEPTH_PER_DBL",   "DEPTH_PER_DOUBLING",     100),
    ("SY_DEPTH_MAX",       "DEPTH_MAX",              100),
]

# Views the TempleOS build deliberately does not have, with the reason. An
# entry here is a decision on the record; an absence from both lists is a bug.
SKIPPED = {
    "view.navy": "no fleets in the TempleOS rules yet",
}


def cpp_views() -> list[str]:
    src = RENDER.read_text(errors="replace")
    m = re.search(r"kViewName\[\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise SystemExit("kViewName[] not found in Game_Render.cpp -- the "
                         "view list has moved and this tool must follow it")
    return re.findall(r'"([^"]+)"', m[1])


def cpp_constants() -> dict[str, float]:
    src = GAMEH.read_text(errors="replace")
    out = {}
    for _, cpp, _ in CONSTANTS:
        m = re.search(r"constexpr\s+\w+\s+" + cpp + r"\s*=\s*([0-9.]+)f?\s*;", src)
        if not m:
            raise SystemExit(f"{cpp} not found in Game.h")
        out[cpp] = float(m[1])
    return out


def client_views() -> set[str]:
    """Which views the HolyC client claims, by the ids it names in one table."""
    src = CLIENT.read_text(errors="replace")
    # Read as one assignment per line, not as a brace initialiser: HolyC does
    # not accept those for arrays of pointers, so the client cannot write the
    # list in the shape a C programmer would reach for first.
    return set(re.findall(r'g_view_ids\[\d+\]\s*=\s*"([^"]+)"', src))


def render(views, consts) -> str:
    lines = [
        "/* GENERATED by tools/templeos_sync.py -- do not edit.",
        " *",
        " * These are the desktop game's numbers, lifted from src/Game.h, so that",
        " * retuning combat there cannot leave this build quietly playing a",
        " * different game. tests/templeos_sync_test.sh fails if this file and its",
        " * source disagree.",
        " */",
        "",
    ]
    for holy, cpp, scale in CONSTANTS:
        v = consts[cpp] * scale
        unit = "" if scale == 1 else f"  /* x{scale}, as an integer */"
        lines.append(f"#define {holy:<20} {int(round(v))}{unit}")
    lines += ["", "/* The map views the C++ owns, in its order. */", ""]
    for i, v in enumerate(views):
        name = "SY_" + v.replace("view.", "VIEW_").upper()
        lines.append(f"#define {name:<20} {i}")
    lines.append(f"#define SY_VIEW_COUNT        {len(views)}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    views = cpp_views()
    consts = cpp_constants()
    text = render(views, consts)

    problems = []
    if a.check:
        have = OUT.read_text() if OUT.exists() else ""
        if have != text:
            problems.append(f"{OUT.relative_to(ROOT)} is stale -- run "
                            f"tools/templeos_sync.py")
        mine = client_views()
        for v in views:
            if v not in mine and v not in SKIPPED:
                problems.append(f"the C++ has {v} and the TempleOS client does "
                                f"not implement it (add it, or record it in "
                                f"SKIPPED with a reason)")
        for v in SKIPPED:
            if v not in views:
                problems.append(f"{v} is recorded as skipped but the C++ no "
                                f"longer has it")
        # ── THE RESEARCH TREE, BY COUNT ──
        #
        # The tree is built in C++ code, not a data file, and templeos_data.py
        # parses those calls. If a node is added there and the baked table is
        # not rebuilt, the TempleOS build is simply missing a technology --
        # which nothing else here would notice.
        if DATA.exists():
            import struct as _s
            blob = DATA.read_bytes()
            if blob[:4] != b"ODTD":
                problems.append("templeos/game.odd is not a data file")
            else:
                baked = _s.unpack("<H", blob[6:8])[0]
                src = re.sub(r"//[^\n]*", "",
                             RESEARCH.read_text(errors="replace"))
                want = len(re.findall(r'add\(\s*"', src))
                if baked != want:
                    problems.append(
                        f"the research tree has {want} nodes and "
                        f"templeos/game.odd has {baked} -- run "
                        f"tools/templeos_data.py")
        else:
            problems.append("templeos/game.odd is missing -- run "
                            "tools/templeos_data.py")

        for v in sorted(mine - set(views)):
            problems.append(f"the TempleOS client implements {v}, which the "
                            f"C++ does not have")
        for p in problems:
            print("  " + p)
        if problems:
            print(f"templeos sync: {len(problems)} divergence(s)")
            return 1
        import struct as _s
        nodes = _s.unpack("<H", DATA.read_bytes()[6:8])[0]
        print(f"templeos sync: {len(views)} views, {len(CONSTANTS)} constants, "
              f"{nodes} research nodes, {len(SKIPPED)} skipped on the record")
        return 0

    OUT.write_text(text)
    print(f"{OUT.relative_to(ROOT)}: {len(CONSTANTS)} constants, {len(views)} views")
    for v in views:
        print(f"  {v}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
