/* GENERATED by tools/gen_bindings.py from sdk/abi.json. Do not edit.
 *
 * Raw imports only. The ergonomic wrappers, the UTF-8 codec and the
 * capability notes are in Gearbox.java.
 */

package org.opendoctrines.gearbox;

import org.teavm.interop.Import;

public final class GearboxRaw {
    private GearboxRaw() { }

    // Write a line to the game log and the mod menu's log view. Messages
    // longer than 2048 bytes are truncated. An out-of-bounds (ptr,len) is
    // refused and logged as an error against your mod rather than read.
    // `(iii)`
    @Import(module = "gearbox:core", name = "log")
    public static native void log(int level, int msg, int msgLen);

    // Fill a gearbox_env_t. Write your own sizeof into out->size FIRST; the
    // host writes at most that many bytes, so an older mod stays safe against
    // a newer host. If size is 0 or larger than the host's struct, the host
    // uses its own size.
    // `(i)`
    @Import(module = "gearbox:core", name = "env")
    public static native void env(int out);

    // Unrecoverable error. Traps out of the current call, disables the mod,
    // and shows the message to the user. Prefer returning an error from a hook
    // where you can.
    // `(ii)`
    @Import(module = "gearbox:core", name = "abort")
    public static native void abort(int msg, int msgLen);

    // The instruction budget for the current hook, or 0xFFFFFFFFFFFFFFFF when
    // unmetered. This is the LIMIT, not a live countdown: it does not decrease
    // as you run. Use it to size your work up front and count your own
    // iterations.
    // `()I`
    @Import(module = "gearbox:core", name = "fuel_budget")
    public static native long fuelBudget();

    // The current turn. 0 when no world is loaded.
    // `()i`
    @Import(module = "gearbox:gamestate.read", name = "turn_number")
    public static native int turnNumber();

    // How many countries exist. 0 when no world is loaded. Rebel factions are
    // not included.
    // `()i`
    @Import(module = "gearbox:gamestate.read", name = "country_count")
    public static native int countryCount();

    // The country at index in [0, country_count). Returns GEARBOX_INVALID
    // (0xFFFFFFFF) if out of range. Ordering is stable within a turn but not
    // across turns.
    // `(i)i`
    @Import(module = "gearbox:gamestate.read", name = "country_at")
    public static native int countryAt(int index);

    // Two-call sizing. Writes at most cap bytes of UTF-8 and returns the FULL
    // length. Call with cap 0 to size, then again to fill. A return greater
    // than cap means truncation, not failure. Returns 0 for an unknown
    // country.
    // `(iii)i`
    @Import(module = "gearbox:gamestate.read", name = "country_name")
    public static native int countryName(int country, int buf, int cap);

    // Treasury balance. 0 for an unknown country.
    // `(i)F`
    @Import(module = "gearbox:gamestate.read", name = "country_treasury")
    public static native double countryTreasury(int country);

    // How many provinces the country owns. 0 for an unknown country.
    // `(i)i`
    @Import(module = "gearbox:gamestate.read", name = "country_province_count")
    public static native int countryProvinceCount(int country);

    // Population of a province. 0 for an unknown province.
    // `(i)I`
    @Import(module = "gearbox:gamestate.read", name = "province_population")
    public static native long provincePopulation(int province);

    // Owning country, or GEARBOX_INVALID if unowned or unknown.
    // `(i)i`
    @Import(module = "gearbox:gamestate.read", name = "province_owner")
    public static native int provinceOwner(int province);

    // Register a panel and return its handle. Returns 0 (invalid) when
    // headless, when UI was revoked, or when you already hold 8 panels. Titles
    // are truncated to 64 bytes. Call this from mod_load, not from your draw
    // hook.
    // `(iiii)i`
    @Import(module = "gearbox:ui", name = "panel_register")
    public static native int panelRegister(int title, int titleLen, int minW, int minH);

    // Filled rectangle in panel-relative coordinates. Colour is 0xRRGGBBAA.
    // Coordinates outside the panel are clipped by the host; they cannot
    // escape it.
    // `(iiiiii)`
    @Import(module = "gearbox:ui", name = "draw_rect")
    public static native void drawRect(int panel, int x, int y, int w, int h, int rgba);

    // UTF-8 text in panel-relative coordinates. Truncated to 512 bytes per
    // call.
    // `(iiiiii)`
    @Import(module = "gearbox:ui", name = "draw_text")
    public static native void drawText(int panel, int x, int y, int rgba, int text, int textLen);

    // Immediate-mode button: draws it and returns 1 on the frame it is
    // clicked. One click activates one button -- the host consumes it, so
    // overlapping rects do not all fire. Label truncated to 64 bytes.
    // `(iiiiiii)i`
    @Import(module = "gearbox:ui", name = "button")
    public static native int button(int panel, int x, int y, int w, int h, int label, int labelLen);

    // Byte size of one of your own data/ files, or 0 if there is no such
    // asset. Names are relative to data/ and use '/' separators:
    // data/flags/fr.png is "flags/fr.png".
    // `(ii)i`
    @Import(module = "gearbox:assets", name = "size")
    public static native int assetSize(int name, int nameLen);

    // Two-call sizing, like country_name. Writes at most cap bytes and returns
    // the asset's full size. The name is looked up in your package's entry
    // list, never resolved as a filesystem path.
    // `(iiii)i`
    @Import(module = "gearbox:assets", name = "read")
    public static native int assetRead(int name, int nameLen, int buf, int cap);

    // Reads one of your own keys. Two-call sizing: returns the full value
    // length and writes at most cap bytes. Returns GEARBOX_INVALID if the key
    // is absent -- which is NOT the same as a zero-length value, so you can
    // tell 'never stored' from 'stored empty'. Values are arbitrary bytes, not
    // text.
    // `(iiii)i`
    @Import(module = "gearbox:storage", name = "get")
    public static native int get(int key, int keyLen, int buf, int cap);

    // Stores bytes under one of your own keys. Returns 1 on success, 0 if a
    // quota was exceeded (256 keys, 128-byte keys, 16 KiB per value, 64 KiB
    // total per mod) -- the reason is written to your log. Not written to disk
    // immediately: the store is flushed at turn boundaries and on unload,
    // because a mod may call this from a draw hook.
    // `(iiii)i`
    @Import(module = "gearbox:storage", name = "set")
    public static native int set(int key, int keyLen, int value, int valueLen);

    // Deletes one of your own keys. Returns 1 if it existed, 0 if it did not.
    // `(ii)i`
    @Import(module = "gearbox:storage", name = "remove")
    public static native int remove(int key, int keyLen);

    // Width of the province map in pixels. 0 when no world is loaded.
    // `()i`
    @Import(module = "gearbox:map", name = "width")
    public static native int width();

    // Height of the province map in pixels. 0 when no world is loaded.
    // `()i`
    @Import(module = "gearbox:map", name = "height")
    public static native int height();

    // How many provinces the loaded map has. 0 when no world is loaded.
    // `()i`
    @Import(module = "gearbox:map", name = "province_count")
    public static native int provinceCount();

    // Province handle at an index in [0, province_count). Returns
    // GEARBOX_INVALID if out of range. The order is stable across runs, unlike
    // the game's internal storage, so an index is safe to remember within a
    // session.
    // `(i)i`
    @Import(module = "gearbox:map", name = "province_at")
    public static native int provinceAt(int index);

    // The province's name. Two-call sizing: returns the full length and writes
    // at most cap bytes. Empty for an unknown province.
    // `(iii)i`
    @Import(module = "gearbox:map", name = "province_name")
    public static native int provinceName(int province, int buf, int cap);

    // X pixel coordinate of the province's centre. 0 for an unknown province.
    // `(i)F`
    @Import(module = "gearbox:map", name = "province_center_x")
    public static native double provinceCenterX(int province);

    // Y pixel coordinate of the province's centre. 0 for an unknown province.
    // `(i)F`
    @Import(module = "gearbox:map", name = "province_center_y")
    public static native double provinceCenterY(int province);

    // 1 if the province is land, 0 if it is sea or unknown. Sampled at the
    // province centre.
    // `(i)i`
    @Import(module = "gearbox:map", name = "province_is_land")
    public static native int provinceIsLand(int province);

    // How many provinces border this one. 0 for an unknown province.
    // `(i)i`
    @Import(module = "gearbox:map", name = "province_neighbor_count")
    public static native int provinceNeighborCount(int province);

    // The bordering province at an index in [0, province_neighbor_count).
    // GEARBOX_INVALID if out of range. Adjacency is computed once when the map
    // loads, so walking it is cheap.
    // `(ii)i`
    @Import(module = "gearbox:map", name = "province_neighbor_at")
    public static native int provinceNeighborAt(int province, int index);

    // 1 if the two countries are at war. Relations are symmetric, so the
    // argument order does not matter. 0 for unknown countries or for a country
    // with itself.
    // `(ii)i`
    @Import(module = "gearbox:diplomacy", name = "at_war")
    public static native int atWar(int a, int b);

    // 1 if the two countries are allied.
    // `(ii)i`
    @Import(module = "gearbox:diplomacy", name = "allied")
    public static native int allied(int a, int b);

    // 1 if the two countries have a non-aggression pact.
    // `(ii)i`
    @Import(module = "gearbox:diplomacy", name = "non_aggression")
    public static native int nonAggression(int a, int b);

    // 1 if the first country guarantees the second.
    // `(ii)i`
    @Import(module = "gearbox:diplomacy", name = "guaranteed")
    public static native int guaranteed(int a, int b);

    // PROPOSES a declaration of war, and returns 1 only if the game accepted
    // it. It is routed through the same code path any other actor uses, so
    // guarantee chains and war consequences follow exactly as normal -- a mod
    // cannot produce a diplomatic state the game itself could not reach.
    // Refused (0) if either country is unknown, they are the same country, or
    // they are already at war. Either outcome is written to your mod log, so a
    // player can see after the fact that a mod started a war.
    // `(ii)i`
    @Import(module = "gearbox:diplomacy", name = "propose_war")
    public static native int proposeWar(int attacker, int defender);

    // Sets a country's treasury outright. Returns 1 on success, 0 if the
    // country is unknown or the value is not finite and within +/-1e12 -- NaN
    // or infinity would silently poison every later calculation, so they are
    // refused rather than stored.
    // `(iF)i`
    @Import(module = "gearbox:gamestate.write", name = "set_country_treasury")
    public static native int setCountryTreasury(int country, double value);

    // Adds to a country's treasury. Usually what you want instead of set: it
    // composes with whatever the economy did this turn. Refused (0) if the
    // result would leave the sane range.
    // `(iF)i`
    @Import(module = "gearbox:gamestate.write", name = "add_country_treasury")
    public static native int addCountryTreasury(int country, double delta);

    // Transfers a province to another country. Routed through the same code
    // the game's own ceasefires use, so the province, the ownership lookup,
    // the per-pixel country map and both countries' pixel lists all stay
    // consistent -- and the previous owner's troops in that province are
    // disbanded, as they are for any other transfer. Returns 0 if either
    // handle is unknown or the country already owns it. Always written to your
    // mod log: territory changing hands is the most consequential thing a mod
    // can do.
    // `(ii)i`
    @Import(module = "gearbox:gamestate.write", name = "set_province_owner")
    public static native int setProvinceOwner(int province, int country);

    // How many floats are in the AI's feature vector. 0 when there is no AI or
    // no world.
    // `()i`
    @Import(module = "gearbox:neural", name = "feature_count")
    public static native int featureCount();

    // Copies the feature vector the AI would see for a country, as 32-bit
    // floats. Two-call sizing, but note cap counts FLOATS and the buffer must
    // therefore be cap*4 bytes. This is a snapshot: writing to your copy does
    // not affect the AI.
    // `(iii)i`
    @Import(module = "gearbox:neural", name = "features")
    public static native int features(int country, int buf, int cap);

    // How many reward channels the AI tracks (economy, politics, war, navy).
    // `()i`
    @Import(module = "gearbox:neural", name = "reward_count")
    public static native int rewardCount();

    // The running mean reward for one channel, indexed in [0, reward_count). 0
    // if out of range. OBSERVE ONLY: this capability has no import that writes
    // to the model, the optimiser state or the reward history, which is
    // deliberate -- a trained model is hours of work and a mod that could
    // quietly retrain it is not something a user can meaningfully consent to.
    // `(i)F`
    @Import(module = "gearbox:neural", name = "reward_mean")
    public static native double rewardMean(int index);

    // Sets a province's population. Returns 0 if the province is unknown, the
    // value is negative, or it exceeds 100 billion. The game stores population
    // in two places -- a map and a dense array used by the population texture
    // -- and this updates both, which is why it exists as an import rather
    // than being something a mod could do by other means.
    // `(iI)i`
    @Import(module = "gearbox:gamestate.write", name = "set_province_population")
    public static native int setProvincePopulation(int province, long value);

}
